vrm-c/UniVRM

Scripts/Editor/VRMExportUnityPackage.cs
`BuildPipeline.BuildPlayer` returns `BuildReport` on Unity 2018.
https://docs.unity3d.com/2018.1/Documentation/ScriptReference/BuildPipeline.BuildPlayer.html
=> fix compile error on Unity 2018

Scripts/Format/VRMImporter.cs, Scripts/UniTask/MainThreadDispatcher.cs, Scripts/UniTask/Scheduler.cs, Scripts/UniTask/StepScheduler.cs, Scripts/UniTask/TaskChain.cs, Scripts/UniTask/ThreadPoolScheduler.cs, Scripts/UniTask/ThreadScheduler.cs
ThreadScheduler has a bottleneck, it can not be processed in parallel.
Add ThreadPoolScheduler, it can be in parallel.
=> Add ThreadPoolScheduler

Scripts/Format/VRMImporter.cs, Scripts/UniTask/Schedulable.cs
Unity2017.x is Supported .NET4.6 Experimental. This Version can use async,await,Task.
However, VRMimporter and Schedulable don't use this in Unity2017.x.
=> Update make async,await,Task available to Unity2017.x

Scripts/BlendShape/BlendShapeBindingMerger.cs, Scripts/BlendShape/BlendShapeClip.cs, Scripts/BlendShape/MaterialValueBindingMerger.cs
BlendShape変更時にDictonaryのKey比較でBox化が発生していたため、それを回避するようにしました。
=> Optimize comparing struct in dictionary key

Assets/VRM/UniGLTF/Editor/UniGLTFTests.cs, Assets/VRM/UniGLTF/Scripts/Format/ExtensionsAndExtras/KHR_materials_unlit.cs, Assets/VRM/UniGLTF/Scripts/Format/glTF.cs, Assets/VRM/UniGLTF/Scripts/Format/glTFAnimation.cs, Assets/VRM/UniGLTF/Scripts/Format/glTFBuffer.cs, Assets/VRM/UniGLTF/Scripts/Format/glTFMaterial.cs, Assets/VRM/UniGLTF/Scripts/Format/glTFMesh.cs, Assets/VRM/UniGLTF/Scripts/Format/glTFNode.cs, Assets/VRM/UniVRM/Scripts/Format/VRMFormat.cs, Assets/VRM/UniVRM/Scripts/Format/glTF_VRM_BlendShape.cs, Assets/VRM/UniVRM/Scripts/Format/glTF_VRM_FirstPerson.cs, Assets/VRM/UniVRM/Scripts/Format/glTF_VRM_Humanoid.cs, Assets/VRM/UniVRM/Scripts/Format/glTF_VRM_SecondaryAnimation.cs
In UniVRM v0.45 invalid glTF json values like
`meshes[].primitives[].targets[].TANGENT = -1` had been removed
by UniGLTF.JsonSerializableBase.SerializeMembers(). But it was disabled
unexpectedly since v0.46's following commit:
https://github.com/ousttrue/UniGLTF/commit/a85b9699e76fb88e279330182ae9972062a4f5d6#diff-6d81c3ba04eb19e159e64767f9dd1325L36
Now call UniGLTF.GLTFJsonFormatter.GLTFValue() explicitly to run serializable's
SerializeMembers() for removing those values that restores UniVRM v0.45
behavior without reflections.
Fixes #105
[glTF Validator](https://github.khronos.org/glTF-Validator/)'s result for [Alicia Solid Model 0.40](https://github.com/dwango/UniVRMTest/blob/fbbaf6fe2baf6009aa425fae6afe4f3f7d1f6486/Models/Alicia_vrm-0.40/AliciaSolid_vrm-0.40.vrm)
| Current master …
=> Remove invalid json like `meshes[].primitives[].targets[].TANGENT = -1`

Assets/VRM/UniGLTF/Editor/MaterialTests.cs, Assets/VRM/UniGLTF/Scripts/IO/MaterialExporter.cs
[glTF2.0の仕様によると](https://github.com/KhronosGroup/glTF/tree/3ddfeefd42b47ba615ff57bcba3191f9b7e4cf92/specification/2.0#materialemissivefactor)、 `jsonのmaterials[].emissiveFactor` の最大値は `1` になっていますが、UnityエディタのマテリアルのInspectorからEmissionを有効にしColorのIntensityを増やすと、glbのエクスポート時に当該の値が `1` を超えてエラーになってしまうことがあります。
そのような場合に `1` を超えないようにcolorの値を調整するようにしました。当該の値はglbフォールバック用の値として設定されるもので、VRMのエクステンション側にオリジナルの値が残っているとのことなので、値を勝手に調整してしまっても安全であるという判断です。
`materials[].emissiveFactor` の最大値を増加させる提案はこちらのIssue https://github.com/KhronosGroup/glTF/issues/1083 でkhronosの方に出ていますが、すぐには採用されなそうな雰囲気です。
変更前、変更後でそれぞれで [glbのサンプルファイル](https://github.com/KhronosGroup/glTF-Sample-Models/blob/2262917421f9b7acdf159350a8247afd11f74343/2.0/Box/glTF-Binary/Box.glb) をインポート、マテリアルの Emission Color を `#00BF00` に、Intensityを `1` …
=> Round glTF2.0 materials[].emissiveFactor value to its maximum limit

Assets/VRM/UniJSON/Scripts/Extensions/DateTimeOffsetExtensions.cs, Assets/VRM/UniJSON/Scripts/MsgPack/MsgPackFormatter.cs, Assets/VRM/UniJSON/Scripts/MsgPack/MsgPackValue.cs
.NET 4.6やStandard 2.0で、MsgPackへ32ビットタイムスタンプとして古すぎる値を入れたときに失敗することを確認するテストが落ちていたのを修正しました。
Typoの修正 https://github.com/dwango/UniVRM/pull/117 適用後に確認お願いします。
=>  Throw exception on serialize 32bit time older than unix epoch

Assets/VRM/UniVRM/Scripts/SpringBone/VRMSpringBone.cs, Assets/VRM/UniVRM/Scripts/SpringBone/VRMSpringBoneColliderGroup.cs
VRIKやFinalIKとUniVRMを併用するときに、使用者が意識せずともVRMSpringBoneの処理がIK計算の後に行われるようにしておくと、ハマりが減って良いと思います。
現在のアセットストアで入手可能なVRIKおよびFinalIKは <11000のScriptExecutionOrderになっています。
=> add execution order number (avoid order conflict with vrik)

Assets/VRM/UniVRM/Editor/Tests/UniVRMSerializeTests.cs, Assets/VRM/UniVRM/Scripts/Format/glTF_VRM_FirstPerson.cs, Assets/VRM/UniVRM/Scripts/Format/glTF_VRM_Humanoid.cs, Assets/VRM/UniVRM/Scripts/Format/glTF_VRM_Meta.cs, Assets/VRM/UniVRM/Scripts/Format/glTF_VRM_SecondaryAnimation.cs
Resolve #91 (partially).
Changes are below.
- `vrm.firstperson.firstPersonBone`
- Add `minimum=0`
- Now ignore a field when `-1` is specified when exporting
- `vrm.firstperson.meshannotation.mesh`
- Add `minimum=0`
- `vrm.meta.texture`
- Add `minimum=0`
- Now ignore a field when `-1` is specified when exporting
- `vrm.humanoid.bone.node`
- Add `minimum=0`
- `vrm.secondaryanimation.spring.center`
- DO NOTHING for compatibility
- `vrm.secondaryanimation.spring.bones`
- Add `minimum=0` for elements
- `vrm.secondaryanimation.spring.colliderGroups`
- Add `minimum=0` for elements
- `vrm.secondaryanimation.collidergroup.node`
- Add `minimum=0` for elements
I have checked that VRM files exported with this version can be read with UniVRM 0.46c.
NOTE: `vrm.secondaryanimation.spring.center` cannot …
=> Fix spec for fields which have indices, add minimum=0 for them

Assets/VRM/UniGLTF/Resources/Shaders/NormalMapEncoder.shader, Assets/VRM/UniGLTF/Scripts/IO/TextureConverter.cs
Resolve #73. 
Switch logic for converting textures in the shader instead of in C#.
=> Fix normal maps are broken on Android(and also iOS) platforms

Assets/VRM/UniVRM/Resources/Shaders/VRMShaders.shadervariants
`UniGLTF/UniUnlit` has been added by UniVRM 0.44(ref: [Release note](https://github.com/dwango/UniVRM/wiki/ReleaseNote-v0.44%28en%29)), but not registered to `VRMShaders` shader variants.
This PR fixes this issue.
If any other shaders(like `StandardShader`) should be added to `VRMShaders`, please tell me.
=> Add UniGLTF/UniUnlit to VRMShaders

Assets/VRM/UniJSON/Editor/Tests/GenericCallUtilityTests.cs, Assets/VRM/UniJSON/Editor/Tests/GenericCallUtilityTests.cs.meta, Assets/VRM/UniJSON/Scripts/GenericCallUtility.meta, Assets/VRM/UniJSON/Scripts/GenericCallUtility/GenericExpressionCallFactory.cs, Assets/VRM/UniJSON/Scripts/GenericCallUtility/GenericExpressionCallFactory.cs.meta, Assets/VRM/UniJSON/Scripts/GenericCallUtility/GenericExpressionCallFactory.g.cs, Assets/VRM/UniJSON/Scripts/GenericCallUtility/GenericExpressionCallFactory.g.cs.meta, Assets/VRM/UniJSON/Scripts/GenericCallUtility/GenericInvokeCallFactory.cs, Assets/VRM/UniJSON/Scripts/GenericCallUtility/GenericInvokeCallFactory.cs.meta, Assets/VRM/UniJSON/Scripts/GenericCallUtility/GenericInvokeCallFactory.g.cs, Assets/VRM/UniJSON/Scripts/GenericCallUtility/GenericInvokeCallFactory.g.cs.meta, UniJSON35/UniJSON/UniJSON.csproj
#146 
Utility that create Action from MethodInfo
Invoke version(for AOT)
```cs
var invoke = (Action<Sample, int>)GenericInvokeCallFactory.Create<Sample, int>(mi);
invoke(s, 1);
Assert.AreEqual(1, s.Value);
```
Expression version
```cs
var exp = (Action<Sample, int>)GenericExpressionCallFactory.Create<Sample, int>(mi);
exp(s, 2);
Assert.AreEqual(2, s.Value);
```
=> Added GenericCallUtility

Assets/VRM/UniVRM/Editor/Tests/UniVRMSerializeTests.cs, Assets/VRM/UniVRM/Scripts/Format/glTF_VRM_Meta.cs
(json schema definitions are not affected by this PR now)
Fields below
- `allowedUserName`
- `violentUssageName`
- `sexualUssageName`
- `commercialUssageName`
- `licenseName`
are now required when exporting. Empty or invalid values are not allowed.
=> Now some fields in meta are required

Assets/VRM/README.url, Assets/VRM/README.url.meta
UniVRMはMITライセンスの元配布されているため他のリポジトリなどで再配布される状況があると思うのですが、現状だとインポートされたパッケージ内からREADMEやLICENSを辿る導線が含まれていません。再配布するユーザーに委ねられるべきかもしれませんが、`README.url`という形でリポジトリに飛べる形にしておくと確実だと考えました。
完全な`README.md`を記載するパターン、`LICENSE.txt`も併せて配置するパターンなども考えましたが、それぞれのオリジナルの変更に追従する手間がかかるため、リンクのみを置く形が好ましいと思います。
=> Add README.url

Assets/VRM/UniVRM/Editor/Format/VRMVersionMenu.cs, Assets/VRM/UniVRM/Editor/Tests/VersionTests.cs, Assets/VRM/UniVRM/Scripts/Format/VRMVersion.cs, Assets/VRM/UniVRM/Scripts/Format/VRMVersionPartial.cs
Bump version to `0.51.0` for the next release. And resolve #182.
=> Bump version to 0.51.0. Support Semver

Assets/VRM/UniGLTF/Editor/Tests/UniGLTFTests.cs, Assets/VRM/UniGLTF/Scripts/Format/glTFBuffer.cs, Assets/VRM/UniGLTF/Scripts/Format/glTFMesh.cs, Assets/VRM/UniGLTF/Scripts/IO/ImporterContext.cs, Assets/VRM/UniGLTF/Scripts/IO/MaterialImporter.cs
Add experimental switch ImporterContext.UseUniJSONParser .
=> Use unijson parser

Assets/VRM/UniVRM/Editor/BlendShape/PreviewFaceRenderer.cs
問題
- BlendshapeClip のプレビュー画面が色飛びする
解決
- 光源の強さを `1f` に Normalize
=> Normalize blendshape preview light's intensity.

Assets/VRM/UniUnlit/Editor/UniUnlitEditor.cs
問題
- UniUnlit のインスペクタで CullMode が空白になったり表面が設定できない
解決
- Enum の内部値とリスト表示インデックスのズレを修正
=> Fix UniUnlit inspector's bug, cull mode was empty.

Assets/VRM/UniUnlit/Resources/UniUnlit.shader
問題
- UniUnlit マテリアルが Opaque であるにも関わらず、アルファに 1.0 以外の値が書き込まれている
解決
- Opaque のときはアルファ 1.0 を出力
=> Fix alpha issue when UniUnlit material is opaque.

Assets/VRM/UniVRM/Scripts/Format/VRMImporter.cs
`VVRMImporterContext` -> `VRMImporterContext`
that's it
=> Fix typo in obsolete attribute.

Assets/VRM/UniGLTF/Scripts/IO/MaterialImporter.cs
=> Set _Cutoff parameters when alphaMode is MASK

ProjectSettings/ProjectVersion.txt
A new security advisory for Unity Editor have been announced, [March 2019 Security Update Advisory (CVE-2019-9197)](https://unity3d.com/security?utm_campaign=engine_global_service_190301-gbl-security-rce&utm_content=190301-gbl-security-rce&utm_medium=email&utm_source=Eloqua#CVE-2019-9197). Thus we update a minimum support Unity version to the patched version for security reasons.
=> Update minimum support Unity version to 5.6.7f1

specification/0.0/schema/vrm.schema.json
specVersionの記述がjson schemaに存在しなかったため、記述を追加しました。
=> Add extensions.VRM.specVersion to the json schema

Assets/VRM/UniVRM/Editor/FirstPerson/VRMFirstPersonEditor.cs
=> Save FirstPerson values on GUI correctly

Assets/VRM/UniGLTF/Editor/Tests/TextureTests.cs, Assets/VRM/UniGLTF/Scripts/IO/MaterialExporter.cs, Assets/VRM/UniGLTF/Scripts/IO/MaterialImporter.cs, Assets/VRM/UniGLTF/Scripts/IO/TextureConverter.cs, Assets/VRM/UniGLTF/Scripts/IO/TextureItem.cs
Resolve #212.
Now some conversion logic are introduced when converting MetallicRoughness maps.
- Unity world to glTF world
- Now `smoothness` value is baked into exported textures when exporting
- Thus `roughnessFactor` is hard-coded as `1.0f` in glTF (because this values are already baked into textures)
- glTF world to Unity world
- (vice versa)
- Now `roughnessFactor` value is baked into imported textures when importing
- Thus `smoothness` is hard-coded as `1.0f` in Unity (because this values are already baked into textures)
=> Bake smoothness and roughnessFactor into textures. 

Assets/VRM/UniGLTF/Scripts/IO/MaterialExporter.cs
EMISSIONキーワードがfalseの場合は何も書き込まない
=> If Emission keyword is false, do not output a value

Assets/VRM.Samples/VRM.Samples.asmdef
This fix error followings
```
Assets\VRM.Samples\Scripts\VRMRuntimeLoader.cs(166,13): error CS0012: The type 'Unit' is defined in an assembly that is not referenced. You must add a reference to assembly 'DepthFirstScheduler, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
```
=> added DepthFirstScheduler reference to VRM.Sample

Assets/VRM/UniGLTF/Scripts/IO/TextureLoader.cs
* WWWからUnityWebRequestTextureに変更
=> unityのwww対応

Assets/VRM.Samples/Scripts/VRMRuntimeLoaderNet4.cs, Assets/VRM/UniGLTF/Scripts/IO/ImporterContext.cs, Assets/VRM/UniVRM/Scripts/Format/VRMImporter.cs
* WebGLでは loadasynctask が動作しないため、使用出来ないように修正
* #251
=> exclude loadasynctask with webgl

Assets/VRM/UniGLTF/Scripts/Extensions/UnityExtensions.cs, Assets/VRM/UniGLTF/Scripts/IO/AnimationExporter.cs, Assets/VRM/UniGLTF/Scripts/IO/AnimationImporter.cs, Assets/VRM/UniGLTF/Scripts/IO/gltfExporter.cs, Assets/VRM/UniHumanoid/Scripts/BoneMapping.cs, Assets/VRM/UniHumanoid/Scripts/Format/Bvh.cs, Assets/VRM/UniHumanoid/Scripts/Skeleton.cs, Assets/VRM/UniJSON/Scripts/Json/JsonPointer.cs, Assets/VRM/UniJSON/Scripts/Utf8String/Utf8StringExtensions.cs
ローカル変数のtypoを修正しました。splitは過去形や過去分詞形では `-ed` などの変化はせず、splitのままです。
=> Fix typo (local variables)

Assets/VRM/UniGLTF/Scripts/IO/AnimationImporter.cs, Assets/VRM/UniGLTF/Scripts/IO/ShaderStore.cs, Assets/VRM/UniHumanoid/Scripts/SkeletonMeshUtility.cs, Assets/VRM/UniJSON/Scripts/JsonSchemaValidator/JsonDictionaryValidator.cs, Assets/VRM/UniJSON/Scripts/JsonSchemaValidator/JsonObjectValidator.cs, Assets/VRM/UniVRM/DevOnly/Editor/VRMExportUnityPackage.cs, Assets/VRM/UniVRM/Editor/Meta/VRMMetaEditor.cs, Assets/VRM/UniVRM/Scripts/LookAt/VRMLookAtBlendShapeApplyer.cs
プライベートなもののtypoを修正しました。リフレクションなどを使わない限りリネームは安全と判断して、Obsoleteなどで古いものを残すことはしませんでした。
=> Fix typo (private fields)

Assets/VRM/DepthFirstScheduler/IEnumeratorExtensions.cs, Assets/VRM/UniGLTF/Editor/gltfAssetPostprocessor.cs, Assets/VRM/UniGLTF/Scripts/Extensions/UnityExtensions.cs, Assets/VRM/UniGLTF/Scripts/Format/BytesBuffer.cs, Assets/VRM/UniGLTF/Scripts/IO/IStorage.cs, Assets/VRM/UniGLTF/Scripts/IO/ImporterContext.cs, Assets/VRM/UniGLTF/Scripts/IO/MeshExporter.cs, Assets/VRM/UniGLTF/Scripts/IO/TextureItem.cs, Assets/VRM/UniGLTF/Scripts/IO/UnityPath.cs, Assets/VRM/UniGLTF/Scripts/IO/glbImporter.cs, Assets/VRM/UniGLTF/Scripts/IO/gltfExporter.cs, Assets/VRM/UniHumanoid/PoseModifier/HandPose.cs, Assets/VRM/UniHumanoid/PoseModifier/HandRig.cs, Assets/VRM/UniJSON/Scripts/ListTreeNode/ListTreeNode.cs, Assets/VRM/UniJSON/Scripts/ListTreeNode/ListTreeNodeArrayExtensions.cs, Assets/VRM/UniUnlit/Editor/UniUnlitEditor.cs, Assets/VRM/UniUnlit/Scripts/Utils.cs, Assets/VRM/UniVRM/Editor/Format/VRMImporterMenu.cs, Assets/VRM/UniVRM/Editor/Format/vrmAssetPostprocessor.cs, Assets/VRM/UniVRM/Scripts/BlendShape/BlendShapeClipHandler.cs, Assets/VRM/UniVRM/Scripts/Format/glTF_VRMExtensions.cs
publicメンバーのtypoを修正しました。古い項目はすべてObsoleteをつけて残すようにしたため、リフレクションなどが使われていない限り後方互換性があります。
=> Fix typo (public class members)

Assets/VRM/UniJSON/Scripts/Json/JsonSchema.cs, Assets/VRM/UniJSON/Scripts/JsonSchemaValidator/IJsonSchemaValidator.cs, Assets/VRM/UniJSON/Scripts/JsonSchemaValidator/JsonArrayValidator.cs, Assets/VRM/UniJSON/Scripts/JsonSchemaValidator/JsonBoolValidator.cs, Assets/VRM/UniJSON/Scripts/JsonSchemaValidator/JsonDictionaryValidator.cs, Assets/VRM/UniJSON/Scripts/JsonSchemaValidator/JsonEnumValidator.cs, Assets/VRM/UniJSON/Scripts/JsonSchemaValidator/JsonNumberValidator.cs, Assets/VRM/UniJSON/Scripts/JsonSchemaValidator/JsonObjectValidator.cs, Assets/VRM/UniJSON/Scripts/JsonSchemaValidator/JsonStringValidator.cs
ToJsonSchemaのtypoを修正しました。interfaceのメンバー名を変更したため、古い名前をObsoleteで残すことができないため単純にリネームしました。仕様変更になります。
=> Fix typo (ToJsonSchema)

Assets/VRM/UniGLTF/Scripts/Format/glTFAnimation.cs, Assets/VRM/UniGLTF/Scripts/IO/AnimationCurveData.cs, Assets/VRM/UniGLTF/Scripts/IO/AnimationExporter.cs
AnimationPropertiesのtypoを修正しました。互換性の無い変更として、下記の項目の戻り値型がAnimationPropertiesへ変更されます。
- UniGLTF.glTFAnimationTarget.GetAnimationProperty()
- UniGLTF.AnimationCurveData.AnimationProperty
=> Fix typo (AnimationProperties)

Assets/VRM/DepthFirstScheduler/Schedulable.cs, Assets/VRM/DepthFirstScheduler/TaskChain.cs
Schedulerのtypoを修正しました。interfaceのメンバー名を変更する際、古い名前をObsoleteで残すことができないため単純にリネームしました。仕様変更になります。
=> Fix typo (Scheduler)

Assets/VRM/UniGLTF/Scripts/Format/glTFMaterial.cs, Assets/VRM/UniGLTF/Scripts/IO/TextureIO.cs
TextureTypeのtypoを修正しました。interfaceのメンバー名を変更する際、古い名前をObsoleteで残すことができないため単純にリネームしました。仕様変更になります。
=> Fix typo (TextureType)

Assets/VRM/UniGLTF/Scripts/IO/MeshImporter.cs, Assets/VRM/UniHumanoid/Scripts/Format/Bvh.cs, Assets/VRM/UniJSON/Scripts/Json/JsonFormatter.cs, Assets/VRM/UniJSON/Scripts/JsonSchemaValidator/JsonArrayValidator.cs, Assets/VRM/UniVRM/Scripts/SkinnedMeshUtility/BoneNormalizer.cs
エラーメッセージのtypoを修正しました。仕様変更にはなりますが、エラーメッセージを見て分岐などすることはそう無いだろうと判断し、一気にリネームしてしまっています。
=> Fix typo (error messages)

specification/0.0/schema/vrm.firstperson.meshannotation.schema.json, specification/0.0/schema/vrm.firstperson.schema.json, specification/0.0/schema/vrm.humanoid.bone.schema.json, specification/0.0/schema/vrm.meta.schema.json, specification/0.0/schema/vrm.schema.json, specification/0.0/schema/vrm.secondaryanimation.collidergroup.schema.json, specification/0.0/schema/vrm.secondaryanimation.spring.schema.json
* Schemaに意図しない変更が入ったためUniVRM-0.46の状態に戻す変更
* #284
=> Revert Schema changes

Assets/VRM/UniGLTF/Scripts/IO/TextureLoader.cs
Issue:
https://github.com/vrm-c/UniVRM/issues/291
TextureのMaxSizeを2048固定からTextureサイズに応じてMaxSizeを512~8192の間で設定するように修正
=> fix texture max size when import vrm

Assets/VRM/UniGLTF/Scripts/Extensions/ArrayExtensions.cs, Assets/VRM/UniGLTF/Scripts/Extensions/ArrayExtensions.cs.meta, Assets/VRM/UniGLTF/Scripts/Format/glTF.cs, Assets/VRM/UniGLTF/Scripts/IO/AnimationImporter.cs, Assets/VRM/UniGLTF/Scripts/IO/BytesReader.cs, Assets/VRM/UniGLTF/Scripts/IO/ImporterContext.cs, Assets/VRM/UniGLTF/Scripts/IO/NodeImporter.cs
#300 
* For empty name node, fix to name nodeIndex
* Fix MarshalCopyTo typo
* Removed GetArrayFromAccessorAsFloat and replaced it with the process of creating a float array
=> fix gltf animation import

Assets/VRM/UniGLTF/Scripts/IO/ImporterContext.cs, Assets/VRM/UniVRM/Scripts/Format/VRMImporterContext.cs
Prefab SubAsset had an error in AssetPipeline v2, so the following measures were taken
* SubAsset is deprecated
* Use SaveAsPrefabAssetAndConnect
* What was SubAsset is expanded to each directory
issue
#292 #294 #321
=> Unity2019 asset pipeline v2 support

Assets/VRM/UniGLTF/Scripts/IO/MaterialExporter.cs, Assets/VRM/UniGLTF/Scripts/IO/MaterialImporter.cs
Convert baseColorFactor to linearColor when exporting
Convert baseColorFactor to gammaColor when importing
#301
=> fix baseColorFactor color space.

Assets/VRM/UniVRM/Editor/Tests/VRMBlendShapeKeyTest.cs, Assets/VRM/UniVRM/Scripts/BlendShape/BlendShapeKey.cs
BlendShapeKeyクラスで頻繁に発生していたGCを低減
`string.ToUpper()` , `Enum.ToString() `  を呼び出す頻度が少なくなるように修正
この変更により一部挙動が以下のように変わります。
- BlendShapeKeyのNameが`Blink` のような定義済みPresetと同名であれば、Preset=BlendShapePreset.BlinkのBlendShapeKeyと同一と見なせていたものが別扱いになる
- NameがToUpper()によって大文字と小文字の区別がされていなかったものが区別されるようになる
=> suppress blendshape gabage collection

Assets/VRM/UniGLTF/Scripts/IO/MeshExporter.cs, Assets/VRM/UniGLTF/Scripts/IO/MeshImporter.cs, Assets/VRM/UniGLTF/Scripts/IO/gltfExporter.cs, Assets/VRM/UniVRM/Scripts/Format/VRMExportSettings.cs, Assets/VRM/UniVRM/Scripts/Format/VRMExporter.cs
https://github.com/vrm-c/UniVRM/issues/295 
~VRMExportする際にBlendShapeの法線・接線データを削るオプションを追加しました。
接線データはもともと含まれていなかったので、チェックを入れた場合、法線データが含まれないようになります。~
古いverのUniVRMのImporterとの互換性がなくなるため、法線削除は一時的に塞ぎました。
使っていないBlendShapeの削除のみ行うようにしています。
=> add VRM Export Option. Reduce BlendShape Size

Assets/VRM/UniGLTF/Scripts/Format/glTF.cs
glTFインポート時に自動命名されるテクスチャー名のtypoを修正しました。仕様変更になります。いちおう修正PRとして出しましたが、テクスチャー名を使って何か処理をしているプログラムが想定される場合はそのままのほうが安全かもしれません。
=> Fix typo (Base64Embedded)

Assets/VRM.Samples/Editor/Tests/VRMImportExportTests.cs, Assets/VRM/UniGLTF/Editor/Tests/UniGLTFTests.cs, Assets/VRM/UniGLTF/Scripts/Format/SerializerTypes.cs, Assets/VRM/UniGLTF/Scripts/Format/SerializerTypes.cs.meta, Assets/VRM/UniGLTF/Scripts/Format/glTF.cs, Assets/VRM/UniGLTF/Scripts/IO/ImporterContext.cs, Assets/VRM/UniVRM/Scripts/Format/VRMExportSettings.cs
#297 
* basic serializer is Obsolete.
* UniJson(Refrection serializer ) is default.
* Generated serializer is Experimental.
=> add generated serializer, fix tests

Assets/VRM/UniVRM/Scripts/Format/VRMExportSettings.cs
In case of prefab, copy is performed, so no revert processing is required.
#348
=> fix fbx prefab export error

Assets/VRM/UniVRM/Scripts/Format/VRMExportSettings.cs
solve 
https://github.com/vrm-c/UniVRM/issues/376
UnityEditor上からのvrm Export時に同名boneを含めたまま出力できてしまうと、ランタイムインポートも動かない場合が多いのでチェックを追加しました。
vrm-specificationで定義されている1.0のglTF Schemaにもnameはユニークを要求しているので規格にも合致する実装だと考えています。
https://github.com/vrm-c/vrm-specification/tree/master/specification/VRMC_vrm-1.0_draft#naming-restrictions
=> Check bone names duplicate when export vrm file.

Assets/VRM/UniGLTF/Scripts/Format/ExtensionsAndExtras/glTFMesh.extras.targetNames.cs, Assets/VRM/UniGLTF/Scripts/Format/ExtensionsAndExtras/glTFMesh.extras.targetNames.cs.meta, Assets/VRM/UniGLTF/Scripts/Format/glTFMesh.cs, Assets/VRM/UniGLTF/Scripts/IO/MeshImporter.cs
Blenderから`*.gltf`や`*.glb`を書き出した際にモーフ名付きのメッシュが読み込まれない問題の修正を行いました。
BlenderとUniGLTFではモーフ名の格納場所が異なっており、現在の実装ではそのようなメッシュを読み込むことができません。
具体的な格納場所は以下の通りです。
>**Khronos glTF Blender I/O v1.1.45**
>`json.meshes[i].extras.targetNames[j]`
>
>**UniGLTF-1.21**
>`json.meshes[i].primitives[j].extras.targetNames[k]`
`targetNames`の格納場所はglTF 2.0で正式に定められてはおりませんが、[glTF 2.0のSpecification](https://github.com/KhronosGroup/glTF/tree/596605d8c0444cf50250b2b46bb93bb1f72a0cd4/specification/2.0#morph-targets)には以下のように記載されています。
> **Implementation note:** A significant number of authoring and client implementations associate names with morph targets. While the glTF 2.0 specification currently does not provide a way to specify names, most tools use an array of strings, `mesh.extras.targetNames`, for this purpose. The …
=> Support mesh sharing morph target

Assets/VRM/UniHumanoid/Scripts/Format/Bvh.cs
#382
https://docs.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo.invariantculture?view=netframework-4.8
ロケールを無視して英語で処理するぽい。小数点が、ピリオドでないロケール(フランス語など)に対する修正。
=> Bvhのfloat.parseのロケール問題を修正

Assets/VRM/UniVRM/Scripts/SkinnedMeshUtility/BoneMeshEraser.cs
頂点数が多いモデルを読み込んだ時に、`BoneMeshEraser.ExcludeTriangles`内で大量のヒープアロケートが発生していたので対処しました。
対策前
対策後
=> Fix: Large heap allocation in BoneMeshEraser.ExcludeTriangles

Assets/VRM/UniVRM/Scripts/BlendShape/BlendShapeKey.cs
#330 で行われた破壊的変更により独自に設定したキーがモデルからキーの一覧を取得した際に大文字で返ってくるため、小文字で設定したキーの適用が不可能になっていた問題を修正しました。
また、この時の変更によりデフォルトのJOYやFUN等のキーが文字列での指定をすることが不可能になってしまったため、アプリ開発者側で変更が必要になっています。
以前`new BlendShapeKey("JOY")`はBlendShapePreset.Joyを指していましたが、
BlendShapePreset.Unknownの名前がJOYのキーを指すようになってしまっています。
(標準のキーはEnumでの指定しか出来ないようにした仕様変更と理解していますが、意図したものかの確認をお願いします。)
テストコード
```csharp
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;
using VRM;
public class UniVRMTest : MonoBehaviour
{
[SerializeField]
private VRMBlendShapeProxy proxy;
private List<string> keyList;
// Start is called before the first frame update
void Start()
{
keyList = proxy.BlendShapeAvatar.Clips.Select(d => BlendShapeKey.CreateFrom(d).Name).ToList();
foreach (var key in keyList)
{ …
```
=> Fix blendshape uppercase bug.

Assets/VRM/UniVRM/Editor/Format/VRMExporterMenu.cs, Assets/VRM/UniVRM/Scripts/Format/VRMExportSettings.cs, Assets/VRM/UniVRM/Scripts/Format/glTF_VRMExtensions.cs
#398
修正しました。
* BlendShapeClip の BlendShapeBinding が参照する mesh が active でないときにこれをエクスポートしない
* VRM のエクスポート前のエラーチェックで active な mesh が 0 であるこを検知する。 `No active mesh`
* ExportWizard のヴァリデーションを EditorApplication.hierarchyWindowChanged でも実行する。GameObject のアクティブ切り替えで Export 可否が即座に反映します。
=> Fix export nonactive mesh

Assets/VRM/UniGLTF/Editor/Tests/UniGLTFTests.cs, Assets/VRM/UniGLTF/Scripts/Format/glTFMaterial.cs
fix glTFPbrMetallicRoughness init.
#371
=> fix glTFPbrMetallicRoughness init.

Assets/VRM/UniGLTF/Editor/Tests/MaterialTests.cs, Assets/VRM/UniGLTF/Scripts/Format/ExtensionsAndExtras/KHR_texture_transform.cs, Assets/VRM/UniGLTF/Scripts/Format/ExtensionsAndExtras/KHR_texture_transform.cs.meta, Assets/VRM/UniGLTF/Scripts/Format/glTFMaterial.cs, Assets/VRM/UniGLTF/Scripts/IO/MaterialExporter.cs, Assets/VRM/UniGLTF/Scripts/IO/MaterialImporter.cs, Assets/VRM/UniGLTF/Scripts/IO/gltfExporter.cs
* textureInfoの拡張であるKHR_texture_transformの対応
* https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Khronos/KHR_texture_transform
* #216 
* UnityのStanderd、UniUnlitShaderで指定したTiling,Scaleの値がエクスポート可能になる
=> WIP: Add texture transform extensions

Assets/VRM/UniVRM/Scripts/FirstPerson/VRMFirstPerson.cs
以下の修正をしました。
* 削除対象が無い場合に処理をMesh作成をスキップする
* 全部削除対象の場合にMeshを破棄して、Renderer作成をスキップする
* OnDestroy で作成した Meshを破棄する
#138
=> VrmFirstPersonを修正

Assets/VRM/UniHumanoid/Scripts/AvatarDescription.cs, Assets/VRM/UniVRM/Scripts/FirstPerson/VRMFirstPerson.cs, Assets/VRM/UniVRM/Scripts/Format/glTF_VRM_Humanoid.cs, Assets/VRM/UniVRM/Scripts/SpringBone/VRMSpringUtility.cs
- LINQ構文使用によってVRMロード時に発生していたGCを抑制
=> Suppress gabage collection due to using linq

Assets/VRM/UniGLTF/Editor/Tests/MaterialTests.cs, Assets/VRM/UniGLTF/Scripts/IO/ImporterContext.cs, Assets/VRM/UniGLTF/Scripts/IO/MaterialImporter.cs, Assets/VRM/UniVRM/Scripts/Format/VRMMaterialImporter.cs
ImporterContextをMaterialImporterに持ち運ばなくても動くように変更。
それに伴ってテストを修正。
=> fix MaterialImporter and TextureTransformTest

Assets/VRM/UniVRM/Editor/BlendShape/BlendShapeClipEditor.cs, Assets/VRM/UniVRM/Editor/BlendShape/BlendShapeClipSelector.cs, Assets/VRM/UniVRM/Editor/BlendShape/VRMBlendShapeProxyEditor.cs, Assets/VRM/UniVRM/Editor/Tests/VRMBlendShapeKeyTest.cs, Assets/VRM/UniVRM/Scripts/BlendShape/BlendShapeAvatar.cs, Assets/VRM/UniVRM/Scripts/BlendShape/BlendShapeClip.cs, Assets/VRM/UniVRM/Scripts/BlendShape/BlendShapeKey.cs, Assets/VRM/UniVRM/Scripts/BlendShape/BlendShapeMerger.cs, Assets/VRM/UniVRM/Scripts/BlendShape/VRMBlendShapeProxy.cs
=> Update BlendShapeKey interface

Assets/VRM/UniGLTF/Scripts/IO/MeshExporter.cs, Assets/VRM/UniGLTF/Scripts/IO/gltfExporter.cs, Assets/VRM/UniVRM/Editor/Format/VRMEditorExporter.cs, Assets/VRM/UniVRM/Editor/Format/VRMExportSettings.cs, Assets/VRM/UniVRM/Scripts/Format/VRMExporter.cs, Assets/VRM/UniVRM/Scripts/Format/VRMExporterConfiguation.cs
=> Add an option to remove vertex color in export menu

Assets/VRM/UniVRM/Editor/LookAt/VRMLookAtHeadEditor.cs
A baked mesh is a copied structure and is created forever
=> Fix: memory leak in editor preview

Assets/VRM/UniHumanoid/Editor/BoneMappingEditor.cs, Assets/VRM/UniVRM/Editor/Format/VRMEditorExporter.cs
BlendShapeProxyの無いモデルのエクスポート時(Vrmになる前の初回エクスポート)にエラーなっていた。
=> Fix nullcheck

Assets/VRM/UniGLTF/Scripts/IO/TextureExportManager.cs, Assets/VRM/UniGLTF/Scripts/IO/TextureIO.cs
#245
https://docs.unity3d.com/ScriptReference/AssetDatabase.GetAssetPath.html
path が得られた場合は、コピーせずにそのバイナリ(png or jpg)をそのまま使う。
=> EditorExport時にアセットが見つかったTextureは、それを使う

Assets/VRM/UniVRM/Scripts/SpringBone/VRMSpringBone.cs
SpringBoneの更新がLateUpdateのためにアニメーションや物理挙動をVRMモデルに加えた時にSpringBoneのコライダが暴れてしまうので、LateUpdateをFixedUpdateに直したところ暴れる事はなくなりました。
LateUpdateをFixedUpdateに変える事によって起こる副作用がこちらでは解らないので、問題がある場合は取り下げていただければと思います。
=> Fix: SpringBone LateUpdate to FixedUpdate

Assets/VRM/UniVRM/DevOnly/Editor/VRMExportUnityPackage.cs
* add VRMShaders
* remove UniJSON-standalone, UniHumanoid-standalone, UniGLTF-standalone
=> update export UnityPackage menu

Assets/VRM/UniGLTF/Scripts/Extensions/StringExtensions.cs, Assets/VRM/UniVRM/Editor/Format/VRMExportSettings.cs, Assets/VRM/UniVRM/Editor/Tests/InvalidFileNameTest.cs, Assets/VRM/UniVRM/Editor/Tests/InvalidFileNameTest.cs.meta, Assets/VRM/UniVRM/Editor/Tests/UniVRM.Editor.Tests.asmdef
#152 #153 
ファイル名前が長すぎるの場合はエクスポートを禁止。
エスケープ文字を追加：制御文字。
参考：https://github.com/vrm-c/vrm-specification/issues/40
=> check invalid file name

Assets/VRM.Samples/Scripts/ViewerUI.cs, Assets/VRM/UniVRM/Scripts/LookAt/VRMLookAtBlendShapeApplyer.cs
初期値
`VRMLookAtBlendShapeApplyer.m_notSetValueApply = true`
に変更。
これに伴って、
`BlendShapeProxy.Apply`
の呼び出しを追加した。
=> Fix vrm look at blend shape applyer

Assets/VRM/UniVRM/Editor/Tests/NormalizeTests.cs, Assets/VRM/UniVRM/Editor/Tests/NormalizeTests.cs.meta, Assets/VRM/UniVRM/Scripts/SkinnedMeshUtility/BoneNormalizer.cs
SkinnedMeshRenderer.bones 配列に null が含まれていても大丈夫なようにした。
該当するボーンをシーン上で削除した場合に起こるかもしれない。
#467
=> fix normalize if bones contains null

Assets/VRM/UniVRM/Editor/Format/VRMEditorExporter.cs, Assets/VRM/UniVRM/Editor/Format/VRMExportSettings.cs
#475
* ボーンは自動的にリネームする
* Rootは特に何もしない。エクスポート時に値が無くなってしまう警告
=> ボーン名重複と、RootのTRSを警告に下げてエクスポートできるようにした

Assets/VRM/UniGLTF/Editor/Serialization/SerializerGenerator.cs, Assets/VRM/UniGLTF/Scripts/IO/FormatterExtensionsGltf.g.cs
Experimental Exporterで空配列の除外設定に漏れがあったため、glTF違反のデータを出力してしまうことがあるの修正しました。また、Experimental Exporterが古くなっていたので再生成しました。
[こちらのVRM](https://github.com/saturday06/VRM_IMPORTER_for_Blender2_8/blob/0_93_1/test/vrm/in/triangle.vrm) をUniVRM masterブランチ c9b383b72cbe71a36d8b7d7bda14ce0c6be2b454 でインポートし「Use Experimental Exporter」をON、「Use Sparse Accessor」をOFFの状態でエクスポートした結果の拡張子をglbとし、 https://github.khronos.org/glTF-Validator/ にかけた結果を次に示します。
| 修正前 | 修正後 |
| --- | --- |
| <img src="https://user-images.githubusercontent.com/532872/88477375-6410be00-cf7a-11ea-8b58-3ea53fb2904b.png" width="300"> | <img src="https://user-images.githubusercontent.com/532872/88477376-68d57200-cf7a-11ea-99b2-7ac9b7ee4736.png" width="300"> |
=> Experimental Exporterでjsonに空の配列が含まれglTF違反になってしまうことがあるのを修正

Assets/MeshUtility/MeshUtility.asmdef, Assets/VRM/UniVRM/DevOnly/Editor/VRMExportUnityPackage.cs
=> Fix unitypackage

Assets/VRM/UniGLTF/Scripts/IO/MeshExporter.cs, Assets/VRM/UniGLTF/Scripts/IO/gltfExporter.cs, Assets/VRM/UniVRM/Scripts/Format/VRMExporter.cs, Assets/VRM/UniVRM/Scripts/Format/glTF_VRMExtensions.cs
v0.56.3のデフォルトのエクスポート設定でglTF違反のデータを出力してしまうことがあるの修正しました。
[こちらのVRM](https://github.com/pixiv/three-vrm/blob/09e1ede108c5ff1993ad5c53bee7fdc41810be09/examples/models/three-vrm-girl.vrm) をUniVRM v0.56.3でインポートし、デフォルトの設定をいじらずエクスポートした結果の拡張子をglbとし、 https://github.khronos.org/glTF-Validator/ にかけた結果を次に示します。
| 修正前 | 修正後 |
| --- | --- |
| <img src="https://user-images.githubusercontent.com/532872/88481109-86afd080-cf94-11ea-88ee-e9fc6936554f.png" width="300"> |  <img src="https://user-images.githubusercontent.com/532872/88480919-bf9b7580-cf93-11ea-9089-d6c54a8c6242.png" width="300"> |
変換前のVRMのエラーは0件です。残りの276件のエラーは、おそらくsparse accessorがデフォルトになった影響かと思いますが、今回は未調査です。
=> 空のモーフターゲットが出力されglTF違反になってしまうことがあるのを修正

Assets/VRM/UniGLTF/Scripts/IO/gltfExporter.cs
空のマテリアルのindexずれ対策が、テスト `SameMeshButDifferentMaterialExport` にささった
=> UnitTestが通らなくなったのを修正

Assets/VRM/UniGLTF/Scripts/IO/MaterialExporter.cs, Assets/VRM/UniVRM/Editor/Format/VRMExportSettings.cs, Assets/VRM/UniVRM/Scripts/Format/VRMMaterialExporter.cs
エクスポートダイアログで、`unlit` としてエクスポートできるにも関わらず警告メッセージ
`unknown material` 
が表示されてしまうのを修正。
* VRM/UnlitTexture
* VRM/UnlitTransparent
* VRM/UnlitCutout
を対象。
* VRM/UnlitTransparentZWrite
は削除予定なので見送り。
#496 に関連。
=> Fix unknown material

Assets/VRM/UniVRM/Editor/Tests/VRMBlendShapeKeyTest.cs, Assets/VRM/UniVRM/Scripts/BlendShape/BlendShapeKey.cs
リファクタ
- ID の判定重複部分を削除して readonly struct に
- CreateFromPreset 時の Enum.ToString() を削除
仕様変更
- BlendShapeClip から生成された BlendShapePreset.Unknown 以外のプリセットの Name は、各プリセット名を ToString() したものになるように
- BlendShapeKey.ToString() が旧仕様の ToUpper() された値を返していたため、 ToUpper() を削除
=> Refactor BlendShapeKey && BlendShapePreset.Unknown 以外のプリセットは独自の Name を持てない仕様に変更

Assets/VRM/UniVRM/Editor/Format/VRMExporterWizard.cs, Assets/VRM/UniVRM/Editor/SpringBone/VRMSpringBoneValidator.cs, Assets/VRM/UniVRM/Editor/SpringBone/VRMSpringBoneValidator.cs.meta
* hair_02_02 ( hair_02_01 の子供 ) が刺さっている
* hair1_L が２回刺さっている
=> * implement SpringBone validation #474

Assets/VRM/UniVRM/Editor/Format/VRMEditorExporter.cs, Assets/VRM/UniVRM/Editor/Format/VRMExporterWizard.cs
#528
エクスポートダイアログで、fbxを直接指定してエクスポートすると、
`target.AddComponent<VRMMeta>()`
が失敗して、エラーになる。(fbxのprefabは変更不可のため)
別の方法を使うようにした。
=> 初回Export時のmeta受け渡し方法を修正

Assets/VRM/UniVRM/Editor/Format/VRMExporterWizard.cs, Assets/VRM/UniVRM/Editor/SpringBone/VRMSpringBoneValidator.cs, Assets/VRM/UniVRM/Scripts/FirstPerson/VRMFirstPerson.cs
* repaint の呼び出しトリガーの修正
* FirstPerson と SpringBone の null 参照メッセージの改善
=> エクスポートダイアログの修正

Assets/VRM/UniVRM/Editor/ExporterExtensions.cs, Assets/VRM/UniVRM/Editor/ExporterExtensions.cs.meta, Assets/VRM/UniVRM/Editor/FirstPerson/VRMFirstPersonValidator.cs, Assets/VRM/UniVRM/Editor/FirstPerson/VRMFirstPersonValidator.cs.meta, Assets/VRM/UniVRM/Editor/Format/VRMExporterWizard.cs, Assets/VRM/UniVRM/Editor/SpringBone/VRMSpringBoneValidator.cs, Assets/VRM/UniVRM/Scripts/FirstPerson/VRMFirstPerson.cs
SprngBone/FirstPerson のついた prefab をシーンに出さずに ExportRoot にセットすると、activeInHierarchy  で `not active` 判定になってしまう。
fbx の prefab には `SprngBone/FirstPerson` がアタッチされていることは無いので、起こらない。
=> activeInHierarchy が prefab にヒットする件

Assets/MeshUtility/Editor/HumanoidEditor.cs, Assets/MeshUtility/Editor/HumanoidEditor.cs.meta, Assets/MeshUtility/Runtime/Humanoid.cs, Assets/MeshUtility/Runtime/Humanoid.cs.meta, Assets/MeshUtility/Runtime/HumanoidLoader.cs, Assets/MeshUtility/Runtime/HumanoidLoader.cs.meta, Assets/MeshUtility/Runtime/UnityPath.cs, Assets/MeshUtility/Runtime/UnityPath.cs.meta
=> 1.0 からバックポート。こっちで管理する。

Assets/VRM/UniVRM/Editor/ExporterExtensions.cs, Assets/VRM/UniVRM/Scripts/FirstPerson/VRMFirstPerson.cs
- https://github.com/vrm-c/UniVRM/commit/22eb7749f9827b1f59184c7b606c533b64198103 にて、親の取得方法が `Ancestor()` から `GetComponentsInParents<Transform>()` に変更されたが、その結果非アクティブな場合に取得できなくなっていた
- 非アクティブな場合にHeadlessModelが作成されなくなっていた
- EnableForExportが常にtrueを返すようになってしまっていた
- `GetComponentsInParents<Transform>(true)` にする方法も考えられるが、元に戻すのが安全だと判断しました
=> 親をたどる時、非アクティブなTransformが取得できなくなっていたのを修正

Assets/VRM/UniVRM/Editor/Format/VRMExporterWizard.cs
`VRMExporterWizardMessages.ROOT_WITHOUT_ROTATION_AND_SCALING_CHANGED` 時のエクスポート禁止を削除。
`VRMExporterWizardMessages.ROTATION_OR_SCALEING_INCLUDED_IN_NODE` 警告が出るのでよし。
=> 正規化するときは、 `ExportRootに回転・拡大縮小` があってもよい。

Assets/VRM/UniVRM/Editor/FirstPerson/VRMFirstPersonValidator.cs, Assets/VRM/UniVRM/Editor/Format/VRMExporterVaildator.cs, Assets/VRM/UniVRM/Editor/Format/VRMExporterVaildator.cs.meta, Assets/VRM/UniVRM/Editor/Format/VRMExporterWizard.cs, Assets/VRM/UniVRM/Editor/Tests/InvalidFileNameTest.cs
* 描画内容の更新イベントを調整
* スクロール領域調整
* エクスポートする Meshの 参考サイズ表示
#534
=> Export Dialog の更新

Assets/VRM/UniVRM/Editor/BlendShape/VRMBlendShapeProxyValidator.cs, Assets/VRM/UniVRM/Editor/BlendShape/VRMBlendShapeProxyValidator.cs.meta, Assets/VRM/UniVRM/Editor/FirstPerson/RendererFirstPersonFlagsDrawer.cs, Assets/VRM/UniVRM/Editor/FirstPerson/VRMFirstPersonEditor.cs, Assets/VRM/UniVRM/Editor/FirstPerson/VRMFirstPersonValidator.cs, Assets/VRM/UniVRM/Editor/Format/VRMExporterVaildator.cs, Assets/VRM/UniVRM/Editor/Format/VRMExporterWizard.cs, Assets/VRM/UniVRM/Scripts/Format/glTF_VRMExtensions.cs
* Validation for BlendShapeClip.Values
* target renderer not found => find same name renderer in hierarchy , and use first
* Validation for BlendShapeClip.MaterialValues
#551 #555
* VrmFirstPerson の Inspector に Validation 表示。reset button
#554
If you ignore the warning, the export is possible and no error occurs, but the corresponding BlendShape is skipped.
=> add BlendShapeClip Validation

Assets/VRM/UniGLTF/Scripts/IO/TextureItem.cs, Assets/VRM/UniGLTF/Scripts/IO/TextureLoader.cs
`ITextureLoader` はテクスチャを実際に Unity Object に変換する処理を担当する。
ここで、テクスチャサンプラはテクスチャの属性のひとつなので `ITextureLoader` で処理するのが望ましい。
しかし現状は `ITextureLoader` の外で処理されているため `ITextureLoader` でテクスチャサンプラに独自の処理を
入れることができない。
したがって `ITextureLoader` のインタフェースを変更し、これを達成する。
=> テクスチャサンプラ適用処理を ITextureLoader が持つ

Assets/VRM/UniGLTF/Editor/Serialization/SerializerGenerator.cs, Assets/VRM/UniGLTF/Editor/Tests/UniGLTFTests.cs, Assets/VRM/UniGLTF/Scripts/Format/SerializerTypes.cs, Assets/VRM/UniGLTF/Scripts/Format/glTF.cs, Assets/VRM/UniGLTF/Scripts/IO/FormatterExtensionsGltf.g.cs, Assets/VRM/UniGLTF/Scripts/IO/GltfDeserializer.g.cs, Assets/VRM/UniGLTF/Scripts/IO/ImporterContext.cs, Assets/VRM/UniVRM/Editor/Format/VRMEditorExporter.cs, Assets/VRM/UniVRM/Editor/Format/VRMExportSettings.cs, Assets/VRM/UniVRM/Editor/Format/VRMExportSettingsEditor.cs
#553
#490
https://github.com/KhronosGroup/glTF-Validator/blob/1be41dd1acdfe21ee9e577577bc2183e6861345a/ISSUES.md
* `BUFFER_VIEW_TARGET_OVERRIDE`
* `ACCESSOR_MAX_MISMATCH`
は、validator の方に 修正が要ると思う。
https://github.com/KhronosGroup/glTF-Sample-Models
に該当するサンプルを送って修正依頼を試みる。
(違うタイプの sparse しかサンプルが無い )
* Microsoft 3D Viewer
* Three.js
* babylon.js
での動作を確認した。
=> 生成シリアライザをデフォルトにする

Assets/VRM/UniVRM/Editor/SkinnedMeshUtility/SkinnedMeshUtility.cs
=> fix warnings

Assets/VRM/UniVRM/Scripts/SpringBone/VRMSpringBone.cs
warning CS0649: Field 'XXX' is never assigned to, and will always have its default value false
=> fix warning CS0649

Assets/VRM/UniGLTF/Scripts/IO/MeshExporter.cs, Assets/VRM/UniVRM/Editor/Format/VRMExportMeshes.cs, Assets/VRM/UniVRM/Editor/Format/VRMExporterVaildator.cs, Assets/VRM/UniVRM/Editor/Format/VRMExporterWizard.cs, Assets/VRM/UniVRM/Editor/Format/VRMExporterWizardMessages.cs
Unity は BoneWeight の無い BlendShape を SkinnedMeshRenderer で扱う。 GLTF が理解できるように正規化で BoneWeight を付与する
=> BoneWeightの無いBlendShapeは正規化必用

Assets/VRM/UniVRM/Scripts/SpringBone/VRMSpringBone.cs, Assets/VRM/UniVRM/Scripts/SpringBone/VRMSpringBoneColliderGroup.cs
#576 
Coordinate conversion is done twice.
```cs
transform.TransformPoint(collider.Offset)
```
=> [SpringBone] collider position bug.

Assets/VRM/UniGLTF/Scripts/IO/AnimationImporter.cs
* EditorImpor時に支障が出るため、AnimationClip生成時にGameObjectが存在することを前提としないように変更
=> fix_animationImporter_blendShape

Assets/VRM/UniGLTF/Scripts/Format/glTF.cs, Assets/VRM/UniGLTF/Scripts/IO/MeshExporter.cs, Assets/VRM/UniGLTF/Scripts/IO/gltfExporter.cs
#564
のサンプルデータ作成のため
* gltf エクスポートの追加
* mesh.extras.targetNames の有効化
* validator にヒットする原因だった、不要な bufferView.target = ARRAY_BUFFER (morphTargetのsparseでは不正)の除去
=> Add gltf export and fix morphTarget sparse

Assets/VRM/UniGLTF/Scripts/IO/ImporterContext.cs
UniVRM 0.59 から入っているメッシュの同名修正：ImporterContext.FixUnique(), MakeUniqueName() ですが、割と古い VRMモデルや GLBなどの背景モデルでは同名メッシュが 100個を超えることもあるので、エラーが出て、ロードができないことがあるようです。
(※髪の毛やスカート、装飾など、メッシュが結合されてないモデルもある)
(例) vrm
https://3d.nicovideo.jp/works/td41774
(UniVRM 0.59 以降で同名が大量にあるときのロード)
　
なので試しに、ImporterContext.MakeUniqueName() 内のループ回数の代わりに GUID にしてみたら、上手くロードできるようになりました。
(GUIDにした修正版)
ただ、GUID にする場合、MakeUniqueName() でループを回す必要性は無くなるので、FixUnique() の中にまとめてみました。
実質、MakeUniqueName() が不要になってしまいましたが、念のため、削除などのご判断はお任せします(笑)。
　
バグレポでも良かったんですが、コードの方がわかりやすい気がしたので、修正の参考にでもして下さい。
=> 同名メッシュが100以上あるときにも対応

Assets/VRM/UniVRM/Editor/Meta/VRMMetaObjectEditor.cs
=> スクリーンショットを作成するボタン

Assets/VRM/Editor/Meta/VRMMetaObjectEditor.cs
=> スクリーンショット作成時に、JpegEncodeしているのに拡張子がpng

Assets/UniGLTF/Runtime/UniGLTF/IO/MeshImporter.cs
=> primitives attributes が有ったり無かったりする場合に対応(例えばNORMAL)

Assets/UniGLTF/Runtime/UniGLTF/IO/MeshExporter.cs
=> skip empty submesh

Assets/VRM/Runtime/FirstPerson/VRMFirstPerson.cs
=> add VRMFirstPerson.SetVisiblity

Assets/UniGLTF/Runtime/UniGLTF/IO/ITextureExporter.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/ITextureExporter.cs.meta, Assets/UniGLTF/Runtime/UniGLTF/IO/TextureIO.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/gltfExporter.cs, Assets/VRM/Runtime/IO/VRMExporter.cs
* 拡張側でテクスチャ出力を置き換え可能にする目的
* ITextureExporterを追加
* 既存のTextureIO でITextureExporterを実装する形に変更
=> add ITextureExporter

Assets/UniGLTF/MeshUtility/Runtime/Validation.cs, Assets/VRM/Editor/FirstPerson/VRMFirstPersonEditor.cs, Assets/VRM/Editor/FirstPerson/VRMFirstPersonValidator.cs, Assets/VRM/Runtime/FirstPerson/VRMFirstPerson.cs
=> add Validation.Extended

Assets/VRM10/Runtime/Migration/Migration.cs, Assets/VRM10/Runtime/UnityBuilder/MeshLoader.cs
Fix migration erros.
- Complete `VRMC_vrm.meta.avatarPermission` variant.
- Complete `VRMC_vrm.meta.allowExcessivelyViolentUsage` variant.
- Complete `VRMC_vrm.meta.allowExcessivelySexualUsage` variant.
- Complete `VRMC_vrm.meta.commercialUsage` variant.
- Invalid mesh load function in Unity 2019.
=> Fix VRM 0.x to VRM1.x migration errors.

Assets/UniGLTF/package.json, Assets/VRM/package.json, Assets/VRM10/package.json
Reason:
Latest UniGLTF has changes, but package version is not changed.
So, not updated package on UPM registory. (e.g. openupm.com)
=> Bump UniGLTF package version

Assets/UniGLTF/Runtime/UniGLTF/UniGLTFVersion.cs, Assets/UniGLTF/package.json, Assets/VRM/Runtime/Format/VRMVersion.cs, Assets/VRM/package.json, Assets/VRMShaders/package.json
#711
UniGLTFのバージョン番号は、 UniVRMのバージョン番号から機械的に決めることにします。
更新の有無でそれぞれバージョンアップの有無を管理すると煩雑になるためです。
major: 2
minor: UniVRM.minor - 64
patch: UniVRM.patch
UniGLTF のバージョンを UniVRMのバージョンに揃えたいのですが、
先に `1.27` というバージョンを持っていて巻き戻るので、とりあえず `2.0` に上げていてやむを得ない状態に。
=> UniVRM-0.65.3 (UniGLTF-2.1.3)

Assets/UniGLTF/MeshUtility/Editor/BoneMeshEraserWizard.cs, Assets/UniGLTF/MeshUtility/Editor/MeshProcessDialog.cs, Assets/UniGLTF/MeshUtility/Editor/MeshUtility.cs
moved BoneMeshEraser to MeshUtility editor, along with mesh separator, mesh integrator and static mesh integrator
#577
=> moved BoneMeshEraser to MeshUtility editor

Assets/VRM10/Runtime/IO/VrmExpressionAdapter.cs, Assets/VRM10/Tests/SerializationTests.cs
Fix ExpressionPreset conversion problem in migration, and add UnitTests.
but the UnitTest is still failed.
Please fix this.
https://github.com/Santarh/UniVRM/blob/d9a8278df907189f93968b125d161bce0982191c/Assets/VRM10/Runtime/IO/VrmExpressionAdapter.cs#L211
=> Fix ExpressionPreset conversion problem in migration.

Assets/VRM10/Runtime/IO/VrmExpressionAdapter.cs, Assets/VRM10/vrmlib/Runtime/EnumUtil.cs, Assets/VRM10/vrmlib/Runtime/Vrm/ExpressionPreset.cs
=> Implemented VrmLib.ExpressionPreset.Surprised

Assets/VRM/Runtime/FirstPerson/VRMFirstPerson.cs
`VRMFirstPerson` のTypoを修正しました。
=> Fix typo (VRMFirstPerson)

Assets/UniGLTF/Runtime/UniGLTF/IO/AnimationExporter.cs
`AnimationCuve.keys` が空だった場合に、166 行目の`AnimationUtility.GetKeyRightTangentMode(curve, 0)` でエラーが出るのでAnimationCuve.keysのチェックを追加
=> Check Keyframe length of AnimationCurve

Assets/UniGLTF/Runtime/UniGLTF/IO/MeshExporter.cs
利便性のため `MeshWithRenderer` を使わずに glTFMesh を Export する関数を追加する
* `MeshExporter` は現状 Mesh 単体から glTFMesh 等を Export することができない
* 描画時に使用するメッシュ以外 Export する必要がないので基本的に上記の仕様で問題ないが、glTF に独自の拡張を追加する場合 Mesh 単体から glTFMesh を Export することが求められるケースがあると思われる
* 例えば拡張として MeshCollider を追加したい場合
=> MeshExporter に Renderer を必要としない Export 関数を追加

Assets/UniGLTF/Runtime/UniGLTF/IO/gltfExporter.cs
Exportする際に、verticesが無い（Length=0） のMeshが紛れていると、`MeshExporter.ExportPrimitives` で `ArgumentOutOfRangeException` が投げられていたので、除外するように修正
=> exclude meshes with no vertices

Assets/UniGLTF/Editor/Animation.meta, Assets/UniGLTF/Editor/Animation/AnimationValidator.cs, Assets/UniGLTF/Editor/Animation/AnimationValidator.cs.meta, Assets/UniGLTF/Editor/UniGLTF/GltfExportWindow.cs, Assets/UniGLTF/Runtime/Extensions/UnityExtensions.cs
* ExportRoot を animate する Animation を Export するときに `KeyNotFoundException` が発生する
* 上記の場合 Export 時に `UnityExtensions.GetFromPath`  の path に空文字が渡され、そのまま `UnityExtensions.GetChildByName` に空文字が渡されることに起因する
* 「ExportRoot を animate することはできない」は仕様的に正しいが、上記エラーの発生は意図したものではなさそうなので `GetFromPath` を修正する
* path を split するときに空文字を除外することで、path に空文字が渡されたときに自身の Transform を返すようにする
* `GetFromPath` を修正したことにより、ExportRoot を animate する Animation を正常に Export できる状態になってしまうので gltf エクスポート時に Validation を追加する
=> ExportRoot を animate する Animation を Export するときの挙動を修正

Assets/UniGLTF/Runtime/UniGLTF/IO/TextureLoader/TextureFactory.cs
runtime import の修正
```cs
var cacheName = param.ConvertedName;
if (param.TextureType == GetTextureParam.NORMAL_PROP)
{
cacheName = param.GltflName; // これでキーが変わるときがありえる
}
if (m_externalMap.TryGetValue(cacheName, out external))
{
if (!m_textureCache.ContainsKey(cacheName)) // ここで重複確認する
{
m_textureCache.Add(cacheName, new TextureLoadInfo(external, used, true));
}
return external;
}
```
* 発生条件: 複数のマテリアルで同じ法線マップを参照している
=> fix runtime texture import

Assets/VRM10/Runtime/Migration/RotateY180.cs
VRM 1.0 の Migration 時に、Buffer に Sparse Accessor が指定されている場合を想定していなかったのを修正。
ただし glTF の構造上、この修正だと二重に反転させてしまう場合がありえる。
=> Consider the sparse accessor while migration.

Assets/UniGLTF/Runtime/UniGLTF/IO/ImporterContext.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/NodeImporter.cs
* あまり root のみのオブジェクトを Export/Import するケースは無いが、念のため修正
=> scene.nodes が無い glTF ファイルを Import したときに null reference exception が発生していた問題を修正

Assets/VRMShaders/UniUnlit/Resources/UniUnlit.shader
Fixed an issue where the right eye was not rendered when rendering in Single Pass Instanced mode.
Verified to work with Unity 2020.3.1f1 + OpenVR XR Plugin.
=> Add support for single pass instanced stereo rendering to UniUnlit shader

Assets/VRM10/Runtime/Migration/MigrationVector3.cs, Assets/VRM10/Runtime/Migration/MigrationVector3.cs.meta, Assets/VRM10/Runtime/Migration/MigrationVrm.cs, Assets/VRM10/Runtime/Migration/MigrationVrmFirstPersonAndLookAt.cs, Assets/VRM10/Runtime/Migration/MigrationVrmFirstPersonAndLookAt.cs.meta, Assets/VRM10/Runtime/Migration/MigrationVrmSpringBone.cs
* lookAt の migration を実装
* firstPerson の migration を実装
* SpringBone と LookAt の座標変換は、 (x, y, -z) じゃなくて (-x, y, z)
=> implement MigrationVrmLookAtAndFirstPerson. fix MigrateVector3

Assets/VRM/Runtime/SpringBone/VRMSpringBone.cs, Assets/VRM/Runtime/SpringBone/VRMSpringBoneColliderGroup.cs
public static float Max(params float[] values);
#843
=> Do not use the variadic max to avoid gc

Assets/UniGLTF/Runtime/UniGLTF/IO/MeshImporter.cs
* primitive が複数ある
* blendShape がある
* UniGLTF以外でエクスポートした Mesh (共有Mesh方式ではない)
#800
|primitive|target0|target1|
|-|-|-|
|0|00|01|
|1|10|11|
bug
```
mesh.
blendshape 00
blendshape 01
blendshape 11
blendshape 11
```
fix
```
mesh.
blendshape 00 + blendshape 10
blendshape 01 + blendshape 11
```
=> BlendShapeの連結バグの修正

Assets/VRM/Editor/Format/VRMEditorImporterContext.cs, Assets/VRM/Editor/Format/VRMImporterMenu.cs, Assets/VRM/Editor/Format/vrmAssetPostprocessor.cs, Assets/VRM/Runtime/IO/VRMImporterContext.cs, Assets/VRM/Runtime/IO/VRMMaterialImporter.cs, Assets/VRM/Runtime/IO/VRMMaterialImporter.cs.meta, Assets/VRM/Tests/MToonTest.cs, Assets/VRM/Tests/VRMTextureEnumerateTests.cs
* VRMMToonMaterialImporter を VRMMaterialImporter にリネーム(Exporterと対になるように)
* VRMEditorImporterContext.AvoidOverwriteAndLoad 周りの未使用コード・コメントを削除
=> VRMMaterialImporterのリネームと、コメントと未使用コード削除

Assets/VRM10/Editor/Components/SpringBone/VRM10SpringSelectorWindow.cs, Assets/VRM10/Editor/Components/SpringBone/VRM10SpringSelectorWindow.cs.meta, Assets/VRM10/Runtime/Components/SpringBone/VRM10SpringBone.cs, Assets/VRM10/Runtime/Components/SpringBone/VRM10SpringBoneColliderGroup.cs, Assets/VRM10/Runtime/Components/SpringBone/VRM10SpringJoint.cs, Assets/VRM10/Runtime/Components/VRM10Controller.cs
スプリングボーン周り
* Spring と Collider をヒエラルキーから探索するのが大変なので、 VRM10SpringSelectorWindow 作った。
* 構成変更により無効になった Gizmo を復旧
* SpringBone の center の仕様を変更
=> [VRM1] SpringBone center をモデルレベルに移動など

Assets/VRM10/Editor/Components/SpringBone/VRM10SpringSelectorWindow.cs
=> SpringBoneWindow が見切れるのを修正。初期選択も実装

Assets/VRM10/Runtime/IO/RuntimeUnityBuilder.cs, Assets/VRM10/Tests/MigrationTests.cs
* VRM部分(SpringBone, Constraint)で座標変換が無かった
=> [1.0] Importerを修正

.gitmodules, Assets/VRMShaders/MToon.meta
UPM には「特定の過去のタグの UPM Package を指定しても、現在の master の .gitmodules を参照してしまう」というバグが有る。
そのバグを考慮して .gitmodules には記述を残しつつ、submodule を移動した。
=> mv MToon submodule due to UPM issue.

Assets/VRMShaders/VRM/MToon.meta
#883 の追加し忘れ。
以前の guid `ad4e8fc4ac2f50a4d82dc71d012a3596` を引き継ぎ。
=> Add MToon directory meta file

Assets/UniGLTF/Editor/UniGLTF/ScriptedImporter/TextureExtractor.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/SubAssetKey.cs
Equals(object o) と間違えてもコンパイルエラーにならないので
=> SubAssetKey == を実装した

Assets/VRM10/Runtime/IO/MeshAdapter.cs, Assets/VRM10/Runtime/IO/Vrm10Exporter.cs, Assets/VRM10/Runtime/IO/Vrm10MaterialExporter.cs, Assets/VRM10/Runtime/IO/Vrm10MaterialImporter.cs
不要なコードを削除。
一部実装。
* Color
* ColorTexture
=> [1.0]MToon export の実装

Assets/UniGLTF/Runtime/UniGLTF/IO/MeshWithRenderer.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/gltfExporter.cs
* Rendererのインスタンス一致でmeshIndexを決定してた部分を、MeshインスタンスとMaterialインスタンスを見てmeshIndexを決定するように変更
* Cube_1とCube_2はそれぞれRendererコンポーネントが付いている状態
* 両方とも同じMeshとMaterialインスタンスをRendererが参照している
* このプルリクの変更を入れてExportした場合、以下のjsonのように両方ともmeshIndex = 0を指し、かつmeshは１つだけexportされる
* 以下Exportしたglbの中身を一部抜粋
```
"nodes": [
{
"mesh": 0,
"name": "Cube_1",
"rotation": [
0,
0,
0,
1
],
"scale": [
1,
1,
1
],
"translation": [
0,
0,
0
]
},
{
"mesh": 0,
"name": "Cube_2",
"rotation": [
0,
0,
0,
1
],
"scale": [
1,
1,
1
],
"translation": [
0,
0,
0
]
}
],
"meshes": [
{
"extras": {
"targetNames": []
},
"name": "Cube",
"primitives": [
{
"attributes": {
"NORMAL": 1,
"POSITION": 0,
"TEXCOORD_0": 2,
"TEXCOORD_1": 3
},
"extras": {
"targetNames": []
},
"indices": 4,
"material": 0,
"mode": 4
}
]
}
],
```
=> 同一のMeshとMaterialを参照しているNodeをExportする場合に、重複をチェックして同じMeshIndexを参照するように変更

Assets/UniGLTF/Editor/UniGLTF/ScriptedImporter/ScriptedImporterExtension.cs, Assets/VRM10.Samples/Runtime/ViewerUI.cs, Assets/VRM10/Editor/Components/VRM10ControllerEditor.cs, Assets/VRM10/Editor/ScriptedImporter/EditorVrm.cs, Assets/VRM10/Editor/ScriptedImporter/VrmScriptedImporterEditorGUI.cs, Assets/VRM10/Editor/ScriptedImporter/VrmScriptedImporterImpl.cs, Assets/VRM10/Editor/Vrm10ExportDialog.cs, Assets/VRM10/Runtime/Components/VRM10Controller.cs, Assets/VRM10/Runtime/Components/VRM10ControllerMeta.cs, Assets/VRM10/Runtime/Components/VRM10ControllerMeta.cs.meta, Assets/VRM10/Runtime/IO/RuntimeUnityBuilder.cs, Assets/VRM10/Runtime/IO/Vrm10Exporter.cs
1.0 の Meta と Expression の Extract の修正
* VrmScriptedImporter の Null 修正
* Meta と Expression が ExternalObjectMap を使う
* 個別リソース置き換えの修正
=> [1.0] Fix10/vrm extract

Assets/UniGLTF/Runtime/UniGLTF/IO/MeshWithRenderer.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/gltfExporter.cs
=> backport v0.67 #899

Assets/VRM10/Editor/Components/VRM10ControllerEditor.cs, Assets/VRM10/Editor/ScriptedImporter/EditorVrm.cs, Assets/VRM10/Runtime/Components/Expression/VRM10ExpressionAvatar.cs, Assets/VRM10/Runtime/Components/VRM10ControllerExpression.cs, Assets/VRM10/Runtime/IO/Vrm10Exporter.cs, Assets/VRM10/Runtime/IO/Vrm10Importer.cs
当初考えていたExpressionAvatar だけ保存しておいて付け替えるような使い方はしなかったので、
分かりにくいだけになってしまった。
カスタムエディタ記述のため  SerializedObject に出来た方がいいので、 MonoBehaviour になる。
=> ExpressionAvatar は 独立した ScriptableObject をやめる

Assets/UniGLTF/Runtime/UniGLTF/IO/gltfExporter.cs
* https://github.com/vrm-c/UniVRM/issues/909
* こちらの件の修正
* mesh.verticesを見て０の場合はmeshを出力しないように変更
* TMPの場合はmesh.vertices = 0になっているためこの方法で防御
* TMPコンポーネントがGameObjectに存在しているか判定する方法だとTMP依存になってしまうため、いったんこの方法を取った。
=> mesh.vertices = 0 の場合にmeshとmaterialをexportしないように修正

Assets/UniGLTF/Editor/Generator/DeserializerWriter.cs, Assets/UniGLTF/Editor/Generator/FormatWriter.cs, Assets/UniGLTF/Editor/JsonSchema/Schemas/ExtensionJsonSchema.cs, Assets/VRM10/Editor/GeneratorMenu.cs, Assets/VRM10/Runtime/Format/Constraints/Deserializer.g.cs, Assets/VRM10/Runtime/Format/Constraints/Format.g.cs, Assets/VRM10/Runtime/Format/Constraints/Serializer.g.cs, Assets/VRM10/Runtime/Format/MaterialsMToon/Deserializer.g.cs, Assets/VRM10/Runtime/Format/MaterialsMToon/Format.g.cs, Assets/VRM10/Runtime/Format/MaterialsMToon/Serializer.g.cs, Assets/VRM10/Runtime/Format/SpringBone/Deserializer.g.cs, Assets/VRM10/Runtime/Format/SpringBone/Format.g.cs, Assets/VRM10/Runtime/Format/SpringBone/Serializer.g.cs, Assets/VRM10/Runtime/Format/Vrm/Deserializer.g.cs, Assets/VRM10/Runtime/Format/Vrm/Format.g.cs, Assets/VRM10/Runtime/Format/Vrm/Serializer.g.cs, Assets/VRM10/Tests/MigrationTests.cs
GltfExtension の JsonSchema から生成した Format.cs から、型依存を取り除いた
=> [1.0]ジェネレーターの生成コード(Format)からUniJSON, UniGLTF依存を除去

Assets/UniGLTF/Editor/Generator/Generator.cs, Assets/VRM10/Editor/GeneratorMenu.cs, Assets/VRM10/Runtime/Format/Constraints/Deserializer.g.cs, Assets/VRM10/Runtime/Format/Constraints/Format.g.cs, Assets/VRM10/Runtime/Format/Constraints/Serializer.g.cs, Assets/VRM10/Runtime/Format/MaterialsMToon/Deserializer.g.cs, Assets/VRM10/Runtime/Format/MaterialsMToon/Serializer.g.cs, Assets/VRM10/Runtime/Format/SpringBone/Deserializer.g.cs, Assets/VRM10/Runtime/Format/SpringBone/Format.g.cs, Assets/VRM10/Runtime/Format/SpringBone/Serializer.g.cs, Assets/VRM10/Runtime/Format/Vrm/Deserializer.g.cs, Assets/VRM10/Runtime/Format/Vrm/Format.g.cs, Assets/VRM10/Runtime/Format/Vrm/Serializer.g.cs, Assets/VRMShaders/VRM10/Format.meta, Assets/VRMShaders/VRM10/Format/Runtime.meta, Assets/VRMShaders/VRM10/Format/Runtime/MaterialsMToon.meta, Assets/VRMShaders/VRM10/Format/Runtime/MaterialsMToon/Format.g.cs, Assets/VRMShaders/VRM10/Format/Runtime/MaterialsMToon/Format.g.cs.meta, Assets/VRMShaders/VRM10/Format/Runtime/VRMShaders.VRM10.Format.Runtime.asmdef, Assets/VRMShaders/VRM10/Format/Runtime/VRMShaders.VRM10.Format.Runtime.asmdef.meta
- Generator can generate different directories between format and serializer.
- Generate MToon format.g.cs in `Assets/VRMShaders/VRM10/Format/Runtime/MaterialsMToon`
=> Generate MToon format.g.cs in VRMShaders

Assets/UniGLTF/Editor/UniGLTF/ScriptedImporter/EditorMaterial.cs, Assets/UniGLTF/Editor/UniGLTF/ScriptedImporter/GlbScriptedImporterEditorGUI.cs, Assets/UniGLTF/Editor/UniGLTF/ScriptedImporter/GltfScriptedImporterEditorGUI.cs, Assets/VRM10/Editor/ScriptedImporter/EditorVrm.cs, Assets/VRM10/Editor/ScriptedImporter/VrmScriptedImporterEditorGUI.cs
* VRM1の asset が VRM0 と別フォルダになるように修正(migrateしたときに混在してしまう)
* VRM10ExpressionAvatar が MonoBehaviour になって Extract対象から外れたことの修正
=> vrm1 の Extract 先を vrm0 と別になるように修正。

Assets/VRMShaders/GLTF/IO/Runtime/TextureConverter.cs
- `GL.sRGBWrite` はそもそも Linear パイプラインの都合を捻じ曲げたいときの最終手段ゆえ、できるかぎり使うべきではない
- いまの使用箇所ではそもそも `GL.sRGBWrite` が機能していないため
- sRGB のテクスチャに書き込むときは `GL.sRGBWrite = true;` になっている
- Linear のテクスチャに書き込むときは `GL.sRGBWrite = false;` になっている
=> Remove GL.sRGBWrite

Assets/UniGLTF/Editor/UniGLTF/ExportDialog/M17N.cs, Assets/UniGLTF/Tests/UniGLTF/M17NTest.cs, Assets/UniGLTF/Tests/UniGLTF/M17NTest.cs.meta
`MsgCache` が `enum` の `value` を保存すべきところで、引数で渡された `key` を保存しています。 
これでは、`enum` のすべての値が、最初に渡された `key` の文字列としてキャッシュされてしまうため、これを修正しました。
=> Fix incorrect value caching of M17N

Assets/UniGLTF/Editor/MeshUtility/TextureSaver.cs, Assets/UniGLTF/Runtime/Extensions/ColorConversionExtensions.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/TextureIO/GltfTextureExporter.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/gltfExporter.cs, Assets/UniGLTF/Tests/UniGLTF/TextureTests.cs, Assets/VRM/Runtime/IO/VRMExporter.cs, Assets/VRM10/Runtime/IO/Vrm10Exporter.cs, Assets/VRMShaders/GLTF/IO/Editor/AssetTextureUtil.cs, Assets/VRMShaders/GLTF/IO/Runtime/ColorSpace.cs, Assets/VRMShaders/GLTF/IO/Runtime/ColorSpace.cs.meta, Assets/VRMShaders/GLTF/IO/Runtime/TextureConverter.cs, Assets/VRMShaders/GLTF/IO/Runtime/TextureExporter.cs, Assets/VRMShaders/GLTF/IO/Runtime/TextureImportTypes.cs, Assets/VRMShaders/GLTF/IO/Tests/4x4.png.meta, Assets/VRMShaders/GLTF/IO/Tests/4x4compressed.DDS.meta, Assets/VRMShaders/GLTF/IO/Tests/CopyTextureTests.cs, Assets/VRMShaders/GLTF/IO/Tests/CopyTextureTests.cs.meta, Assets/VRMShaders/GLTF/IO/Tests/TextureBytesTests.cs
Unity の `Texture2D` は状態として、 Compressed であったり Non-readable であったりする。
これらの状態の場合 `Texture2D.EncodeToPNG()` は失敗となる。
それらの場合でも PNG を出力できるようにする。
具体的には `Texture2D` をいったん別の `Texture2D` にコピーして PNG を出力する。
またその際 `Texture2D` の色空間が既知である必要があるため、別途 `ColorSpace` を伝搬させるようにした。
=> Exporter can export compressed or non-readable texture.

Assets/UniGLTF/Runtime/UniGLTF/IO/MeshExportUtil.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/TextureIO/TextureSamplerUtil.cs
#943 
* magFilter が glTF の仕様を守っていないのを修正
* DIVIDE_VERTEX_BUFFER 時に position の accessor に min, max が無かったのを修正
=> fix MagFiler

Assets/UniGLTF/Tests/UniGLTF/MeshExportValidatorTests.cs, Assets/UniGLTF/Tests/UniGLTF/MeshExportValidatorTests.cs.meta
`MeshExportValidator` のテストケースを追加しました。
1 つのメッシュを持つオブジェクトに対し、
- マテリアル数 0
- `null` のマテリアル数 1
- `null` のマテリアル数 2
のテストケースを作成しました。  
いずれのケースも、Validator は、エクスポート不可とすべきはずです。  
しかし、`null` のマテリアル数 2 の場合は、エクスポート不可にならず、テストに失敗します。
=> Add test cases for validating null materials

Assets/VRM10/Runtime/Migration/MigrationMToon.cs
=> skip non mtoon material

Assets/VRM10/Editor/Components/Constraint/VRM10AimConstraintEditor.cs, Assets/VRM10/Editor/Components/Constraint/VRM10PostionRotationConstraintEditorBase.cs, Assets/VRM10/Runtime/Components/Constraint/ConstraintSource.cs, Assets/VRM10/Runtime/Components/Constraint/VRM10AimConstraint.cs, Assets/VRM10/Runtime/Components/Constraint/VRM10Constraint.cs, Assets/VRM10/Runtime/Components/Constraint/VRM10PositionConstraint.cs, Assets/VRM10/Runtime/Components/Constraint/VRM10RotationConstraint.cs, Assets/VRM10/Runtime/Components/Constraint/VRM10RotationPositionConstraintBase.cs, Assets/VRM10/Runtime/IO/Vrm10Importer.cs
* 赤の線が up_vector
* 位置部の共通機能(ModelRootなど)を親 class に移動
=> [1.0] aim constraint の up vector の目標空間 model/local を実装

Assets/VRMShaders/GLTF/IO/Editor/EditorTextureSerializer.cs
サポートしないテクスチャは明示的に例外。
それに Unity が Obsolute な enum を勝手に書き換えてコンパイルエラーになるので消去。
=> Throw not supported texture types

Assets/UniGLTF/Tests/UniGLTF/MeshExportValidatorTests.cs
`MeshExportValidator` のテストケースを追加しました。
以下のオブジェクトを Validator に渡すと `NullReferenceException` が発生します。 
- MeshFilter 無し、マテリアル有り
- MeshFilter のメッシュが `null`、マテリアル有り
Validator は、例外を発生させることなく、適切な結果を返すことを期待します。
```
NullReferenceException: Object reference not set to an instance of an object
UniGLTF.MeshExportValidator.CalcMeshSize (UniGLTF.MeshExportInfo& info, System.String relativePath) (at Assets/UniGLTF/Editor/UniGLTF/ExportDialog/MeshExportValidator.cs:47)
UniGLTF.MeshExportValidator.TryGetMeshInfo (UnityEngine.GameObject root, UnityEngine.Renderer renderer, UniGLTF.MeshExportInfo& info) (at Assets/UniGLTF/Editor/UniGLTF/ExportDialog/MeshExportValidator.cs:156)
UniGLTF.MeshExportValidator.SetRoot (UnityEngine.GameObject ExportRoot, UniGLTF.MeshExportSettings settings) (at …
```
=> メッシュが無いオブジェクトに対する MeshExportValidator のテストを追加

Assets/VRMShaders/GLTF/IO/Runtime/NormalConverter.cs, Assets/VRMShaders/GLTF/IO/Runtime/OcclusionMetallicRoughnessConverter.cs, Assets/VRMShaders/GLTF/IO/Runtime/RuntimeTextureSerializer.cs, Assets/VRMShaders/GLTF/IO/Runtime/TextureConverter.cs, Assets/VRMShaders/GLTF/IO/Runtime/TextureExporter.cs, Assets/VRMShaders/GLTF/IO/Tests/CopyTextureTests.cs
#983 をマージ後にレビューお願いします。
glTF Export 時、アルファチャンネルが不要であると判断できる以下の場合にアルファチャンネル無しで Export します。
- Linear
- Normal
- Metallic-Roughness
以下の glTF-Sample-Models の再出力を行った場合、以下のようになりました
https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/FlightHelmet
| File | Bytes |
| --- | --- |
| original | 48,392,382 bytes (46.1 MB) |
| export with UniGLTF (old) | 61,554,876 bytes (58.7 MB) |
| export with UniGLTF (PR) | 57,222,392 bytes (54.5 MB) |
さらに sRGB テクスチャもアルファチャンネルを考慮して出力すれば original と同様のサイズになります。
しかし sRGB テクスチャは「アルファチャンネルを必要とするプロパティと必要としないプロパティどちらからも参照されうる」ので今の仕組みではできない判定を行う必要があるため、本 PR では行いません。
=> Export textures without alpha channel if the texture was linear, normal, or metallic-roughness.

Assets/UniGLTF/Editor/UniGLTF/UniGLTFPreference.cs, Assets/VRM/Editor/VrmPreference.cs
workaround
https://github.com/Unity-Technologies/com.unity.cinemachine/blob/master/Editor/Windows/CinemachineSettings.cs#L313
=> use SettingProvider

Assets/UniGLTF/Runtime/UniGLTF/IO/MeshIO/BlendShapeExporter.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/MeshIO/BlendShapeExporter.cs.meta, Assets/UniGLTF/Runtime/UniGLTF/IO/MeshIO/MeshExportUtil.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/MeshIO/MeshExporter_DividedVertexBuffer.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/MeshIO/MeshExporter_SharedVertexBuffer.cs, Assets/VRM10/Editor/ScriptedImporter/VrmScriptedImporterImpl.cs, Assets/VRM10/Runtime/IO/Model/MeshImporterDivided.cs, Assets/VRM10/Runtime/IO/Model/MeshWriter.cs, Assets/VRM10/Runtime/Migration/RotateY180.cs
#962 #861
|          | vertex buffer | defaut | comment          |
|----------|---------------|--------|------------------|
| glb/gltf | shared        |        | 既存             |
| vrm      | shared(仕様)  |        | 既存             |
| glb/gltf | divided       |        | この修正から有効 |
| vrm1     | divided(仕様) | on     | この修正から有効 |
UniVRM では、morphTarget の accessor にのみ sparse を適用します。
=> 既存の morphTarget の sparse export を整理して、divided 頂点バッファでも動くようにした

Assets/VRMShaders/GLTF/IO/Runtime/MaterialFactory.cs, Assets/VRMShaders/GLTF/IO/Runtime/VRMShaders.GLTF.IO.Runtime.asmdef
=> 古いシェーダー名をフォールバック

Assets/VRM/Runtime/IO/VRMMToonTextureImporter.cs, Assets/VRM/Runtime/IO/VrmTextureDescriptorGenerator.cs, Assets/VRM/Tests/VRMTextureEnumerateTests.cs
standard, unlit に fallback する条件を変更
* `ShaderName != "VRM/MToon"` => `ShaderName == VRM_USE_GLTFSHADER`
未知のシェーダーも vrm extensions の dictionary を使う。
=> 古いvrmのTextureImportを修正

Assets/UniGLTF/Tests/UniGLTF/UniGLTFTests.cs
`UniGLTF.gltfExporter` のテストケースを追加しました。
`MeshFilter` のメッシュが `null` でマテリアルがある場合に、  
`MeshExportValidator` はエクスポート可を返すにもかかわらず、 
`Mesh not found.` 例外が発生します。
```
System.Exception : Mesh not found.
at UniGLTF.gltfExporter.ExportNode (UnityEngine.Transform x, System.Collections.Generic.List`1[T] nodes, System.Collections.Generic.List`1[T] meshWithRenderers, System.Collections.Generic.List`1[T] skins) [0x00128] in Assets/UniGLTF/Runtime/UniGLTF/IO/gltfExporter.cs:175 
at UniGLTF.gltfExporter.Export (UniGLTF.MeshExportSettings meshExportSettings, VRMShaders.ITextureSerializer textureSerializer) [0x00272] in Assets/UniGLTF/Runtime/UniGLTF/IO/gltfExporter.cs:259 
```
=> Add a test case for exporting nodes contains null mesh

Assets/VRM10/Editor/ScriptedImporter/EditorVrm.cs
When extracting VRM Meta file, Unity sometimes find `{importer.assetPath}.vrm1` file 's `.meta` file rarely (because Unity's cache strategy?).
So VRM Meta file directory will be named to `{importer.assetPath}.vrm1.MetaObject` .
This name follows vrm 0.x.
=> Fix failing extracting vrm meta file in vrm 1.0 (rarely)

Assets/VRM10/Editor/Components/LookAt/LookAtEditor.cs, Assets/VRM10/Editor/Components/VRM10ControllerEditor.cs, Assets/VRM10/Editor/Components/VRM10Window.cs, Assets/VRM10/Runtime/Components/VRM10Controller.cs, Assets/VRM10/Runtime/Components/VRM10ControllerRuntime.cs, Assets/VRM10/Runtime/Components/VRM10ControllerRuntime.cs.meta
* runtime 変数置き場を隔離して、初期化を遅延
* Editor 用の変数の初期化を分離。
VRM10Controller.Reset, Start, Setup を整理。
=> VRM10Controllerの変数管理を修正

Assets/VRMShaders/VRM10/MToon10/Resources/VRM10/vrmc_materials_mtoon_define.hlsl, Assets/VRMShaders/VRM10/MToon10/Resources/VRM10/vrmc_materials_mtoon_forward_fragment.hlsl, Assets/VRMShaders/VRM10/MToon10/Resources/VRM10/vrmc_materials_mtoon_geometry_alpha.hlsl, Assets/VRMShaders/VRM10/MToon10/Resources/VRM10/vrmc_materials_mtoon_geometry_alpha.hlsl.meta
=> Refactoring mtoon 1.0 alpha

Assets/UniGLTF/Editor/UniGLTF.Editor.asmdef, Assets/UniGLTF/Runtime/UniGLTF.asmdef, Assets/UniGLTF/Tests/UniGLTF.Tests.asmdef, Assets/UniGLTF/UniHumanoid/Editor/Tests/UniHumanoid.Editor.Tests.asmdef, Assets/UniGLTF/UniHumanoid/Editor/UniHumanoid.Editor.asmdef, Assets/UniGLTF/UniHumanoid/UniHumanoid.asmdef, Assets/VRM.Samples/Editor/Tests/VRM.Samples.Editor.Tests.asmdef, Assets/VRM.Samples/VRM.Samples.asmdef, Assets/VRM/Editor/VRM.Editor.asmdef, Assets/VRM/Runtime/VRM.asmdef, Assets/VRM/Tests/VRM.Tests.asmdef, Assets/VRM10.Samples/Runtime/VRM10.Samples.Runtime.asmdef, Assets/VRM10/Editor/VRM10.Editor.asmdef, Assets/VRM10/Runtime/VRM10.asmdef, Assets/VRM10/Tests.PlayMode/VRM10.Tests.PlayMode.asmdef, Assets/VRM10/Tests/VRM10.Tests.asmdef, Assets/VRM10/vrmlib/Runtime/VrmLib.asmdef, Assets/VRM10/vrmlib/Tests/VrmLib.Tests.asmdef, Assets/VRMShaders/GLTF/IO/Tests/VRMShaders.GLTF.IO.Tests.asmdef, Assets/VRMShaders/GLTF/UniUnlit/Editor/VRMShaders.GLTF.UniUnlit.Editor.asmdef, Assets/VRMShaders/GLTF/UniUnlit/Runtime/VRMShaders.GLTF.UniUnlit.Runtime.asmdef, Assets/VRMShaders/VRM/IO/Editor/VRMShaders.VRM.IO.Editor.asmdef, Assets/VRMShaders/VRM/IO/Runtime/VRMShaders.VRM.IO.Runtime.asmdef, Assets/VRMShaders/VRM10/Format/Runtime/VRMShaders.VRM10.Format.Runtime.asmdef, Assets/VRMShaders/VRM10/MToon10/Editor/VRMShaders.VRM10.MToon10.Editor.asmdef, Assets/VRMShaders/VRM10/MToon10/Runtime/VRMShaders.VRM10.MToon10.Runtime.asmdef
AutoReferenced を Disable にすることで、モジュールの参照関係が逆転するなどの事故を防ぐ
=> Disable "AutoReferenced" in all asmdefs.

Assets/UniGLTF/Runtime/UniGLTF/IO/gltfExporter.cs
=> fix mesh == null

Assets/UniGLTF/Runtime/UniGLTF/RuntimeGltfInstance.cs, Assets/UniGLTF/Tests/UniGLTF/TextureTests.cs, Assets/VRM10/Runtime/Migration/MigrationMToon.cs, Assets/VRM10/Tests/MigrationTests.cs
* [1.0] SpringBone の JsonSchema 変更対応
* Mtoon マイグレーション。enum 不正値対応
* ImporterContext.Load 関数の呼び出しでテクスチャが ImporterContext から GameObject に移動することに対応
=> 最近の UnitTest

Assets/UniGLTF/Editor/UniGLTF/Serialization/SerializerGenerator.cs, Assets/UniGLTF/Runtime/UniGLTF/Format/GltfSerializer.g.cs, Assets/UniGLTF/Runtime/UniGLTF/Format/glTFNode.cs
#1059
```json
{
"name": "1",
"translation": [
0,
0,
0
],
"rotation": [
0,
0,
0,
1
],
"scale": [
1,
1,
1
]
}
```
👇
```json
{
"name": "1"
}
```
=> Export 時に default 値の TRS を出力しない

Assets/UniGLTF/Runtime/UniGLTF/IO/GltfParser.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/ImporterContext.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/MigrationFlags.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/MigrationFlags.cs.meta, Assets/UniGLTF/Runtime/UniGLTF/IO/TextureIO/Shaders/StandardMapImporter.shader, Assets/VRMShaders/GLTF/IO/Runtime/OcclusionMetallicRoughnessConverter.cs, Assets/VRMShaders/GLTF/IO/Runtime/TextureFactory.cs, Assets/VRMShaders/GLTF/IO/Tests/MetallicRoughnessConverterTests.cs
UniGLTF v0.69 未満の場合に Roughness Texture が二乗されて格納されていた。それを加味できるコードを追加。
実際には判定する材料が足りないので自動では行わない
=> Add migration code about legacy roughness texture behaviour.

Assets/UniGLTF/Runtime/UniGLTF/Format/glbTypes.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/GltfParser.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/glbImporter.cs
Because glTF specification says
> Client implementations must ignore chunks with unknown types to enable glTF extensions to reference additional chunks with new types following the first two chunks.
https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#chunks
=> Allow referencing additional chunks.

Assets/VRM10/Runtime/Migration/MigrationMToon.cs, Assets/VRMShaders/VRM10/MToon10/Resources/VRM10/vrmc_materials_mtoon.shader, Assets/VRMShaders/VRM10/MToon10/Resources/VRM10/vrmc_materials_mtoon_forward_vertex.hlsl, Assets/VRMShaders/VRM10/MToon10/Resources/VRM10/vrmc_materials_mtoon_lighting_mtoon.hlsl
bugs
- Couldn't compile on Unity 2018.4.
- EmissionColor was not considered when emissionMap is null.
- OutlineWidthTexture doesn't reference uv correctly.
=> [1.0] Fix MToon 1.0 bugs

Assets/UniGLTF/Runtime/UniGLTF/IO/ZipArchiveStorage.cs
`Stored` なファイルを展開する際に、ファイル本体ではなく Local File Header の位置を指して展開していたのを修正。
=> Fix bug of unarchiving stored file in zip.

Assets/UniGLTF/Editor/UniGLTF/ScriptedImporter/ZipArchivedGltfScriptedImporter.cs, Assets/UniGLTF/Editor/UniGLTF/ScriptedImporter/ZipArchivedGltfScriptedImporter.cs.meta, Assets/UniGLTF/Editor/UniGLTF/UniGLTFPreference.cs
=> experimental zip archive importer

Assets/UniGLTF/Runtime/Extensions/UnityExtensions.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/NodeImporter.cs, Assets/UniGLTF/Tests/UniGLTF/MatrixTests.cs, Assets/UniGLTF/Tests/UniGLTF/MatrixTests.cs.meta
#1078
行列式が負であるときに、Xミラーであると決め打ちする。
Yミラー、Zミラー、XYZミラーと区別する方法、あるのだろうか？
=> Nodeの行列分解時の負のスケールの限定対応

Assets/UniGLTF/Runtime/UniGLTF/IO/Parser/GlbLowLevelParser.cs
UniGLTF は Unity に展開されるリソースオブジェクトの名前が被りうる場合は、それを Unique にする挙動をする。
これを GLTF 拡張でも同じルールでできるようにするために public 化。
=> Make public resource fix method

Assets/UniGLTF/Runtime/UniGLTF/RuntimeGltfInstance.cs
すでに `RuntmeGltfInstance` コンポーネントや gameobject が破壊されていた場合に Dispose を呼ぶと `MissingReferenceException` が出るのを修正
=> fix MissingReferenceException

Assets/VRM10/Tests/MaterialImportTests.cs, Assets/VRMShaders/VRM10/MToon10/Editor/MToon10EditorEditMode.cs, Assets/VRMShaders/VRM10/MToon10/Editor/MToon10EditorEditMode.cs.meta, Assets/VRMShaders/VRM10/MToon10/Editor/MToonInspector.cs, Assets/VRMShaders/VRM10/MToon10/Resources/VRM10/vrmc_materials_mtoon.shader, Assets/VRMShaders/VRM10/MToon10/Resources/VRM10/vrmc_materials_mtoon_define.hlsl, Assets/VRMShaders/VRM10/MToon10/Resources/VRM10/vrmc_materials_mtoon_forward_vertex.hlsl, Assets/VRMShaders/VRM10/MToon10/Resources/VRM10/vrmc_materials_mtoon_lighting_mtoon.hlsl, Assets/VRMShaders/VRM10/MToon10/Runtime/MToon10Migrator.cs, Assets/VRMShaders/VRM10/MToon10/Runtime/UnityShaderLab/Properties/MToon10Meta.cs, Assets/VRMShaders/VRM10/MToon10/Runtime/UnityShaderLab/Properties/MToon10Prop.cs, Assets/VRMShaders/VRM10/MToon10/Runtime/UnityShaderLab/Properties/MToon10Properties.cs, Assets/VRMShaders/VRM10/MToon10/Tests.meta, Assets/VRMShaders/VRM10/MToon10/Tests/MigrationTests.cs, Assets/VRMShaders/VRM10/MToon10/Tests/MigrationTests.cs.meta, Assets/VRMShaders/VRM10/MToon10/Tests/VRMShaders.VRM10.MToon10.Tests.asmdef, Assets/VRMShaders/VRM10/MToon10/Tests/VRMShaders.VRM10.MToon10.Tests.asmdef.meta
- Rename to `VRM10/MToon10`
- Improve Inspector.
- Fix Migration code & add tests.
=> Fix MToon 1.0 functions.

Assets/UniGLTF/Editor/UniGLTF/ExportDialog/MaterialValidator.cs, Assets/UniGLTF/Editor/UniGLTF/ExportDialog/MaterialValidator.cs.meta, Assets/UniGLTF/Editor/UniGLTF/ExportDialog/MeshExportValidator.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/MaterialExporter.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/MeshIO/MeshExportInfo.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/gltfExporter.cs, Assets/UniGLTF/Runtime/UniGLTF/Validation/Validation.cs, Assets/UniGLTF/Tests/UniGLTF/MeshTests.cs, Assets/VRM/Editor/Format/VRMExporterWizard.cs, Assets/VRM/Editor/VRM.Editor.asmdef
=> EditorTextureSerializer で例外になるテクスチャを事前にエラーメッセージにする

Assets/UniGLTF/Runtime/UniGLTF.asmdef, Assets/UniGLTF/UniHumanoid/UniHumanoid.asmdef, Assets/VRM/Runtime/VRM.asmdef, Assets/VRM10/Runtime/VRM10.asmdef, Assets/VRMShaders/GLTF/IO/Runtime/VRMShaders.GLTF.IO.Runtime.asmdef
https://github.com/vrm-c/UniVRM/issues/1107
ユーザが `ImporterContext` などの公開 API を使用するのに必要な asmdef の `Auto Referenced` を `true` に変更。
=> Make asmdef's auto-referenced true.

Assets/UniGLTF/Runtime/UniGLTF/RuntimeGltfInstance.cs
https://github.com/vrm-c/UniVRM/issues/1096
Runtime Resources にアクセスするためのプロパティを追加。
また `ShowMeshes()` と `EnableUpdateWhenOffscreen()` が関係のないレンダラを操作していたバグを修正。
=> Add properties & Fix the bug in `RuntimeGltfInstance`

Assets/UniGLTF/Runtime/UniGLTF/IO/gltfExporter.cs
`MeshExportInfo.CanExport` が false である場合、その mesh の export をスキップする
- `MeshExportList.GetInfo` で集めた `MeshExportInfo` の中には「Export 可能ではない Mesh の情報」（Mesh が null であったり、Mesh の vertexCount が 0 だったりするもの）が存在しうる
- しかし、mesh の Export 処理で Export 可能ではない Mesh の `MeshExportInfo` が渡された場合のハンドリングが抜けている
- mesh の export 処理で呼ばれる `MeshExporter_DividedVertexBuffer.Export` ならびに `MeshExporter_SharedVertexBuffer.Export` は Mesh が null ではない、Mesh の vertexCount が 0 ではないこと前提の処理となっており、そうでない `MeshExportInfo` が渡された場合 Exception が発生する
- Mesh が export 可能であるか否かは事前に判別可能（ `MeshExportInfo.CanExport` を見ればよい）であるため、CanExport が false の場合対象の mesh の export をスキップしたい
=> Skip mesh export when MeshExportInfo.CanExport is false

Assets/VRM.Samples/Scripts/VRMRuntimeExporter.cs
=> ラインタイムエクスポート時に正規化を実行する例

Assets/UniGLTF/Editor/UniGLTF/ScriptedImporter/GlbScriptedImporterEditor.cs, Assets/UniGLTF/Editor/UniGLTF/ScriptedImporter/GltfScriptedImporterEditor.cs, Assets/UniGLTF/Editor/UniGLTF/ScriptedImporter/RemapScriptedImporterEditorBase.cs, Assets/UniGLTF/Editor/UniGLTF/ScriptedImporter/ZipArchivedGltfScriptedImporterEditor.cs, Assets/VRM10/Editor/ScriptedImporter/VrmScriptedImporterEditorGUI.cs, ProjectSettings/ProjectVersion.txt
https://github.com/Unity-Technologies/UnityCsReference/blob/2019.4/Modules/AssetPipelineEditor/ImportSettings/AssetImporterEditor.cs#L443
=> 開発バージョンをUnity-2019にあげる。および、 Unity-2019 require ApplyRevertGUI call in OnInspectorGUI の修正

Assets/UniGLTF/Editor/UniGLTF.Editor.asmdef, Assets/UniGLTF/Runtime/UniGLTF.asmdef, Assets/UniGLTF/Tests/UniGLTF.Tests.asmdef, Assets/UniGLTF/UniHumanoid/Editor/Tests/UniHumanoid.Editor.Tests.asmdef, Assets/UniGLTF/UniHumanoid/Editor/UniHumanoid.Editor.asmdef, Assets/UniGLTF/UniHumanoid/UniHumanoid.asmdef, Assets/VRM.Samples/Editor/Tests/VRM.Samples.Editor.Tests.asmdef, Assets/VRM.Samples/VRM.Samples.asmdef, Assets/VRM/Editor/VRM.Editor.asmdef, Assets/VRM/Runtime/VRM.asmdef, Assets/VRM/Tests/VRM.Tests.asmdef, Assets/VRM10.Samples/Runtime/VRM10.Samples.Runtime.asmdef, Assets/VRM10/Editor/VRM10.Editor.asmdef, Assets/VRM10/Runtime/VRM10.asmdef, Assets/VRM10/Tests.PlayMode/VRM10.Tests.PlayMode.asmdef, Assets/VRM10/Tests/VRM10.Tests.asmdef, Assets/VRM10/vrmlib/Runtime/VrmLib.asmdef, Assets/VRM10/vrmlib/Tests/VrmLib.Tests.asmdef, Assets/VRMShaders/GLTF/IO/Editor/VRMShaders.GLTF.IO.Editor.asmdef, Assets/VRMShaders/GLTF/IO/Runtime/VRMShaders.GLTF.IO.Runtime.asmdef, Assets/VRMShaders/GLTF/IO/Tests/VRMShaders.GLTF.IO.Tests.asmdef, Assets/VRMShaders/GLTF/UniUnlit/Editor/VRMShaders.GLTF.UniUnlit.Editor.asmdef, Assets/VRMShaders/GLTF/UniUnlit/Runtime/VRMShaders.GLTF.UniUnlit.Runtime.asmdef, Assets/VRMShaders/VRM/IO/Editor/VRMShaders.VRM.IO.Editor.asmdef, Assets/VRMShaders/VRM/IO/Runtime/VRMShaders.VRM.IO.Runtime.asmdef, Assets/VRMShaders/VRM10/Format/Runtime/VRMShaders.VRM10.Format.Runtime.asmdef, Assets/VRMShaders/VRM10/MToon10/Editor/VRMShaders.VRM10.MToon10.Editor.asmdef, Assets/VRMShaders/VRM10/MToon10/Runtime/VRMShaders.VRM10.MToon10.Runtime.asmdef, Assets/VRMShaders/VRM10/MToon10/Tests/VRMShaders.VRM10.MToon10.Tests.asmdef
Unity 2019 へのアップグレードに伴い、 asmdef の参照関係を名前から GUID 解決へと変更。
MToon も同様の対応をした v3.9 にアップデート。
=> Use GUID in asmdefs

Assets/VRM/Editor/VRMExportUnityPackage.cs
=> VRM-1.0 の unitypackage も作成する

Assets/UniGLTF/Editor/UniGLTF/ScriptedImporter/RemapEditorAnimation.cs, Assets/UniGLTF/Editor/UniGLTF/ScriptedImporter/RemapEditorBase.cs, Assets/UniGLTF/Editor/UniGLTF/ScriptedImporter/RemapScriptedImporterEditorBase.cs
https://github.com/vrm-c/UniVRM/pull/796 で一旦2020対応されたが、
その後の変更で再度動かなくなっていたため修正
=> Unity2020対応のデグレを修正

Assets/VRM10/Editor/Components/Expression/SerializedExpressionEditor.cs, Assets/VRM10/Editor/Components/Expression/VRM10ControllerEditorExpression.cs, Assets/VRM10/Editor/Components/Expression/VRM10ExpressionEditor.cs, Assets/VRM10/Runtime/Components/Expression/DefaultExpressionValidator.cs, Assets/VRM10/Runtime/Components/Expression/ExpressionKey.cs, Assets/VRM10/Runtime/Components/Expression/ExpressionMerger.cs, Assets/VRM10/Runtime/Components/Expression/VRM10Expression.cs, Assets/VRM10/Runtime/Components/VRM10Object/VRM10ObjectExpression.cs, Assets/VRM10/Runtime/IO/Vrm10Exporter.cs, Assets/VRM10/Runtime/IO/Vrm10Importer.cs
* VRM10Expression.Preset は VRM10ObjectExpression　のどのスロットにセットされているかで判定
* VRM10Expression.ExpressionName は VRM10Expression.name を使う
https://github.com/vrm-c/vrm-specification/pull/296 で、
Expression をコレクションに格納するのをやめて、固定のフィールドに保持するように変更した。
実装の追随。
=> VRM10Expression.Preset と ExpressionName を廃止

Assets/UniGLTF/Runtime/UniGLTF/UniGLTFVersion.cs, Assets/VRM/Editor/Format/VRMVersionMenu.cs
* gltf/asset/generator は据え置き
#1156
=> 内部バージョンは維持 UniGLTF/UniGLTFVersion.cs

Assets/VRM10/Runtime/IO/Material/Vrm10MToonMaterialExporter.cs, Assets/VRM10/Runtime/IO/Texture/Vrm10MToonTextureImporter.cs
* export: null check
* import: texture の割り当て
=> Fix10/mtoon export/import

Assets/VRM10/Runtime/IO/Material/Vrm10MToonMaterialImporter.cs, Assets/VRMShaders/VRM10/MToon10/Editor/MToonInspector.cs
=> SubAssetでも中を見れるように、デフォルトで AdvancedMode にする

Assets/UniGLTF/Runtime/UniGLTF/IO/Parser/GlbBinaryParser.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/Parser/GlbBinaryParser.cs.meta
Glb バイナリを扱う Parser が `GlbLowLevelParser` となっており、API 上不親切。
明示的に新設。
=> Define GlbBinaryParser

Assets/UniGLTF/Editor/UniGLTF/ScriptedImporter/GlbScriptedImporter.cs, Assets/UniGLTF/Editor/UniGLTF/ScriptedImporter/GltfScriptedImporter.cs, Assets/UniGLTF/Editor/UniGLTF/ScriptedImporter/GltfScriptedImporterBase.cs, Assets/UniGLTF/Editor/UniGLTF/ScriptedImporter/ZipArchivedGltfScriptedImporter.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/ImporterContext.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/RenderPipelineTypes.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/RenderPipelineTypes.cs.meta, Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/URP.meta, Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/URP/GltfPbrURPMaterialImporter.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/URP/GltfPbrURPMaterialImporter.cs.meta, Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/URP/GltfURPMaterialDescriptorGenerator.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/URP/GltfURPMaterialDescriptorGenerator.cs.meta, Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/URP/UrpPipelineTypes.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/URP/UrpPipelineTypes.cs.meta, Assets/VRM/Runtime/IO/VRMImporterContext.cs, Assets/VRM/Runtime/IO/VRMURPMaterialDescriptorGenerator.cs, Assets/VRM/Runtime/IO/VRMURPMaterialDescriptorGenerator.cs.meta, Assets/VRM10/Editor/ScriptedImporter/VrmScriptedImporter.cs, Assets/VRM10/Editor/ScriptedImporter/VrmScriptedImporterEditorGUI.cs, Assets/VRM10/Editor/ScriptedImporter/VrmScriptedImporterImpl.cs, Assets/VRM10/Runtime/IO/Material/Vrm10UrpMaterialDescriptorGenerator.cs, Assets/VRM10/Runtime/IO/Material/Vrm10UrpMaterialDescriptorGenerator.cs.meta, Assets/VRM10/Runtime/IO/Vrm10Importer.cs
#1165
また、 `ImoprterContext`, `VRMImporterContext`, `Vrm10Importer` に materialGenerator 引数を追加して、
任意のマテリアル生成ロジックを追加できるようにした。
```cs
public VRMImporterContext(
GltfData data,
IReadOnlyDictionary<SubAssetKey, Object> externalObjectMap = null,
ITextureDeserializer textureDeserializer = null,
IMaterialDescriptorGenerator materialGenerator = null)
```
* GltfUrpMaterialDescriptorGenerator
* VRMUrpMaterialDescriptorGenerator
* Vrm10UrpMaterialDescriptorGenerator
が Urp 版のマテリアル生成ロジック。
下記のようにしてマテリアル生成動作を変更できる。
```cs
// 他の引数省略
new VrmImporterContext(materialGenerator: new VRMUrpMaterialDescriptorGenerator())
```
=> Add MaterialGenerator customization point (for URP)

Assets/UniGLTF/Runtime/UniGLTF/IO/ImporterContext.cs, Assets/VRM/Editor/Format/VRMImporterMenu.cs, Assets/VRM/Editor/Format/vrmAssetPostprocessor.cs, Assets/VRM/Runtime/IO/VRMData.cs, Assets/VRM/Runtime/IO/VRMData.cs.meta, Assets/VRM/Runtime/IO/VRMException.cs, Assets/VRM/Runtime/IO/VRMException.cs.meta, Assets/VRM/Runtime/IO/VRMImporterContext.cs, Assets/VRM/Samples/FirstPersonSample/VRMRuntimeLoader.cs, Assets/VRM/Samples/RuntimeExporterSample/VRMRuntimeExporter.cs, Assets/VRM/Samples/SimpleViewer/SimpleViewer.unity, Assets/VRM/Samples/SimpleViewer/ViewerUI.cs, Assets/VRM/Tests/MToonTest.cs, Assets/VRM/Tests/SampleTests/VRMImportExportTests.cs, Assets/VRM/Tests/VRMLoadTests.cs, Assets/VRM/Tests/VRMLookAtTests.cs, Assets/VRM/Tests/VrmDividedMeshTests.cs, Assets/VRM10/Editor/ScriptedImporter/VrmScriptedImporterEditorGUI.cs, Assets/VRM10/Editor/ScriptedImporter/VrmScriptedImporterImpl.cs, Assets/VRM10/Runtime/IO/Vrm10Data.cs, Assets/VRM10/Runtime/IO/Vrm10Data.cs.meta, Assets/VRM10/Runtime/IO/Vrm10Importer.cs, Assets/VRM10/Runtime/Scenes/Sample.cs, Assets/VRM10/Samples/VRM10Viewer/VRM10Viewer.unity, Assets/VRM10/Samples/VRM10Viewer/VRM10ViewerUI.cs, Assets/VRM10/Tests.PlayMode/MaterialTests.cs, Assets/VRM10/Tests/ApiSampleTests.cs
gltf から vrm 拡張を取り出す責務を `VrmData class` とした。
`VRMImporterContext` はこれを引数に受ける。
ドキュメントを書いていてサンプルコードを書いてみたら、
VRMImporterContext の materialGenerator をカスタマイズするのに VRM.glTF_VRM_extensions vrm が必用なのだが、
VRMImporterContext の中で VRM.glTF_VRM_extensions vrm を取り出していて使いづらかった。
* このインタフェースを使う SimpleViewer などのサンプル
* このインタフェースを使う Test
=> VRMImporterContext に VrmData を導入

Assets/VRM10/Runtime/IO/Texture/Vrm10TextureDescriptorGenerator.cs, Assets/VRM10/Runtime/Migration/MigrationVrm.cs, Assets/VRM10/Runtime/Migration/MigrationVrmMeta.cs, Assets/VRM10/Tests/ExpressionTests.cs, Assets/VRM10/Tests/LoadTests.cs, Assets/VRM10/Tests/LoadTests.cs.meta, Assets/VRM10/Tests/TestAsset.cs, Assets/VRM10/Tests/TestAsset.cs.meta
* 無かったらデフォルト名にフォールバック
* vrm0x では texture を使っていたのが、vrm10 では image を使うようになったので無名になるのかも。対処した
* univrm のエクスポートでは基本的に image と texture の index は一致する
#1188
=> [1.0] thumbnail の名前が無い時に SubAssetKey を作るのに失敗するのを修正

Assets/VRMShaders/GLTF/IO/Resources/UniGLTF/StandardMapExporter.shader, Assets/VRMShaders/GLTF/IO/Resources/UniGLTF/StandardMapExporter.shader.meta, Assets/VRMShaders/GLTF/IO/Runtime/OcclusionMetallicRoughnessConverter.cs
#1178 
* 変数名が Exporter になっていたのを Importer に修正
* 然る後に Exporter 一式追加
左エクスポート前、右エクスポート後再インポート。見分けは付かないのでたぶん OK
=> [Exporter] shader版の StandardMap の Exporter 変換を追加

Assets/VRM10/Runtime/Components/Expression/MaterialValueBindingMerger.cs, Assets/VRM10/Runtime/Components/Expression/PreviewMaterialItem.cs, Assets/VRM10/Samples/VRM10Viewer/VRM10AutoExpression.cs
=> 初期値との差分を使うようにロジックを変更

Assets/VRM10/Runtime/Components/Expression/Preview/PreviewMaterialUtil.cs, Assets/VRM10/Runtime/Components/Expression/Preview/PreviewMaterialUtil.cs.meta, Assets/VRM10/Runtime/Components/Expression/Preview/PreviewSceneManager.cs, Assets/VRM10/Runtime/Components/Expression/PreviewMaterialItem.cs
* PreviewSceneManager　が MonoBehaviour かつ Editor 専用なのが微妙
=> #if UNITY_EDITOR でビルドエラーを修正

Assets/UniGLTF/Runtime/UniGLTF/IO/ImporterContext.cs
LoadTexturesAsync・LoadMaterialsAsyncへのAwaitCallerの受け渡しが漏れていた問題を修正しました
=> LoadTexturesAsync・LoadMaterialsAsyncへのAwaitCallerの受け渡しが漏れていた問題を修正

Assets/UniGLTF/Runtime/UniGLTF/IO/ImporterContext.cs
ImporterContextのうち、BuildHierarchyまわりのフレームを分散しました
=> ImporterContextのうち、BuildHierarchyまわりのフレームを分散

Assets/UniGLTF/Runtime/MeshUtility/BoneMeshEraser.cs
スレッドアクセス違反
```
UnityException: get_canAccess can only be called from the main thread.
```
=> Can not access Mesh on thread

Assets/UniGLTF/Runtime/UniGLTF/IO/MeshIO/MeshImporter.cs
Profiler.Begin()/End()をMeshImporterに仕込みました
=> Profiler.Begin()/End()をMeshImporterに仕込んだ

Assets/VRM10/Runtime/Components/Expression/MaterialValueBindingMerger.cs, Assets/VRM10/Runtime/Components/Expression/Preview/PreviewSceneManager.cs, Assets/VRM10/Runtime/Components/Expression/PreviewMaterialItem.cs
https://github.com/vrm-c/vrm-specification/issues/279
Editor の Preview も追随。
修正前は、[0, 0, 1, 1] と設定との間でアニメーションしていた。
=> [1.0] preview の MaterialUVBindings 動作を修正

Assets/VRM10/Runtime/Components/VRM10Controller/VRM10Controller.cs
=> [1.0] DefaultExecutionOrder

Assets/UniGLTF/Editor/UniGLTF/ScriptedImporter/GltfScriptedImporterBase.cs, Assets/VRM10/Editor/ScriptedImporter/VrmScriptedImporter.cs
Shader.Find で null が返って Exception が throw されてしまう。
=> URP 未インストール時に、URPを選択できないように修正

Assets/VRMShaders/VRM10/MToon10/Resources/VRM10/vrmc_materials_mtoon_attribute.hlsl, Assets/VRMShaders/VRM10/MToon10/Resources/VRM10/vrmc_materials_mtoon_forward_fragment.hlsl, Assets/VRMShaders/VRM10/MToon10/Resources/VRM10/vrmc_materials_mtoon_forward_vertex.hlsl
MToon10 シェーダのフォグが動いていなかったので修正しました。
Fix #1211
=> Make MToon10's fog work.

Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/GltfUnlitMaterialImporter.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/MaterialExporter.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/MeshIO/VertexColorState.cs, Assets/VRM/Runtime/IO/VRMMaterialDescriptorGenerator.cs, Assets/VRM/Runtime/IO/VRMZWriteMaterialImporter.cs, Assets/VRM/Runtime/IO/VRMZWriteMaterialImporter.cs.meta, Assets/VRMShaders/GLTF/IO/Runtime/MaterialFactory.cs, Assets/VRMShaders/GLTF/UniUnlit/Editor/UniUnlitEditor.cs, Assets/VRMShaders/GLTF/UniUnlit/Runtime/UniUnlitUtil.cs, Assets/VRMShaders/GLTF/UniUnlit/Runtime/UniUnlitUtil.cs.meta, Assets/VRMShaders/GLTF/UniUnlit/Runtime/Utils.cs.meta
#1139
MToon へのフォールバック時に同じような見た目になるようにプロパティを書き換え。
主要な変更
* VRMMaterialDescriptorGenerator
* VRMZWriteMaterialImporter
ついで
* `UniUnilt.Utils` を `UniUnlit.UniUnlitUtil` に rename 。 ( using 時に `Utils` だと分かりづらいため )
* const UniUnlit.UniUnlitUtil.ShaderName を使うように修正
=> `VRM/UnlitTransparentZWrite` の Import を修正

Assets/UniGLTF/Runtime/UniGLTF/RuntimeGltfInstance.cs, Assets/VRM10/Runtime/Components/VRM10Object/VRM10ObjectFirstPerson.cs, Assets/VRM10/Samples/VRM10FirstPersonSample/VRM10RuntimeLoader.cs, Assets/VRMShaders/GLTF/IO/Runtime/IResponsibilityForDestroyObjects.cs, docs/implementation/runtime_resource_management.md, docs/index.md, docs/vrm1/vrm1_firstperson.md
#1242
* FirstPerson.SetupAsync の仕様を変更(中で AddRenderer する)
* SkinnedMeshRenderer.updateWhenOffscreen = true しない (あとで EnableUpdateWhenOffscreen )
* AddComponent 直後に SkinnedMeshRenderer.enabled = false
* AddRenderer のバグ修正 (_skinnedMeshRenderers に Add してなかった)
=> [1.0] FirstPerson.SetupAsync 修正

Assets/VRM10/Runtime/Components/VRM10Object/VRM10ObjectFirstPerson.cs
#1250 
要するに、自分以外の `VRM` に `FirstPersonOnly` フラグがあった場合に、その `Renderer` を非表示にする。
=> add self flag

Assets/UniGLTF/Runtime/UniGLTF/IO/ImporterContext.cs
=> lambda `Func<Task<AnimationClip>>` cause warning. Use Task.FromResult

Assets/VRM/Samples/SimpleViewer/ViewerUI.cs
=> Vrm と　それ以外の glb の処理分岐方法を変更

Assets/VRMShaders/VRM10/MToon10/Resources/VRM10/vrmc_materials_mtoon_forward_vertex.hlsl
OffsetScale 変換が、頂点シェーダとフラグメントシェーダの両方で行われてしまっていた。
=> [1.0] Fix MToon10 texture offset/scale bug.

Assets/UniGLTF/Runtime/MeshUtility/BoneNormalizer.cs, Assets/UniGLTF/Runtime/MeshUtility/MeshExtensions.cs
さもないと blendshape が壊れる
#1354
`vrm-0.88` `original fbx` `fixed`
blender由来の z-up mesh が起因で 行列に回転が入っていることでトリガーするかもしれない。
=> meshを正規化するときに、法線を正規化する

Assets/UniGLTF/Runtime/UniGLTF/IO/ImporterContext.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/MeshIO/MeshContext.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/MeshIO/MeshImporter.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/MeshIO/MeshVertex.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/MeshIO/MeshVertex.cs.meta, Assets/UniGLTF/Runtime/UniGLTF/IO/MeshIO/PrimitiveExtensions.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/MeshIO/PrimitiveExtensions.cs.meta
- Unity2019から追加されたNew Mesh APIを利用するように変更しました
- Meshのアップロードコストが大幅に削減できます（詳細は次の負荷計測の項に）
- Tangent周りのコードの維持が難しかったため削除
- 必要性があれば復元しますが、アプローチは相談したい
- エディタ上でのAlicia Solidの読み込み時間で計測
- BuildMeshのコストが2.79ms -> 0.79ms
- GC Allocも1300KB -> 2.6KB
=> New Mesh APIを利用することで、GPUへのMeshアップロードコストを削減

Assets/UniGLTF/Runtime/UniGLTF/IO/MeshIO/MeshVertex.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/SkinJoint.cs, Assets/VRM10/Runtime/IO/Model/CopyIndicesJob.cs, Assets/VRM10/Runtime/IO/Model/CopyIndicesJob.cs.meta, Assets/VRM10/Runtime/IO/Model/InterleaveMeshVerticesJob.cs, Assets/VRM10/Runtime/IO/Model/InterleaveMeshVerticesJob.cs.meta, Assets/VRM10/Runtime/IO/Model/MeshImporter.cs, Assets/VRM10/Runtime/IO/Model/MeshImporterDivided.cs, Assets/VRM10/Runtime/IO/Model/MeshVertex.cs, Assets/VRM10/Runtime/IO/Model/MeshVertex.cs.meta, Assets/VRM10/Runtime/VRM10.asmdef, Assets/VRM10/vrmlib/Runtime/BufferAccessor.cs, Assets/VRM10/vrmlib/Runtime/VrmLib.asmdef
VRM1.0についても https://github.com/vrm-c/UniVRM/pull/1373 と同様の対応を行うことで、情報をGPUのアップロードする際のコストを削減します
=> VRM1.0についてもNew Mesh APIを使う

Assets/VRM10/Editor/Components/Expression/ExpressionEditorHelper.cs, Assets/VRM10/Editor/Components/Expression/ReorderableMorphTargetBindingList.cs, Assets/VRM10/Editor/Components/Expression/SerializedExpressionEditor.cs, Assets/VRM10/Editor/EditorTool/VRM10ExpressionEditorTool.cs, Assets/VRM10/Runtime/Components/Expression/MorphTargetBinding.cs, Assets/VRM10/Runtime/Components/Expression/MorphTargetBindingMerger.cs, Assets/VRM10/Runtime/Components/Expression/Preview/PreviewMeshItem.cs, Assets/VRM10/Runtime/IO/ExpressionExtensions.cs, Assets/VRM10/Tests/SerializationTests.cs
#1380
シリアライズの値域が 0-1 なのに対して
SciptableObject の値域が 0-100 だった。
import/export 時に値域の操作が必用だった
SciptableObject の値域を 0-1 に修正。
* GetBlendShapeWeight 時に 0.01 倍する
* SetBlendShapeWeight 時に 100 倍する
* それ以外で操作しない
ように修正。
=> [1.0] ScriptableObject VRM10Expression の MorphTargetBinding.Weight の値域を 0-1 に修正

Assets/UniGLTF/Editor/UniGLTF/ExportDialog/MaterialValidator.cs
Standard でも Unlit でもない Material を含むモデルを GLTF エクスポートしようとすると・・・
=> 未知の material をエクスポートするとエラーになるのを回避

Assets/UniGLTF/Runtime/UniGLTF/IO/MeshIO/MeshContext.cs
https://github.com/vrm-c/UniVRM/issues/1393
MeshContext、colorsがnullだった場合の考慮漏れを修正しました
=> Colorsのnull考慮漏れを修正

Assets/UniGLTF/Runtime/UniGLTF/IO/MeshIO/MeshContext.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/MeshIO/MeshImporter.cs, Assets/VRM10/Runtime/IO/Model/MeshImporter.cs, Assets/VRM10/Runtime/IO/Model/MeshImporterDivided.cs
v0.89.1 および v0.90.0 で UniGLTF の MeshIO を使用するもので発生。
New Mesh API の対応によって発生していたと考えられる。
従来の Mesh API は `mesh.vertices` のセット時に、自動的に Bounds が計算されていた。
https://docs.unity3d.com/ja/2018.4/ScriptReference/Mesh-vertices.html
=> UniGLTF において、メッシュの Bounds が計算されていなかった問題を修正

Assets/VRM10/Runtime/Migration/Materials/MigrationMToonMaterial.cs, Assets/VRMShaders/VRM10/MToon10/Resources/VRM10/vrmc_materials_mtoon_define.hlsl, Assets/VRMShaders/VRM10/MToon10/Resources/VRM10/vrmc_materials_mtoon_geometry_vertex.hlsl, Assets/VRMShaders/VRM10/MToon10/Resources/VRM10/vrmc_materials_mtoon_utility.hlsl
VRM 0.x -> 1.0 のマイグレーション時にエラーがあったので修正。
マイグレーションと 1.0 の実装の双方が間違っていたので、得られる結果の見た目自体は変わらない。
具体的には、スクリーン座標系輪郭線の幅の変換が間違っていた。
従来の MToon 0.x の幅は、スクリーンの縦幅の半分を 100 としたときの値だった。
一方で MToon 1.0 の幅は、スクリーンの縦幅を 1 としたときの値となる。
したがってマイグレーション時には値を `1/200` 倍する必要がある。
しかし `1/100` 倍になっていた。
またスクリーン座標系輪郭線に関連して、VR などの高視野角カメラ環境においてスクリーン座標系輪郭線が太くなりすぎる問題があったので、仕様の範囲外でこれを抑制した。
これがうまくいくようなら、仕様にも提案したい。
=> Fix migration error in MToon & Modify Screen Coords Outline drawing algorithm.

Assets/VRMShaders/GLTF/IO/Editor/Texture/EditorTextureUtility.cs, Assets/VRMShaders/GLTF/IO/Editor/Texture/EditorTextureUtility.cs.meta, Assets/VRMShaders/GLTF/IO/Editor/Texture/Exporter/EditorTextureSerializer.cs, Assets/VRMShaders/GLTF/IO/Editor/Texture/Importer/TextureImporterConfigurator.cs
Editor Import 時に、2048 を超える Texture ファイルに対する MaxSize 指定がうまくいってなかったのを修正
この Issue を修正
https://github.com/vrm-c/UniVRM/issues/1379
=> While importing in Unity Editor, `Max Size` property is invalid if a texture size was larger than 2048.

Assets/UniGLTF/Runtime/UniGLTF/IO/TextureIO/GltfTextureExporter.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/gltfExporter.cs, Assets/VRM/Runtime/IO/VRMExporter.cs, Assets/VRMShaders/GLTF/IO/Editor/Texture/Exporter/EditorTextureSerializer.cs, Assets/VRMShaders/GLTF/IO/Runtime/Texture/Exporter/ITextureSerializer.cs, Assets/VRMShaders/GLTF/IO/Runtime/Texture/Exporter/RuntimeTextureSerializer.cs, Assets/VRMShaders/GLTF/IO/Runtime/Texture/Exporter/TextureExporter.cs
waiting merging https://github.com/vrm-c/UniVRM/pull/1402
fix https://github.com/vrm-c/UniVRM/issues/964
glTF や VRM のエクスポート時に、使用するテクスチャアセットの圧縮設定をオフにする。
これにより、ユーザが UniVRM を使用して VRM ファイルをエクスポートするときに、知らずにテクスチャ品質が悪化するのを防ぐ。
ただし Export するとアセットの圧縮設定がオフになったまま放置される。
その挙動がクリティカルに影響するユーザはかなり少ないと思うので、いったんはこう実装する。
エクスポート後に圧縮設定を復元する実装は、できればしたくない。
=> Ignore texture compression settings while exporting glTF / VRM.

Assets/UniGLTF/Runtime/UniGLTF/Format/ExtensionsAndExtras/KHR_texture_basisu.cs, Assets/UniGLTF/Runtime/UniGLTF/Format/ExtensionsAndExtras/KHR_texture_basisu.cs.meta, Assets/UniGLTF/Runtime/UniGLTF/Format/ExtensionsAndExtras/KHR_texture_transform.cs, Assets/UniGLTF/Runtime/UniGLTF/Format/glTFTexture.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/GltfData.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/GltfUnlitMaterialImporter.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/TextureIO/GltfPbrTextureImporter.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/TextureIO/GltfTextureImporter.cs, Assets/VRM/Runtime/IO/VRMImporterContext.cs, Assets/VRM/Runtime/IO/VRMMToonTextureImporter.cs, Assets/VRM/Runtime/IO/VrmTextureDescriptorGenerator.cs, Assets/VRM10/Runtime/IO/Texture/Vrm10MToonTextureImporter.cs, Assets/VRM10/Runtime/IO/Texture/Vrm10TextureDescriptorGenerator.cs, Assets/VRMShaders/GLTF/IO/Runtime/Texture/Importer/DeserializingTextureInfo.cs, Assets/VRMShaders/GLTF/IO/Runtime/Texture/Importer/TextureDescriptor.cs, Assets/VRMShaders/GLTF/IO/Runtime/Texture/Importer/TextureFactory.cs, Assets/VRMShaders/GLTF/IO/Runtime/Texture/Importer/UnityTextureDeserializer.cs
`KHR_texture_basisu` や `MSFT_texture_dds` といった、 glTF texture が参照する glTF image index を override する拡張の考慮を Runtime importer に導入します。
この対応によって `.ktx2` や `.dds` が実際に読み込めるようになるわけではありません。
=> Add the capability of importing texture extension.

Assets/VRM10/Editor/ScriptedImporter/VrmScriptedImporterEditorGUI.cs, Assets/VRM10/Runtime/IO/Vrm10Data.cs, Assets/VRM10/Runtime/Migration/MeshUpdater.cs, Assets/VRM10/vrmlib/Runtime/ModelExtensionsForCoordinates.cs, Assets/VRMShaders/GLTF/IO/Runtime/Util/Symbols.cs, Assets/VRMShaders/GLTF/IO/Runtime/Util/Symbols.cs.meta
glTFフォーマット上はもっと微妙なケースもあり得るのだけど、
Exporter の癖次第。
~本件は、 Blender のエクスポーターで稀に発生する様子。~
#1405 のmigration 時に発生してたー。
今後同様のケースが起こる場合は、バッファのコピーを前もって作る方法にする。
vrmlib の処理なので `vrm-1.0` のみがヒットする。
=> 同一のバイト列を参照するBufferAccessor が複数回、座標変換(右手・左手変換)されるのを回避する

Assets/VRMShaders/GLTF/IO/Runtime/Util/Symbols.cs
VRM_DEVELOP シンボル未定義時に unreachable code detected warning が出るのを抑制
=> Suppress compler warning `unreachable code detected warning` when `VRM_DEVELOP` symbol is undefined.

Assets/UniGLTF/Runtime/Extensions/ArrayExtensions.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/ArrayPin.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/BytesReader.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/GltfData.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/SafeMarshalCopy.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/SafeMarshalCopy.cs.meta, Assets/UniGLTF/Tests/UniGLTF/4x4_gray_import_as_linear.png.meta, Assets/UniGLTF/Tests/UniGLTF/4x4_gray_import_as_normal_map.png.meta, Assets/UniGLTF/Tests/UniGLTF/4x4_gray_import_as_srgb.png.meta, Assets/VRM10/Tests/MigrationTests.cs
* SafeMarshalCopy を作成
* ArrayByteBuffer.Extend を除いて、こちらを使うように修正した
* 呼び出し時に bufferView.byteStride = 0 で意図しない動作をする場合を修正した
=> Marshal.Copy で問題が発生する前に throw する

Assets/VRMShaders/GLTF/IO/Runtime/Texture/Exporter/TextureExportParam.cs
metallic roughness occlusion テクスチャの Export 時の修正。
旧来「metallic か occlusion どちらかのテクスチャが同じであれば同じとみなす」としていたコードを
「metallic も occlusion もどちらのテクスチャも同じであれば同じとみなす」とした。
テクスチャが増える場合はあるだろうが、厳密性を優先。
具体的には「Metallic テクスチャは存在するが、Occlusion テクスチャは存在しない」マテリアルが複数ある時に
`null == null` -> `true` となって、同じテクスチャを出力すればよい、と判定されてしまっていた。
=> Can export metallic roughness occlusion correct.

Assets/UniGLTF/Runtime/UniGLTF/IO/MeshIO/MeshContext.cs
MeshVertexのdefault colorをwhiteにしました
color bufferがnullだったときに白で描画されるようになり、一部状況で黒くなってしまうバグが修正されます
=> MeshVertexのdefault colorをwhiteにした

Assets/VRM10/Runtime/IO/Vrm10Importer.cs
* `float?` (Nullable<float>の省略記法) の項目
* float[] の項目
が無いときの挙動を修正
=> [1.0] SpringBone Joint のJSONキー省略時にデフォルト値を補う

Assets/VRM10/Runtime/IO/Vrm10Importer.cs
Collider 数が 0 の ColliderGroup で NullReferenceException が発生するのを修正
=> 空の collider group の null check

Assets/VRMShaders/GLTF/IO/Tests/MetallicRoughnessConverterTests.cs
https://github.com/vrm-c/UniVRM/pull/1437 の変更時に通らなくなったテストの修正。
いい加減、PR チェックでテストくらい走らせたい。
=> Fix the test of exporting Metallic-Rougness texture

Assets/UniGLTF/Runtime/UniJSON/ListTreeNode/ListTreeNodeObjectExtensions.cs, Assets/VRM10/Runtime/Migration/MigrationVector3.cs, Assets/VRM10/Runtime/Migration/MigrationVrmFirstPersonAndLookAt.cs, Assets/VRM10/Runtime/Migration/MigrationVrmMeta.cs
* meta: unknown key で throw せずに warning メッセージ表示に留める
* firstPersonBoneOffset: 無くても動くように修正
* KeyNotFoundException に key.ToString を追加
metaはデフォルト値が不許可に倒してあるので、読み取れなくても制限が緩くなることは無いのでよいということで。
=> [1.0] Migrationのエッジケースを修正

Assets/VRM10/Runtime/IO/Vrm10Exporter.cs
#1500 のついでに
springBone拡張ですが、colliderやspringsがない場合においても空の拡張がエクスポートされていたため、（特に仕様的に問題はない挙動ではありますが）これをエクスポートしないように変更しました。
=> [1.0] don't export the springBone extension if there are no colliders and springs

Assets/VRM10/Editor/Components/Constraint/VRM10PostionRotationConstraintEditorBase.cs, Assets/VRM10/Runtime/Components/Constraint/ConstraintAxes.cs, Assets/VRM10/Runtime/Components/Constraint/VRM10RotationConstraint.cs, Assets/VRM10/Runtime/Components/Constraint/VRM10RotationPositionConstraintBase.cs, Assets/VRM10/Runtime/Format/Constraints/Deserializer.g.cs, Assets/VRM10/Runtime/Format/Constraints/Format.g.cs, Assets/VRM10/Runtime/Format/Constraints/Serializer.g.cs, Assets/VRM10/Runtime/IO/Vrm10Exporter.cs, Assets/VRM10/Runtime/IO/Vrm10Importer.cs
WIll close #1490 
[仕様のほうのPR](https://github.com/vrm-c/vrm-specification/pull/352) に基づき、こちらも `freezeAxes` を `axes` に変更しました。
- 仕様側がマージされたので更新しました
=> [1.0] Constraint, freezeAxes -> axes

Assets/UniGLTF/Runtime/UniGLTF/IO/MeshIO/MeshExportUtil.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/MeshIO/MeshExporter_SharedVertexBuffer.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/MeshIO/PositionMinMax.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/MeshIO/PositionMinMax.cs.meta
SHARED vertex buffer(vrm-0.x と glb) 方式は実装済み。
glb と vrm-1.0 が使う Divided vertex buffer の方に無かった。
#1492
https://www.khronos.org/registry/glTF/specs/2.0/glTF-2.0.html#accessors-bounds
> Animation input and vertex position attribute accessors MUST have accessor.min and accessor.max defined. For all other accessors, these properties are optional.
いつの間に・・・
=> POSITION の Accessor に min, max を追加

Assets/VRM10/Editor/Vrm10InstanceEditor.cs, Assets/VRM10/Editor/Vrm10InstanceEditor.cs.meta
シーンから AddComponent を起点にセットアップできるボタンを作りました。
#1491
=> add custom editor

Assets/VRM/Runtime/SpringBone/VRMSpringBone.cs
#1508
* 表示非表示の bool を廃止
* OnDrawGizmosSelected に変更
* `!Application.isPlaying` 時の Gizmo を追加
=> [SpringBone]非Play時にもSpringのGizmoを表示する

Assets/UniGLTF/Runtime/UniGLTF/IO/gltfExporter.cs, Assets/VRM/Runtime/IO/VRMExporter.cs
#1522
`virtual void gltfExporter.ExportAnimations()` を切り出した。
=> VRM は Animation をエクスポートしない

Assets/UniGLTF/Runtime/MeshUtility/BoneMeshEraser.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/ImporterContext.cs, Assets/VRM/Editor/Format/VRMEditorImporterContext.cs, Assets/VRM/Runtime/IO/VRMImporterContext.cs, Assets/VRM/Runtime/IO/VrmUtility.cs, Assets/VRM10/Runtime/Components/VRM10Object/VRM10ObjectFirstPerson.cs, Assets/VRM10/Runtime/IO/Vrm10.cs, Assets/VRM10/Runtime/IO/Vrm10Importer.cs, Assets/VRM_Samples/FirstPersonSample/VRMRuntimeLoader.cs
#1216
引き数 `IAwaitCaller = null` で受けて、
```cs
if (awaitCaller == null)
{
awaitCaller = new ImmediateCaller();
}
```
としているところをデフォルト引数をやめて、明示的に引数を渡すように変更。
```cs
throw new ArgumentNullException();
```
とした。
=> remove `awaitCaller ?? new ImmediateCaller()`

Assets/UniGLTF/Editor/EditorSettingsValidator/UnityColorSpaceSettingsValidator.cs, Assets/UniGLTF/Editor/EditorSettingsValidator/UnityEditorSettingsValidatorWindow.cs
#1559
C# シンボル `UNIGLTF_USE_GAMMA_COLORSPACE ` を定義すると、x で閉じると復活しない。
1. シンボルを定義する。Unity 終了(シンボル設定が保存されるように)
2. 設定を Gamma に変える。ダイアログを閉じると復活しません
=> UNIGLTF_USE_GAMMA_COLORSPACE

Assets/UniGLTF/Runtime/UniGLTF/IO/MeshIO/MeshContext.cs
主に VRM-0.X の Mesh import で発生(ImportMeshSharingVertexBuffer)
vrm-1.0 は別の経路(ImportMeshIndependentVertexBuffer)を通るので起きない。
UniVRM で作った glb はどっちもありうる？
=> blendshape が無になるバグ

Assets/VRMShaders/VRM10/MToon10/Resources/VRM10/vrmc_materials_mtoon_input.hlsl
Questなどの一部端末で、一定時間経過後にMToonのテクスチャスクロールがカクカクする問題を修正しました
=> Questなどの一部端末で、一定時間経過後にMToonのテクスチャスクロールがカクカクする問題を修正

Assets/VRM10/Runtime/Migration/MigrationVrmFirstPersonAndLookAt.cs
`throw new NotImplementedException("mesh is not used");`
に到達するモデルでマイグレーションが失敗していました。
このようなモデルは、VRM ファイルを入力に改造した VRM ファイルなどにおいて
Renderer の数が増減しているにもかかわらず FirstPerson の設定を変更し忘れていた場合に
過去の UniVRM で出力しえたようです。
またこのマイグレーションにおいて null アクセスがありえた部分をすべて TryGet に直しました。
=> Fix a error in migrating FirstPerson.

Assets/UniGLTF/Runtime/UniGLTF/IO/GltfExportSettings.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/MeshIO/MeshExportInfo.cs
As described in issue https://github.com/vrm-c/UniVRM/issues/1582 I added an export setting that allows for MeshFilters with HideFlags to be also be catalogued for the runtime export.
It does not change anything if not specifically set in ExportSettings, as the standard value for the setting keeps the status quo as is.
This also enables the use of ProBuilderMeshes.
=> Added ExportSetting to allow HideFlags ins MeshFilters

Assets/UniGLTF/package.json, Assets/VRM/package.json, Assets/VRMShaders/package.json
以下のパッケージでUnity公式モジュールの依存関係が不足していたので追加しました。
* UniGLTF
* VRM
* VRMShaders
リポジトリ直下にプロジェクトを作成して、manifest.jsonを以下のように設定します。
``` json
{
"dependencies": {
"com.vrmc.gltf": "file:../../Assets/UniGLTF",
"com.vrmc.univrm": "file:../../Assets/VRM",
"com.vrmc.vrm": "file:../../Assets/VRM10",
"com.vrmc.vrmshaders": "file:../../Assets/VRMShaders"
}
}
```
この状態でプロジェクトを開くと次のようなエラーが出ます
com.unity.modules.animationに依存している箇所のエラーの例
```
C:\Users\mkc1370\src\UniVRM\Assets\UniGLTF\Runtime\UniHumanoid\AnimationClipUtility.cs(53,70): error CS1069: The type name 'HumanPose' could not be found in the namespace 'UnityEngine'. This type has been forwarded to assembly 'UnityEngine.AnimationModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' Enable the built in package 'Animation' in the Package Manager window …
```
=> Unity公式モジュールの依存関係が不足している問題を修正

Assets/VRM10/Runtime/IO/Vrm10Data.cs, Assets/VRM10/Runtime/Migration/MigrationVrmMeta.cs
* Migration 中発生したエラーを catch して message 表示(Editor)
* otherLicenseUrl と otherPermissionUrl 両方を記述しエラーにしない対応
=> [1.0] migration のエラーハンドリングを修正

Assets/UniGLTF/Runtime/MeshUtility/BoneNormalizer.cs
#1592
例えば、エクスポート対象ヒエラルキーの外部の GameObject が rootBone セットされている
=> シーン構成によっては、稀にエラーになるっぽい？

Assets/VRM10/Runtime/Components/Constraint/Vrm10AimConstraint.cs, Assets/VRM10/Runtime/Components/Constraint/Vrm10RollConstraint.cs, Assets/VRM10/Runtime/Components/Constraint/Vrm10RotationConstraint.cs
改めて、コンストレイント対応ありがとうございました！
現状、仕様ではweightの最大値は1.0となっているので、UI上もこれに従うのが良いと思います。
See: https://github.com/vrm-c/vrm-specification/blob/master/specification/VRMC_node_constraint-1.0_draft/README.ja.md#weight
=> change (1.0, constraint): Change max range of weights to 1.0

Assets/VRM10/Runtime/Components/SpringBone/VRM10SpringBoneCollider.cs, Assets/VRM10/Runtime/Components/Vrm10Instance/Vrm10Instance.cs
OnDrawGizmosではなくOnDrawGizmosSelectedを利用する
SpringBoneのGizmoの負荷は高く、全てのオブジェクトのGizmoを常に出しておく必要性もないため
=> OnDrawGizmosではなくOnDrawGizmosSelectedを利用する

Assets/UniGLTF/Editor/EditorSettingsValidator/UnityEditorSettingsValidatorWindow.cs
Because WebGL not support Liner Color Space.
Execute Liner check will block build on WebGL Platform
[colorspaceをgammaに設定するとLinearに設定変更を促すダイアログが表示され閉じることができなくなる ](https://github.com/vrm-c/UniVRM/issues/1559)
=> Disable WebGl color space check

Assets/UniGLTF/Runtime/UniGLTF/IO/ImporterContext.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/MeshIO/PrimitiveExtensions.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/SByte4.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/SByte4.cs.meta, Assets/UniGLTF/Runtime/UniGLTF/IO/UShort2.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/UShort2.cs.meta
`KHR_mesh_quantization` の最低限の実装。
<https://github.com/KhronosGroup/glTF/blob/main/extensions/2.0/Khronos/KHR_mesh_quantization/README.md>
単に、格納する型が増えるだけで済むようになっているぽい。
* Position: USHORT3(4byte alignment)
* Normal: SByte3(4byte alignment)
* UV: USHORT2
を実装した。
#1558 
https://meshoptimizer.org/gltf/
で作れるぽい。
=> Initial support for KHR_mesh_quantization

Assets/VRMShaders/GLTF/IO/Editor/Texture/Exporter/EditorTextureSerializer.cs
#1583 
`ArgumentOutOfRangeException` よりはましに。
=> error message

Assets/VRM10/Runtime/Components/Expression/MaterialValueBindingMerger.cs, Assets/VRM10/Runtime/IO/Vrm10Data.cs, Assets/VRM10/Runtime/Migration/MigrationVrmExpression.cs
VRM 0.x -> VRM 1.0 の Migration 時、UV Scale/Offset の Expression 値が多重に登録されてしまうバグを修正。
仕様により、TextureTransformBind は事実上、Material に対してただ一つのみしか存在しない。
https://github.com/vrm-c/vrm-specification/blob/master/specification/VRMC_vrm-1.0-beta/expressions.ja.md#texturetransformbind
=> Ignore duplicated UV expression in migration.

Assets/UniGLTF/Runtime/UniGLTF/Format/ExtensionsAndExtras/KHR_materials_emissive_strength.cs, Assets/UniGLTF/Runtime/UniGLTF/Format/ExtensionsAndExtras/KHR_materials_emissive_strength.cs.meta, Assets/UniGLTF/Runtime/UniGLTF/Format/ExtensionsAndExtras/KHR_materials_unlit.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/GltfExportSettings.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/GltfPbrMaterialImporter.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/MaterialExporter.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/URP/GltfPbrURPMaterialImporter.cs, Assets/UniGLTF/Tests/UniGLTF/MaterialTests.cs
https://github.com/KhronosGroup/glTF/tree/main/extensions/2.0/Khronos/KHR_materials_emissive_strength
の実装です。
=> KHR_materials_emissive_strength を実装

Assets/VRM10/Runtime/Components/Vrm10Instance/Vrm10Instance.cs, Assets/VRM10/Runtime/Components/Vrm10Instance/Vrm10InstanceSpringBone.cs, Assets/VRM10/Runtime/Components/Vrm10Runtime/Vrm10Runtime.cs, Assets/VRM10/Runtime/Format/SpringBone/Deserializer.g.cs, Assets/VRM10/Runtime/Format/SpringBone/Format.g.cs, Assets/VRM10/Runtime/Format/SpringBone/Serializer.g.cs, Assets/VRM10/Runtime/IO/Vrm10Exporter.cs, Assets/VRM10/Runtime/IO/Vrm10Importer.cs
https://github.com/vrm-c/vrm-specification/pull/374
=> [1.0] SpringBone.center 復活

Assets/VRM10/Runtime/FastSpringBone/System/FastSpringBoneBufferCombiner.cs
SpringBoneを持たないVRMをインポートすると `NativeArray<BlittableLogic> Logics` の長さが0の `FastSpringBoneBuffer` が `FastSpringBoneBufferCombiner.Register()` に渡されており、この状態で `FastSpringBoneBufferCombiner.SaveToSourceBuffer()` を実行すると `ArgumentOutOfRangeException` が発生する場合があったため、この問題を修正しました。
=> FastSpringBoneBufferCombinerでArgumentOutOfRangeExceptionしうる問題を修正

Assets/UniGLTF/Runtime/UniGLTF/IO/GltfData.cs
警告 `Texture image MIME type `{textureInfo.DataMimeType}` is not supported.` の防止。
https://www.khronos.org/registry/glTF/specs/2.0/glTF-2.0.html#images
glb のときは mime を省略不可。
> a reference to a bufferView; in that case mimeType MUST be defined.
=> image.uri から mime を決定する

Assets/VRM/Runtime/IO/VRMMToonMaterialImporter.cs, Assets/VRMShaders/GLTF/IO/Runtime/Material/Importer/MaterialFactory.cs
Unity-2021 では SetVector により offset, scale をセットするとエラー Property PROP_NAME already exists in the property sheet with a different type: 5 が発生する。
#1680 では Unity-2020 で発生とのことで、どのバージョンから発生するか詳細は不明。
Unity-2019 では発生していない。
=> fix Property PROP_NAME already exists in the property sheet with a different type: 5

Assets/UniGLTF/Editor/MeshUtility/TabMeshSeparator.cs, Assets/UniGLTF/Runtime/UniGLTF/UniGLTFVersion.cs, Assets/UniGLTF/package.json, Assets/VRM/Runtime/Format/VRMVersion.cs, Assets/VRM/Samples~/BlendShapeMenu/BlendShapeMenu.cs, Assets/VRM/package.json, Assets/VRM10/package.json, Assets/VRMShaders/package.json
`v0.100` から最低バージョンを `Unity-2020` にするので、マイナーバージョンにします。
=> MeshUtility.SeparationProcessing を public にする

Assets/UniGLTF/Editor/UniGLTF/ScriptedImporter/GlbScriptedImporter.cs, Assets/UniGLTF/Editor/UniGLTF/ScriptedImporter/GltfScriptedImporter.cs
* 新規の glb/gltf を asset に投入したときに、importer が発動しなくなっていた
=> ScriptedImporterAttribute.overrideExts の使い方が間違っていた

Assets/UniGLTF/Runtime/MeshUtility/MeshIntegrator.cs
#1717
Unity 上では，マテリアルがセットされていない時（ピンク色の表示）と異なり，マテリアルが指定されなくなった部分のポリゴン（サブメッシュ）が Unity 上で描画されないため，マテリアルの数が足りていない部分は描画をしないようにしました．
=> Fix MeshIntegratorWizard cannot run with insufficient materials for submeshes

Assets/VRM10/Runtime/Components/Vrm10Runtime/Vrm10Runtime.cs, Assets/VRM10/Runtime/FastSpringBone/InputPorts/FastSpringBoneBuffer.cs, Assets/VRM10/Runtime/FastSpringBone/InputPorts/FastSpringBoneJoint.cs
`Vrm10Runtime.ReconstructSpringBone()` を呼ぶと、呼んだ時点のSpringBoneの変形した形状を維持する方向に剛性が働くようになってしまう問題を修正しました。
=> SpringBoneの剛性が意図しない方向に働くことがある問題を修正

Assets/VRM10/Runtime/Components/Vrm10Instance/Vrm10Instance.cs, Assets/VRM10/Runtime/Components/Vrm10Runtime/Vrm10Runtime.cs, Assets/VRM10/Runtime/Components/Vrm10Runtime/Vrm10RuntimeLookAt.cs, Assets/VRM10/Runtime/Format/Vrm/Deserializer.g.cs, Assets/VRM10/Runtime/Format/Vrm/Format.g.cs, Assets/VRM10/Runtime/Format/Vrm/Serializer.g.cs, Assets/VRM10/Runtime/IO/Model/ModelExporter.cs, Assets/VRM10/Runtime/IO/Vrm10Exporter.cs, Assets/VRM10/Runtime/IO/Vrm10Importer.cs, Assets/VRM10/Runtime/Migration/MigrationCheck.cs, Assets/VRM10/Runtime/Migration/MigrationVrmHumanoid.cs, Assets/VRM10/vrmlib/Runtime/Humanoid/Humanoid.cs, Assets/VRM10/vrmlib/Runtime/Humanoid/HumanoidBones.cs
https://github.com/vrm-c/vrm-specification/issues/380 に追随
Unity では proximal, intermediate, distal であることに注意。
import / export での変換(Enum.Parse)を修正。
=> [1.0] 親指のボーン名を metacarpal, proximal, distal に変更

Assets/VRM10/Runtime/IO/Model/MeshImporterDivided.cs
fixed #1692 
position 以外の頂点属性は nullable であることに対応
=> Other than position is nullable

Assets/UniGLTF/Editor/Animation/EditorAnimationExporter.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/ImporterContext.cs, Assets/VRM/Editor/Format/VRMEditorExporter.cs, Assets/VRM/Editor/Format/VRMEditorImporterContext.cs, Assets/VRM/Editor/Format/VRMExportOptions.cs, Assets/VRM/Editor/Format/VRMExportSettings.cs, Assets/VRM/Editor/Format/VRMExportSettingsEditor.cs, Assets/VRM/Editor/Format/VRMExporterWizard.cs, Assets/VRM/Editor/Format/vrmAssetPostprocessor.cs, Assets/VRM/Runtime/IO/VRMExporter.cs, Assets/VRM/Runtime/IO/VRMImporterContext.cs, Assets/VRM/Runtime/IO/VrmUtility.cs, Assets/VRM_Samples/SimpleViewer/SimpleViewer.unity, Assets/VRM_Samples/SimpleViewer/ViewerUI.cs
#1682
関連 #1522
* VRM は Animation を仕様に含めない
=> 未知の VRM をロードしたアプリケーションは、たとえ Animation が含まれていても用途が分からないであろう
=> エクスポートするの止めた #1522
* 自分でやっているので既知です #1682 
=> 自分用に glb のアニメーションを含められるように変更
以下のように UniVRM の動作を整理します。
|                | 新デフォルト    |コメント                                    | 既存の動作                                                 |
|----------------|---------------|------------------------------------|------------------------------------------------------------|
| editor export  | export しない | オプション指定でエクスポートできる | v0.96でエクスポートしなくなった                            |
| editor import  | import する   |                                    | インポートが動作してなかった(使わないので気にしてなかった) |
| runtime import | import しない | オプション指定でインポートできる   | Importされる                                               |
glb/glTF …
=> vrm の gltf Animation の読み書き仕様

Assets/VRM/Runtime/BlendShape/VRMBlendShapeProxy.cs
=> runtime に BlendShapeProxy.m_merger を再初期化する

Assets/UniGLTF/Editor/UniGLTF/Serialization/FieldSerializationInfo.cs, Assets/UniGLTF/Editor/UniGLTF/Serialization/NullableSerialization.cs, Assets/UniGLTF/Editor/UniGLTF/Serialization/NullableSerialization.cs.meta, Assets/UniGLTF/Runtime/UniGLTF/Format/GltfSerializer.g.cs, Assets/UniGLTF/Runtime/UniGLTF/Format/glTFBuffer.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/ExportingGltfData.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/GltfData.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/GltfJsonUtil.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/MeshIO/BlendShapeExporter.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/gltfExporter.cs, Assets/UniGLTF/Tests/UniGLTF/GltfJsonUtilTests.cs, Assets/VRM10/Runtime/IO/IndexExtensions.cs, Assets/VRM10/Runtime/IO/Vrm10ImportData.cs, Assets/VRM10/Runtime/Migration/MeshUpdater.cs, Assets/VRM10/Runtime/Migration/RotateY180.cs, Assets/VRM10/Tests/MigrationTests.cs, Assets/VRMShaders/GLTF/IO/Editor/PathObject.cs
Exporter の gltf_validator にヒットする問題を修正しました。
* [bug] extensionsUsed の typo (extensionUsed)
* シリアライザーの Nullable<int> 対応
* Nullable<int> を使った sparse accessor に対する byteOffset を 無にする修正
* morphTarget.position に対する min, max
など。
=> [exporter] fix for gltf_validator

Assets/VRM10/Runtime/IO/Material/Vrm10MToonMaterialExporter.cs
Fix glTF validator's error.
Consider KHR_materials_emissive_strength extension while exporting mtoon material as vrm-1.0.
=> Consider KHR_materials_emissive_strength extension while exporting mtoon material as vrm-1.0

Assets/UniGLTF/Runtime/UniGLTF/Format/ExtensionsAndExtras/gltf_mesh_extras_targetNames.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/BlendShapeTargetNameLocationFlags.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/BlendShapeTargetNameLocationFlags.cs.meta, Assets/UniGLTF/Runtime/UniGLTF/IO/MeshIO/MeshExporter_DividedVertexBuffer.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/MeshIO/MeshExporter_SharedVertexBuffer.cs, Assets/VRM10/Runtime/IO/Model/MeshWriter.cs
targetName
下記参照のこと。
https://www.khronos.org/registry/glTF/specs/2.0/glTF-2.0.html#meshes
> A significant number of authoring and client implementations associate names with morph targets. While the glTF 2.0 specification currently does not provide a way to specify names, most tools use an array of strings, mesh.extras.targetNames, for this purpose. The targetNames array and all primitive targets arrays must have the same length.
歴史的事情により、当初 primitive.extras.targetNames を使っていた。
https://github.com/KhronosGroup/glTF/issues/1036
=> [1.0] VRM-1.0 の targetNames を Mesh.extras のみに修正

Assets/VRM/Editor/BlendShape/VRMBlendShapeProxyValidator.cs, Assets/VRM/Runtime/IO/VRMExporter.cs
fixed #1709
Clips はスクリプトにより生成されることが多いのでその時は発生しない。
別の手順で操作したときには起こり得る。
=> [exporter] BlendShapeClip の null check

Assets/VRM10/Runtime/Components/Expression/DefaultExpressionValidator.cs
* Override 設定をもとに Blink, LookAt, Mouth の weight を算出する際に、isBinary の設定が反映された後の actualWeight でなく inputWeight が使われていた
* そのため、Blink/LookAt/Mouth の isBinary が true であっても中間の値が適用されていた
=> [VRM 1.0] プロシージャルな Expression に isBinary の設定が反映されていなかったバグを修正

Assets/UniGLTF/Runtime/MeshUtility/MeshIntegrator.cs
=> arrays size must match mesh vertex count

Assets/VRM/Editor/BlendShape/BlendShapeClipSelector.cs, Assets/VRM/Editor/BlendShape/VRMBlendShapeProxyValidator.cs, Assets/VRM/Editor/Format/VRMBlendShapeExportFilter.cs, Assets/VRM/Editor/Format/VRMEditorExporter.cs, Assets/VRM/Editor/Format/VRMExporterWizard.cs, Assets/VRM/Runtime/BlendShape/BlendShapeAvatar.cs, Assets/VRM/Tests/SampleTests/VRMImportExportTests.cs, Assets/VRM_Samples/BlendShapeMenu/BlendShapeMenu.cs
BlendShapeClipのファイルが削除された後に表情の変更やVRMのエクスポートをしようとするとエラーが発生します。
これは、BlendShapeVatar.Clips内の削除したBlendShapeClipがnullになるためです。
1. VRMファイルを読み込む
2. 作成されたPrefabをScene上に配置
3. 1個以上のBlendShapeClipのアセットファイルを削除
4. 2.で作成したGameObjectにAIUEOをアタッチ
5. Playする
エラー抜粋
```
NullReferenceException: Object reference not set to an instance of an object
VRM.BlendShapeKey.GetHashCode () (at Assets/VRM/Runtime/BlendShape/BlendShapeKey.cs:128)
```
<details>
<summary>エラー全文</summary>
```
NullReferenceException: Object reference not set to an instance of an object
VRM.BlendShapeKey.GetHashCode () (at Assets/VRM/Runtime/BlendShape/BlendShapeKey.cs:128)
System.Collections.Generic.GenericEqualityComparer`1[T].GetHashCode (T obj) (at <695d1cc93cca45069c528c15c9fdd749>:0) …
```
=> BlendShapeClipが削除された後に様々な場所でエラーが出る問題を修正

Assets/UniGLTF/Runtime/UniGLTF/IO/MeshIO/MeshUploader.cs
`Profiler.BeginSample` ～ `Profiler.EndSample` が 1 frame で終わらないと Unity から以下のようなエラーメッセージが出るため、該当箇所を削除。
```
Non-matching Profiler.EndSample (Every EndSample call must have a preceding BeginSample call within the same frame): 
```
=> Remove multi-frame profiler sample

Assets/UniGLTF/Runtime/UniGLTF/IO/GltfUtility.cs, Assets/VRM/Runtime/IO/VrmUtility.cs, Assets/VRMShaders/GLTF/IO/Runtime/AwaitCaller/RuntimeOnlyNoThreadAwaitCaller.cs, Assets/VRMShaders/GLTF/IO/Runtime/AwaitCaller/RuntimeOnlyNoThreadAwaitCaller.cs.meta, Assets/VRM_Samples/SimpleViewer/Plugins.meta, Assets/VRM_Samples/SimpleViewer/Plugins/OpenFile.jslib, Assets/VRM_Samples/SimpleViewer/Plugins/OpenFile.jslib.meta, Assets/VRM_Samples/SimpleViewer/ViewerUI.cs
VRM_Samples/SimpleViewer を WebGL ビルドする環境
* GltfUtility.LoadAsync の byte[] 引数
* VrmUtility.LoadAsync の byte[] 引数
あたりどうするか。
* RuntimeOnlyNoThreadAwaitCaller は動作確認できました。本物の Thread が無いのでそれなりの効果
あと、 colorspace gamma が要求されるので色の再現性には目を瞑る。
=> WebGLの動作確認

Assets/UniGLTF/Runtime/UniGLTF/Format/GltfSerializer.g.cs, Assets/UniGLTF/Runtime/UniGLTF/Format/glTFTexture.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/GltfPbrMaterialImporter.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/GltfUnlitMaterialImporter.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/URP/GltfPbrURPMaterialImporter.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/Parser/GlbLowLevelParser.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/TextureIO/GltfPbrTextureImporter.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/TextureIO/GltfTextureImporter.cs, Assets/VRM/Runtime/IO/VRMImporterContext.cs, Assets/VRM/Runtime/IO/VRMMToonMaterialImporter.cs, Assets/VRM/Runtime/IO/VRMMToonTextureImporter.cs, Assets/VRM/Runtime/IO/VRMUnlitTransparentZWriteMaterialImporter.cs, Assets/VRM/Runtime/IO/VrmTextureDescriptorGenerator.cs, Assets/VRM10/Runtime/IO/Texture/Vrm10MToonTextureImporter.cs, Assets/VRMShaders/GLTF/IO/Runtime/SubAssetKey.cs, Assets/VRMShaders/GLTF/IO/Runtime/Texture/Importer/TextureDescriptor.cs
=> glTFTexture.source type to int?

Assets/VRM10/Editor/ScriptedImporter/VrmScriptedImporter.cs, Assets/VRM10/Editor/ScriptedImporter/VrmScriptedImporterEditorGUI.cs, Assets/VRM10/Editor/ScriptedImporter/VrmScriptedImporterImpl.cs, Assets/VRM10/Runtime/IO/Vrm10.cs, Assets/VRM10/Runtime/IO/Vrm10Importer.cs, Assets/VRM10/vrmlib/Runtime/Model.cs, Assets/VRM10_Samples/VRM10Viewer/VRM10Viewer.unity, Assets/VRM10_Samples/VRM10Viewer/VRM10ViewerUI.cs
これは API Breaking Change です。
VRM 1.0 importer の `doNormalize` オプションを除去します。
以下の理由が挙げられます。
- normalize を正常に動かし続けるには保守コストが大きい
- VRM 1.0 の SpringBone や Constraint 設定は、node transform の状態に依存したプロパティが多く存在するため
- ControlRig 機能の導入により normalize の意義が薄れたため
=> Remove the VRM 1.0 importer option about the normalization of node transforms.

Assets/VRM10/Runtime/Components/Vrm10Instance/Vrm10Instance.cs, Assets/VRM10/Runtime/Components/Vrm10Runtime/Vrm10Runtime.cs, Assets/VRM10/Runtime/Components/Vrm10Runtime/Vrm10RuntimeControlRig.cs, Assets/VRM10/Runtime/IO/Vrm10.cs, Assets/VRM10/Runtime/IO/Vrm10Importer.cs, Assets/VRM10/Tests/ExpressionTests.cs, Assets/VRM10_Samples/VRM10Viewer/VRM10ViewerUI.cs
API Breaking Change です。
Control Rig を生成するオプションが VRM 1.0 Importer に `generateControlRig` として追加されます。
Control Rig は `Vrm10RuntimeControlRig` として実装されます。
Control Rig は、すべてのボーンの `localRotation` が `Quaternion.identity` であるとき、VRM の T-Pose になるリグです。
Control Rig は、その姿勢を VRM モデルのボーンに Vrm10Runtime の指定されたタイミングで適用します。
Control Rig は、VRM モデルのインスタンス Root の子に生成されます。
Control Rig は、VRM モデルの `Animator` とは別に、独自の `Animator` を生成します。
=> Add the `GenerateControlRig` option to VRM 1.0 Importer.

Assets/VRMShaders/GLTF/IO/Runtime/AwaitCaller/IAwaitCaller.cs, Assets/VRMShaders/GLTF/IO/Runtime/AwaitCaller/ImmediateCaller.cs, Assets/VRMShaders/GLTF/IO/Runtime/AwaitCaller/RuntimeOnlyAwaitCaller.cs, Assets/VRMShaders/GLTF/IO/Runtime/AwaitCaller/RuntimeOnlyNoThreadAwaitCaller.cs
edit : IAwaitCallerに正規のインターフェスとしてNextFrameIfTimedOutを追加する形式に修正
アプリ内でRuntimeOnlyAwaitCallerを使用する際、UniVRMによるVRMファイルロード時のメインスレッドCPU処理スパイク (一時的な処理量の増加) を積極的に軽減したい場合があります。
UniVRMには既に `RuntimeOnlyAwaitCaller.NextFrame()` によるスパイク軽減が実装されていますが、処理量によらず常に次のフレームを待つため、処理時間および待ち時間の粒度が大きく異なる傾向があります。
この点を改善するため、この変更では `RuntimeOnlyAwaitCaller.NextFrameIfTimedOut()` という疑似メソッドを追加し、一定時間経過した場合のみ `NextFrame()` を自動的に呼び出せるようにします。
この変更内には、実際にこの疑似メソッドを呼び出す部分はありませんが、例えば以下のようなコードのループ内への追加を行うことで、CPU処理量の大きな変動の抑制が可能になります。
```c#
public class VRMImporterContext : ImporterContext {
protected override async Task OnLoadHierarchy(IAwaitCaller awaitCaller, ...) {
...
var blendShapeList = VRM.blendShapeMaster.blendShapeGroups;
if (blendShapeList != null && blendShapeList.Count > 0) {
foreach (var x in blendShapeList) {
await …
```
=> BREAKING CHANGE: Add interface method IAwaitCaller.NextFrameIfTimedOut which invokes NextFrame if timed out

Assets/VRM_Samples/SimpleViewer/ViewerUI.cs
https://github.com/vrm-c/UniVRM/pull/1756#issuecomment-1221776178
の修正で null 引数を受けなくなっていたのに追随。
`async void LoadModelAsync(string path, byte[] bytes = null)`
👇
`async void LoadModelAsync(string path, byte[] bytes)`
=> add LoadPathAsync

docs/index.html, docs/release/079/v0.103.0.md, docs/release_gen.py
=> release UniVRM-0.103.0

Assets/VRM10/Runtime/Components/Constraint/Vrm10AimConstraint.cs, Assets/VRM10/Runtime/Components/Constraint/Vrm10RollConstraint.cs, Assets/VRM10/Runtime/Components/Constraint/Vrm10RotationConstraint.cs, Assets/VRM10/Runtime/IO/Vrm10Exporter.cs, Assets/VRM10/Runtime/IO/Vrm10Importer.cs
- Vrm10Exporterから出てくるMToon拡張のspecVersionがまだ `1.0-draft` だったので、これを `1.0-beta` に修正しました。
- ついでに、ソースコード内コンストレイント仕様へのリンクを適切に修正しました。
=> Fix specVersion of MToon `1.0-draft` -> `1.0-beta`

Assets/VRM10/Runtime/Migration/Materials/MigrationMToonMaterial.cs, Assets/VRM10/Runtime/Migration/MigrationVrm.cs, Assets/VRM10/Runtime/Migration/MigrationVrmMeta.cs, Assets/VRM10/Runtime/Migration/MigrationVrmSpringBone.cs
`MigrationVrm` から出力されたVRMが仕様に適合しないので、これを仕様に適合する形に更新します。
- `specVersion` が抜けていたのを修正しました。
- `licenseUrl` が抜けていたのを修正しました。
- `extensionsUsed` の不整合を修正しました。
=> Fix VRM exported from MigrationVrm class

Assets/VRM10/Runtime/Migration/Materials/MigrationMToonMaterial.cs
Sequel of #1787
先のPRについて、追加で `KHR_texture_transform` を `extensionUsed` に追加する必要があったので、これを追加しました。
=> Fix VRM exported from MigrationVrm class (2)

Assets/VRM10/Runtime/Components/Vrm10Runtime/Vrm10Runtime.cs
ControlRig は nullable だがそれを考慮できていない。
ControlRig は初期状態として T ポーズであることを要求するが、それを担保できるのは現状 Rutime Load だけ。
したがって Editor で Prefab 配置した場合は現状 ControlRig は生成できない。
=> Fix bug of null access when loading vrm1.0 prefab placed in the scene.

Assets/UniGLTF/Runtime/UniHumanoid/AvatarDescription.cs
fixed #1799
HumanBodyBones.ToString != HumanTrait.BoneName であることに注意(指のみ。Space)。
分かりにくいので変数名、関数名をくどい感じにしました。
コード整理したら `HumanBodyBones` => `HumanTrait.BoneName` になった。
要するに `Dictionary<HumanBodyBones, string>`
=> AvatarBuilder.BuildHumanAvatar には隠れたボーン名 HumanTrait.BoneName が必用

Assets/VRM10/Runtime/IO/Vrm10Exporter.cs
Importer だけ変換していたので、
Export するたびにカプセルコライダーのx座標が反転する現象。
=> [1.0] SpringBone のカプセルコライダーの座標変換漏れ

Assets/VRM/Runtime/IO/VRMImporterContext.cs
この PR は、 `VRMImporterContext.LoadBlendShapeMaster` を async Task 化し、`IAwaitCaller` を与えます。これによって、 CPU スパイクの軽減を目指します。
このために、 `VRMImporterContext.LoadBlendShapeMaster` 内のループで `IAwaitCaller.NextFrameIfTimedOut()` を呼び出しています。
また、  `VRMImporterContext.LoadBlendShapeBind` も async 化しています。
これは、このメソッド内の連続した LINQ 処理に長い時間がかかる可能性があるためです。
----
edit : `NextFrameIfTimedOut` の直前、直後に `NextFrame` が配置されているケースがありますが、従来の動作との互換性を考えて、このPRではそのままにしています。
=> Add IAwaitCaller to VRMImporterContext.LoadBlendShapeMaster

Assets/VRM10/Runtime/Components/VRM10Object/VRM10ObjectFirstPerson.cs, Assets/VRM10/Runtime/Components/Vrm10Instance/Vrm10Instance.cs, Assets/VRM10/Runtime/Components/Vrm10Runtime/ControlRig/ControlRigGenerationOption.cs, Assets/VRM10/Runtime/Components/Vrm10Runtime/ControlRig/ControlRigGenerationOption.cs.meta, Assets/VRM10/Runtime/Components/Vrm10Runtime/ControlRig/Vrm10ControlBone.cs, Assets/VRM10/Runtime/Components/Vrm10Runtime/Vrm10Runtime.cs, Assets/VRM10/Runtime/Components/Vrm10Runtime/Vrm10RuntimeControlRig.cs, Assets/VRM10/Runtime/IO/Vrm10.cs, Assets/VRM10/Runtime/IO/Vrm10Importer.cs, Assets/VRM10/Runtime/Scenes/Sample.cs, Assets/VRM10/Tests/ExpressionTests.cs, Assets/VRM10/Tests/MigrationTests.cs, Assets/VRM10/Tests/TestAsset.cs
API Breaking Change
既存のコードベースとの互換を考えると、Animator を上書きするかたちの ControlRig が必要であろうとなったので
それを追加します。
=> Replace control rig generation option with enum in vrm 1.0

Assets/VRM10/Runtime/Format/Vrm/Format.g.cs
https://github.com/vrm-c/vrm-specification/pull/394
に追随。
- submodule の前進
- コード生成の実行 (Format.g.cs)
のみです。
`matcapColor` を使う Import/Export の追記も必用。
=> [1.0] format に matcapColor 反映

Assets/VRM10/Runtime/Components/Expression/MaterialValueBindingMerger.cs, Assets/VRM10/Runtime/Components/Expression/PreviewMaterialItem.cs
https://github.com/vrm-c/UniVRM/pull/1817 の追従漏れ
=> follow matcapFactor in material color binding

Assets/VRM10/Runtime/IO/Material/Vrm10MToonMaterialExporter.cs, Assets/VRM10/Runtime/IO/Material/Vrm10MToonMaterialImporter.cs
In vrm 1.0 specification, The uv rotation speed unit is radian per second.
UniVRM implementation uses rotation per second.
It must be converted.
In vrm 1.0 specification, the uv rotation direction is counter-clockwise in uv coords.
And the texture coordinates is different between glTF and Unity.
Therefore, the speed parameter must be inverted.
|\ | glTF | Unity |
| --- | --- | --- |
| rotation speed | positive | positive | 
| uv in uv coords | CCW (Bottom-left origin) | CCW (Bottom-left origin) |
| uv in texture coords | CW (Top-left origin) | CCW (Bottom-left origin) |
| image on mesh | CCW | CW (inverted 😭) |
https://github.com/vrm-c/vrm-specification/tree/master/specification/VRMC_materials_mtoon-1.0
https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#images
=> Fix uv rotation coords of vrm-1.0

Assets/VRM10/Runtime/Migration/Materials/MigrationMToonMaterial.cs
`matcapFactor` の追加に伴い、マイグレーションにバグがありました。これを直します。
具体的には MatCap テクスチャが存在するときは `matcapFactor` を `1.0` に設定するようにしました。
また `RimLightingLightingMixFactor` も、 Parametric Rim と Matcap の統合により曖昧なパラメタになっているので
これを一律に安全な見た目に倒すように変更しました。
=> Fix migration behaviour of matcap.

Assets/VRM10/Runtime/IO/Material/Vrm10MToonMaterialExporter.cs, Assets/VRM10/Runtime/IO/Material/Vrm10MToonMaterialImporter.cs
https://github.com/vrm-c/UniVRM/pull/1826 was wrong interpretation.
This pull request is correct.
glTF uses U-right V-down space in the texture coords. [[refs]](https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#images)
Unity uses U-right V-up space in the texture coords. [[refs]](https://docs.unity3d.com/ScriptReference/Mesh-uv.html)
Directions of the positive rotation value
|\ | glTF (KHR_texture_transform & vrmc_materials_mtoon-1.0) | Unity |
| --- | --- | --- |
| uv in mathematical coords | CW (U-right V-up space) | CCW (U-right V-up space) |
| uv in texture coords | CCW (U-right V-down space) **[specification]** | CCW (U-right V-up space) |
| image on mesh | CW 👍 | CW 👍  |
reference: 
https://github.com/KhronosGroup/glTF/pull/1624
=> Invert UV rotation direction of MToon 1.0 import/export.

Assets/UniGLTF/Runtime/UniGLTF/IO/ImporterContext.cs
処理の長いループ内に `IAwaitCaller.NextFrameIfTimedOut` を追加します。
ループ外に `Profiler.Begin/EndProfile()` がある場合は、ループ内に入れます。
これにより、UnityEngine がループをまたいだ `Begin/EndProfile` に対して警告を出すのを抑制します。
`NextFrame()` とのバランスから、また、将来 `continue` 等のフロー制御を追加した際にも気にせず対応できるよう、できるだけループの先頭側に `NextFrameIfTimedOut` を追加しています。
ただ、コード全体として見たとき、これが望ましい位置なのか意見が分かれる点かもしれません。
=> Add IAwaitCaller.NextFrameIfTimedOut to time consuming loops

Assets/UniGLTF/Runtime/UniGLTF/IO/TextureIO/GltfTextureImporter.cs
fixed #1840
This is cause `CS1525: Invalid expression term '='` in Unity-2019.
=> [Unity-2019] fix `??=`.

Assets/VRM/Editor/BlendShape/BlendShapeClipEditorHelper.cs, Assets/VRM10/Editor/Components/Expression/ExpressionEditorHelper.cs
Unity 2021.2以上でTexture2D.Resizeを使用するとAPIの更新が求められます。 
1. Unity 2021.2でプロジェクトを作成
2. UniVRMとVRMのunitypackageを追加（[リンク](https://github.com/vrm-c/UniVRM/releases/tag/v0.104.1)）
UPMの`Add package from disk...`を使用した場合も同様の結果が得られます
以下の2個のファイルに対して、APIの更新が求められます。
* `Assets/VRM/Editor/BlendShape/BlendShapeClipEditorHelper.cs`
* `Assets/VRM10/Editor/Components/Expression/ExpressionEditorHelper.cs`
`UNITY_2021_2_OR_NEWER`の#ifディレクティブを追加しました
[What's new in Unity 2021.2.0 - Unity](https://unity3d.com/jp/unity/whats-new/2021.2.0)
```
Graphics: Changed: Renamed Texture2D.Resize to Reinitialize. ([1312670](https://issuetracker.unity3d.com/issues/texture2d-dot-resize-toggles-graphicsformat-each-time-its-called-between-linear-and-srgb))
```
[Unity Issue Tracker - Texture2D.Resize toggles GraphicsFormat each time …
=> Rename Texture2D.Resize to Reinitialize

Assets/VRMShaders/GLTF/IO/Runtime/PathObject.cs
`#if UNITY_EDITOR` を追加。
PathObject (UnityPath をリファインしたもの) は、このバージョンから Editor から Runtime に移動していました。
PathObject は UnityPath と仕様を変えて、UnityProject の外のパスを扱えるようにしたものです。
UnityPath は UnityProject を root とした相対パスで表現されるため、
外のパスを扱うと例外が飛びます。
=> Editor向け機能の切り分け忘れ

Assets/VRM10/Runtime/IO/Vrm10Exporter.cs
`Vrm10Exporter` のstaticの `Export` にoptionalな第三引数 `vrmMeta` を追加しました。
`Vrm10Exporter` のstaticじゃない `Export` メソッドにあったoptionalな `vrmMeta` にそのまま渡します。
=> feature: add third argument `vrmMeta` to static Vrm10Exporter.Export

Assets/VRM10/Editor/Vrm10InstanceEditor.cs, Assets/VRM10/Runtime/Components/Vrm10Instance/Vrm10Instance.cs
親指の向き・爪の向きのガイドを行うGizmoを表示するようにしました。
元々、ousttrueさんが #1875 で行っていたものに対して、表示の改善を行ったものです。
VRM仕様のT-Pose定義にもとづいています:
https://github.com/vrm-c/vrm-specification/blob/master/specification/VRMC_vrm-1.0/tpose.ja.md
=> 親指の向き・爪の向きのガイドを行うGizmo

Assets/VRM10/Editor/Components/Expression/VRM10ExpressionEditor.cs, Assets/VRM10/Runtime/Components/Expression/Preview/PreviewMaterialUtil.cs, Assets/VRM10/Runtime/Components/Expression/Preview/PreviewSceneManager.cs, Assets/VRM10/Runtime/Components/Expression/PreviewMaterialItem.cs
サポートされていないシェーダーが含まれているモデルのVRM10 Expression Assetを選択するとプレビューが表示されない問題を修正しました。
1. UniVRMのプロジェクトを開く
2. `Assets\VRM10_Samples\ModelSetup_SeedSan\Materials\mtoon\hair.mat`のシェーダーを`Sprites/Diffuse`に変更する
3. `Assets\VRM10_Samples\ModelSetup_SeedSan\Expressions\aa.asset`を選択する
* UniVRM10.PreviewMaterialItem.GetBindTypeでNotImplementedExceptionが発生する
* Scene上に__PREVIEW_SCENE_MANGER__が残る
<details>
<summary>エラー全文</summary>
```
NotImplementedException: The method or operation is not implemented.
UniVRM10.PreviewMaterialItem.GetBindType (System.String property) (at Assets/VRM10/Runtime/Components/Expression/PreviewMaterialItem.cs:115)
UniVRM10.PreviewMaterialUtil.CreateForPreview (UnityEngine.Material material) (at Assets/VRM10/Runtime/Components/Expression/Preview/PreviewMaterialUtil.cs:27) …
```
=> サポートされていないシェーダーが含まれるモデルのプレビューをできるように

Assets/UniGLTF/Runtime/UniGLTF/IO/TextureIO/GltfTextureImporter.cs, Assets/VRM10/Runtime/IO/Texture/Vrm10TextureDescriptorGenerator.cs, Assets/VRMShaders/GLTF/IO/Runtime/Texture/Importer/UnityTextureDeserializer.cs
VRM 1.0 モデルインポート時の挙動を修正。
- サムネイル画像の mimeType が `null` になっていたバグを修正。
- サムネイル画像の名前に対して強制的に `__UNIGLTF_DUPLICATED` suffix がついてしまっていた状態を解消。
- Export 時に glTF texture を定義しているが、Import 時はこれを参照せず動的に glTF texture を生成するため名前が被る
- mimeType が予期しない値だった時のログを Warning から通常のレベルに変更。
=> Consider thumbnail image's mimeType when loading the VRM 1.0 model.

Assets/UniGLTF/Editor/UniGLTF/ExportDialog/ExportDialogState.cs, Assets/UniGLTF/Editor/UniGLTF/ScriptedImporter/GltfScriptedImporterBase.cs, Assets/UniGLTF/Editor/UniGLTF/ScriptedImporter/TextureExtractor.cs, Assets/UniGLTF/Runtime/MeshUtility/BoneNormalizer.cs, Assets/UniGLTF/Runtime/MeshUtility/MeshExtensions.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/ImporterContextExtensions.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/GltfMaterialDescriptorGenerator.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/URP/GltfURPMaterialDescriptorGenerator.cs, Assets/VRM/Editor/Format/VRMEditorImporterContext.cs, Assets/VRM/Runtime/BlendShape/PreviewSceneManager.cs, Assets/VRM/Runtime/IO/VRMURPMaterialDescriptorGenerator.cs, Assets/VRM10/Editor/ScriptedImporter/VrmScriptedImporterImpl.cs, Assets/VRM10/Editor/Vrm10TopMenu.cs, Assets/VRM10/Runtime/Components/Expression/Preview/PreviewSceneManager.cs, Assets/VRM10/Runtime/IO/Material/Vrm10MaterialDescriptorGenerator.cs, Assets/VRM10/Runtime/Migration/Materials/Vrm0XMToonValue.cs, Assets/VRMShaders/GLTF/IO/Runtime/Material/Importer/MaterialFactory.cs, Assets/VRMShaders/GLTF/IO/Runtime/Util/Symbols.cs
プリプロセッサを使うことで IDE でのコード変更の追いづらさが高まってしまうので、使用をやめました。
これによる実行時の負荷増加は、保守性の低下と比べれば微々たるものだと考えます。
また IL2CPP を通せばコンパイル時に消える処理になっているといいなあ、というところです。
=> Use static getter instead of preprocessors.

Assets/VRM/Runtime/IO/MaterialIO/BuiltInRP/Export/BuiltInVrmMaterialExporter.cs
https://github.com/vrm-c/UniVRM/pull/1004 で削除された Shader の Export がいまだ考慮されていたので、該当コードを削除。
=> Stop supporting to export legacy vrm shaders.

Assets/UniGLTF/Runtime/UniGLTF/IO/UnityPath.cs, Assets/UniGLTF/Tests/UniGLTF/UniGLTFTests.cs, Assets/VRM/Editor/Format/vrmAssetPostprocessor.cs, Assets/VRM/Editor/SkinnedMeshUtility/VrmMeshIntegratorWizard.cs, Assets/VRM10/Editor/Vrm10ExportDialog.cs, Assets/VRM10/Editor/Vrm10InstanceEditor.cs
現在のUnityPathはAssets以下にファイルを作成することのみを想定しています。
そのため、モデルをローカルのパッケージで管理しているとパッケージのフォルダ以下にVRM関連のオブジェクトを生成することができません。
そこで、UnityPathでローカルのパッケージ管理下のファイルも扱えるようにしました。
例としてPackages以下に直接パッケージを置く方法を記載していますが、manifest.jsonから`file://~`で指定した場合も同様の結果になります。
1. `Packages/Test/package.json`を以下の内容で作成
``` json
{
"displayName": "Test",
"name": "test",
"version": "0.0.0"
}
```
2. `Assets\VRM10_Samples\ModelSetup_SeedSan\Models\new_seedsan_betterfbx.fbx`のをシーン上に置く
3. 2で置いたモデルに`VRMInstance`をアタッチ
4. `Create new VRM10Object and default Expressions. select target folder`をクリック
5. 1で作成したフォルダを選択
6. `フォルダーの選択`をクリック
* NotImplementedExceptionが出てVRM10Objectが生成されない
<details>
<summary>エラー全文</summary>
```
NotImplementedException: The method or operation is not implemented.
UniGLTF.UnityPath.CreateAsset (UnityEngine.Object o) (at …
```
=> UnityPathでパッケージ管理下のファイルを扱えるように

Assets/VRM10/Editor/VRM10ExportSettings.cs, Assets/VRM10/Editor/Vrm10ExportDialog.cs
fixed #1906
#1913
未実装だった `ReduceBlendshape`,  `ReduceBlendshapeClip` を封じました。
次のバージョンで実装予定です。
=> [1.0] morph target の accessor に sparse を使うか否かのオプションを実装

Assets/UniGLTF/Runtime/UniGLTF/IO/UnityPath.cs, Assets/UniGLTF/Tests/UniGLTF/UniGLTFTests.cs
UnityPath.FromUnityPath の引数が null, "", "." の場合の動作を調整した。
=> UnityPath の UnitTest が失敗するのを修正

Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/BuiltInRP/Import/Materials/BuiltInGltfPbrMaterialImporter.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/BuiltInRP/Import/Materials/BuiltInGltfUnlitMaterialImporter.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/GltfMaterialImportUtils.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/URP/Import/Materials/UrpGltfPbrMaterialImporter.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/MigrationFlags.cs, Assets/VRM/Runtime/IO/VRMData.cs
UniVRM 0.54 未満の古い VRM ファイルに対する、Standard Material のマイグレーションフラグを追加しました。
この PR で修正されたものです。
https://github.com/vrm-c/UniVRM/pull/339
=> Migrate baseColorFactor of older VRM files

Assets/VRM/Tests/InvalidFileNameTest.cs
macOS上のUnity 2020.3.34f1でDetectInvalidCharactersテストが失敗していました。テスト対象メソッドの Path.GetInvalidFileNameCharsの実装をUnityのレポジトリで確認したところ ( https://github.com/Unity-Technologies/mono/blob/2020.3.34f1/mcs/class/corlib/System.IO/Path.cs#L560-L571 ) Windows以外の環境では、必ずテストに失敗することがわかりました。
調査したところ、Path.GetInvalidFileNameChars自体がUniVRMとそのサブモジュールですでに使われていないことが判明したため テスト自体が不要になったと考え、削除しました。
=> Windows以外でDetectInvalidCharactersテストが失敗する。テスト対象メソッドがもう使われていないのでテスト自体を削除

Assets/VRM/Tests/VRMTextureEnumerateTests.cs
`default(ArraySegment<byte>).ToArray()` throws `InvalidOperationException` since Unity 2021.
It fails `VRMTextureEnumerateTests`. Use `new ArraySegment<byte>(Array.Empty<byte>())` instead.
Confirmed to work with Unity 2020.3.34f1, 2021.3.13f1 and 2022.1.23f1.
fixes https://github.com/vrm-c/UniVRM/issues/1934
=> Use `new ArraySegment<byte>(Array.Empty<byte>())` instead of `default(ArraySegment<byte>)`

Assets/UniGLTF/Runtime/UniGLTF/IO/ImporterContext.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/BuiltInRP/Import/BuiltInGltfMaterialDescriptorGenerator.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/BuiltInRP/Import/Materials/BuiltInGltfDefaultMaterialImporter.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/BuiltInRP/Import/Materials/BuiltInGltfDefaultMaterialImporter.cs.meta, Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/IMaterialDescriptorGenerator.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/URP/Import/Materials/UrpGltfDefaultMaterialImporter.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/URP/Import/Materials/UrpGltfDefaultMaterialImporter.cs.meta, Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/URP/Import/UrpGltfMaterialDescriptorGenerator.cs, Assets/VRM/Runtime/IO/MaterialIO/BuiltInRP/Import/BuiltInVrmMaterialDescriptorGenerator.cs, Assets/VRM/Runtime/IO/MaterialIO/URP/Import/UrpVrmMaterialDescriptorGenerator.cs, Assets/VRM10/Runtime/IO/Material/BuiltInRP/Import/BuiltInVrm10MaterialDescriptorGenerator.cs, Assets/VRM10/Runtime/IO/Material/URP/Import/UrpVrm10MaterialDescriptorGenerator.cs, Assets/VRMShaders/GLTF/IO/Runtime/Material/Importer/MaterialDescriptor.cs
MaterialDescriptor には `string shaderName` ではなく `Shader shader` を持たせたい。
そのためにまず、MaterialDescriptor をリファクタして、ImporterContext から RenderPipeline の具体的な知識を剥がす。
=> Refactor MaterialDesciptorGenerator

Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/BuiltInRP/Import/BuiltInGltfMaterialDescriptorGenerator.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/BuiltInRP/Import/Materials/BuiltInGltfDefaultMaterialImporter.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/BuiltInRP/Import/Materials/BuiltInGltfPbrMaterialImporter.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/BuiltInRP/Import/Materials/BuiltInGltfUnlitMaterialImporter.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/URP/Import/Materials/UrpGltfDefaultMaterialImporter.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/URP/Import/Materials/UrpGltfPbrMaterialImporter.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/URP/Import/UrpGltfMaterialDescriptorGenerator.cs, Assets/UniGLTF/Tests/UniGLTF/GltfLoadTests.cs, Assets/VRM/Runtime/IO/MaterialIO/BuiltInRP/Import/BuiltInVrmMaterialDescriptorGenerator.cs, Assets/VRM/Runtime/IO/MaterialIO/BuiltInRP/Import/Materials/BuiltInVrmMToonMaterialImporter.cs, Assets/VRM/Runtime/IO/MaterialIO/BuiltInRP/Import/Materials/BuiltInVrmUnlitTransparentZWriteMaterialImporter.cs, Assets/VRM/Runtime/IO/MaterialIO/URP/Import/UrpVrmMaterialDescriptorGenerator.cs, Assets/VRM/Tests/MToonTest.cs, Assets/VRM10/Runtime/IO/Material/BuiltInRP/Import/BuiltInVrm10MaterialDescriptorGenerator.cs, Assets/VRM10/Runtime/IO/Material/BuiltInRP/Import/Materials/BuiltInVrm10MToonMaterialImporter.cs, Assets/VRM10/Runtime/IO/Material/URP/Import/UrpVrm10MaterialDescriptorGenerator.cs, Assets/VRM10/Tests/MaterialImportTests.cs, Assets/VRMShaders/GLTF/IO/Runtime/Material/Importer/MaterialDescriptor.cs, Assets/VRMShaders/GLTF/IO/Runtime/Material/Importer/MaterialFactory.cs
アプリケーションによっては Shader を暗黙的な `Shader.Find()` ではなく、アプリケーション側で明示的なアセットバンドルなどに含めて提供したい場合があります。
そうしたときに、既存の `MaterialDescriptor` の構造ではそれができません。
本 PR では `MaterialDescriptor` が保持するシェーダ情報を `string` から `Shader` に変えることで
上記の例のような場合を `IMaterialDescriptorGenerator` で実装可能にするよう柔軟性を持たせます。
=> Specify a Shader instead of a string in MaterialDescriptor.

Assets/VRM/Editor/SpringBone/VRMSpringBoneEditor.cs, Assets/VRM/Editor/SpringBone/VRMSpringBoneEditor.cs.meta, Assets/VRM/Runtime/SpringBone/VRMSpringBone.cs, Assets/VRM10/Editor/Components/SpringBone/VRM10SpringBoneJointEditor.cs, Assets/VRM10/Editor/Components/SpringBone/VRM10SpringBoneJointEditor.cs.meta, Assets/VRM10/Runtime/Components/SpringBone/VRM10SpringBoneJoint.cs
SpringBoneの各パラメータ（stiffness, gravityPower, jointRadius）に対して、スライダーの範囲は従来のまま、数値入力の際にスライダーの範囲を超えて入力できるように変更しました。
VRM0・VRM1の双方に変更を適用しました。
Editor拡張というものをいじる機会があまりなく、これで問題がないか不安です。
- Undo・Redoができること・変更を加えたプロパティの表示が変わること・プロパティ名を右クリックして値のコピーができることは確認しております。
=> Add limit break sliders to spring bone joint properties

Assets/UniGLTF/Runtime/Extensions/glTFExtensions.cs
■発生する例外
```
InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
System.Collections.Generic.Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior) (at <9aad1b3a47484d63ba2b3985692d80e9>:0)
System.Collections.Generic.Dictionary`2[TKey,TValue].Add (TKey key, TValue value) (at <9aad1b3a47484d63ba2b3985692d80e9>:0)
UniGLTF.glTFExtensions.IsGeneratedUniGLTFAndOlder (UniGLTF.glTF gltf, System.Int32 major, System.Int32 minor) (at Assets/UniGLTF/Runtime/Extensions/glTFExtensions.cs:153)
UniGLTF.MeshData.ImportMeshSharingVertexBuffer (UniGLTF.GltfData data, …
```
=> ランタイムロードの非同期アクセスで例外が発生する問題の修正 

Assets/UniGLTF/Runtime/UniGLTF/IO/MeshIO/MeshExportInfo.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/gltfExporter.cs
In my use case, I'm disabling certain renderers at runtime to hide previously added elements from the model. Since I want to have a undo/redo functionality, I do not want to delete these renderers thereby losing their content.
The exporter ignores if renderers are disabled and exports them anyway. I have added a check for that, thereby only exporting what is actually visible in Unity at runtime.
I can also amend this with an export setting in case it is important for someone to have disabled renderers still be exported.
=> Disabled renderers no longer get exported

Assets/VRM10/Runtime/FastSpringBone/System/FastSpringBoneService.cs
FastSpringBone should always be executed after `Vrm10Instance` in order for the SpringBone simulation to be smooth. However, currently both `Vrm10Instance` and `FastSpringBoneService` are set to DefaultExecutionOrder 11000. Because of this, the Execution order is unstable and there is no guarantee as to which code will get executed first.
To make sure `FastSpringBoneService` will always be executed after `Vrm10Instance`, I want to change the DefaultExecutionOrder of `Vrm10Instance` to 11010 with this PR.
=> Change FastSpringBoneService ExecutionOrder To 11010

Assets/VRM10/Editor/EditorTool/VRM10LookAtEditorTool.cs, Assets/VRM10/Runtime/AssemblyInfo.cs, Assets/VRM10/Runtime/AssemblyInfo.cs.meta, Assets/VRM10/Runtime/Components/Expression/LookAtEyeDirection.cs, Assets/VRM10/Runtime/Components/VRM10Object/VRM10ObjectLookAt.cs, Assets/VRM10/Runtime/Components/Vrm10Instance/Vrm10Instance.cs, Assets/VRM10/Runtime/Components/Vrm10Runtime/Vrm10Runtime.cs, Assets/VRM10/Runtime/Components/Vrm10Runtime/Vrm10RuntimeLookAt.cs, Assets/VRM10_Samples/VRM10Viewer/VRM10Loaded.cs
`Vrm10RuntimeLookAt` の実装が、API・ロジックともに非常に分かりづらかったためリファクタリングしました。
元の public 関数は Obsolete として残しています。
=> Refactoring about Vrm10 LookAtRuntime

Assets/VRM10/Runtime/Components/Vrm10Runtime/Vrm10Runtime.cs, Assets/VRM10/Runtime/Components/Vrm10Runtime/Vrm10RuntimeLookAt.cs
https://github.com/vrm-c/UniVRM/pull/1984 で public にした目の位置を指定する `LookAtOrigin` Transform は VRHMD の視点位置紐づけに使われる。
この Transform が ControlRig ではなく生ボーンのヒエラルキーにあると以下の時に問題がある。
1. ControlRig を更新する
2. LookAtOrigin Transform を見てカメラ位置と紐づける
3. Vrm10Runtime.Process で ControlRig の姿勢を生ボーンに適用する
2 の時に正しい姿勢が得られない。
LookAtOrigin Transform はランタイムにアクセスされることだけを想定するので、ControlRig があるならそちらにぶら下がっていた方が好ましい。
=> Add a LookAtOrigin transform to ControlRig.

Assets/VRM10_Samples/VRM10Viewer/VRM10ViewerUI.cs
bvh のファイルの中身を渡すべきところにファイル名を渡して、常にエラーになっていた。
=> sampler の bvh load の修正

Assets/VRM10/Runtime/Components/Vrm10Instance/Vrm10Instance.cs, Assets/VRM10/Runtime/Components/Vrm10Runtime/Vrm10Runtime.cs, Assets/VRM10/Runtime/Components/Vrm10Runtime/Vrm10RuntimeControlRig.cs, Assets/VRM10/Runtime/ControlRig/InitialRotations/ControlRigGenerationOption.cs, Assets/VRM10/Runtime/ControlRig/Vrm10BoneInitialRotation.cs, Assets/VRM10/Runtime/ControlRig/Vrm10BoneInitialRotation.cs.meta, Assets/VRM10/Runtime/ControlRig/Vrm10ControlBone.cs, Assets/VRM10/Runtime/IO/Vrm10.cs, Assets/VRM10/Runtime/IO/Vrm10Importer.cs, Assets/VRM10/Tests/ExpressionTests.cs, Assets/VRM10/Tests/MigrationTests.cs
Vrm10RuntimeControlRig は 正規化TPose(VRM0互換) に対するポーズ(NormalizedLocalRotation)を
受けるクラスであることを明確にして、インタフェースをシンプルにする。
ControlRig作成の３択
- 作らない
- ControlRig(VRM0互換)
- ControlRig(カスタム初期回転)
を
- 作らない
- ControlRig(VRM0互換)
の２択に変更します。
これに伴い `IReadOnlyDictionary<HumanBodyBones, Quaternion> controlRigInitialRotations` 
引き数を廃止し bool に変更します。
`IReadOnlyDictionary<HumanBodyBones, Quaternion> controlRigInitialRotations` を取り扱う責務は、
Vrm10RuntimeControlRig の外部に改めて作成します(Vrm10BoneInitialRotation を使う)。
=> [API Breaking Change] Vrm10RuntimeControlRig は、正規化されたTPoseを受け取る責務に特化

Assets/VRM/Editor/Format/vrmAssetPostprocessor.cs
vrmAssetPostprocessorが誤ってディレクトリを処理してしまうことがあるのを修正しました。
名前が `.vrm` で終わるフォルダに反応して、以下のエラーが出ていました:
```
Exception: Exception of type 'System.Exception' was thrown.
VRM.vrmAssetPostprocessor.ImportVrm (UniGLTF.UnityPath vrmPath) (at Assets/VRM/VRM/Editor/Format/vrmAssetPostprocessor.cs:46)
VRM.vrmAssetPostprocessor.OnPostprocessAllAssets (System.String[] importedAssets, System.String[] deletedAssets, System.String[] movedAssets, System.String[] movedFromAssetPaths) (at Assets/VRM/VRM/Editor/Format/vrmAssetPostprocessor.cs:31)
```
具体的には、 `Packages/com.vrmc.vrm` に反応してエラーを起こしてしまう現象が発生していました。
=> fix: Fix vrmAssetPostprocessor

Assets/UniGLTF/Runtime/UniGLTF/IO/NodeImporter.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/Parser/GlbLowLevelParser.cs, Assets/UniGLTF/Runtime/UniHumanoid/AvatarDescription.cs, Assets/UniGLTF/Runtime/UniHumanoid/IO/BvhImporterContext.cs, Assets/UniGLTF/Runtime/UniHumanoid/SkeletonMeshUtility.cs, Assets/VRM10/Editor/Vrm10SerializerGenerator.cs, Assets/VRM10/Runtime/ControlRig/InitialRotationPoseProvider.cs, Assets/VRM10/Runtime/Format/Animation.meta, Assets/VRM10/Runtime/Format/Animation/Deserializer.g.cs, Assets/VRM10/Runtime/Format/Animation/Deserializer.g.cs.meta, Assets/VRM10/Runtime/Format/Animation/Format.g.cs, Assets/VRM10/Runtime/Format/Animation/Format.g.cs.meta, Assets/VRM10/Runtime/Format/Animation/Serializer.g.cs, Assets/VRM10/Runtime/Format/Animation/Serializer.g.cs.meta, Assets/VRM10_Samples/VRM10Viewer/VRM10Motion.cs, Assets/VRM10_Samples/VRM10Viewer/VRM10Viewer.unity, Assets/VRM10_Samples/VRM10Viewer/VRM10ViewerUI.cs
https://github.com/vrm-c/vrm-specification/pull/425 の UniVRM での importer 実装です。
* VRMC_vrm_animation のコード生成
* VRMC_vrm_animation の import 実験(motion ボタンで拡張子 bvh 以外を vrm-animation として試行)
* VRMC_vrm_animation から humanoid 情報を得て vrm1 への retarget 例
など。
#1987 の分割 PR の最後がこれになります。
=> [experimental][vrm-animation] vrm animation の試験実装

Assets/VRM10/Editor/Components/VRM10MetaPropertyValidator.cs
vrm-1.0 のエクスポートダイアログで Authors の Array 表示が分かりにくい件
fixed #1845
fixed #1880
fixed #1981
ちょっと改善
=> ArrayProperty name `Element 0` to `{Array.Name}[0]`

Assets/UniGLTF/Runtime/UniHumanoid/IO/BvhImporterContext.cs, Assets/VRM_Samples/SimpleViewer/ViewerUI.cs
vrm-1.0 のサンプルの都合で BvhImporterContext は BoxMan の自動作成とHumanPoseTransfer の自動作成を止めてた。
vrm-0.x のサンプルが動かなくなっていた。
* BoxMan を隠すコードを削除(renderer.enabled=false が不要になった)
* HumanPoseTransfer は自動作成を復活(使わなければ特に影響無い)
=> [sample] SimpleViewer を修復(BvhImporterContext の挙動変更に追随)

Assets/UniGLTF/Runtime/UniHumanoid/AvatarDescription.cs, Assets/UniGLTF/Runtime/UniHumanoid/ForceUniqueName.cs, Assets/UniGLTF/Runtime/UniHumanoid/ForceUniqueName.cs.meta, Assets/UniGLTF/Runtime/UniHumanoid/HumanoidLoader.cs
fixed #2019
AvatarBuilder.BuildHumanAvatar の呼び出しがもう一か所あった。
#2000 と関連
- AvatarBuilder.BuildHumanAvatar
> Ambiguous Transform 'XXX:Hips' and 'XXX:Hips' found in hierarchy for human bone 'Hips'. Transform name mapped to a human bone must be unique.
=> AvatarBuilder.BuildHumanAvatar

Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/URP/Import/Materials/UrpGltfPbrMaterialImporter.cs
_METALLICSPECGLOSSMAPが正常にURP PBR Materialに設定されない問題を修正します
1行の修正のみ
=> _METALLICSPECGLOSSMAPが正常にURP Materialに設定されない問題を修正

Assets/VRMShaders/VRM10/MToon10/Runtime/MToonOutlineRenderFeature.cs, Assets/VRMShaders/VRM10/MToon10/Runtime/MToonOutlineRenderPass.cs
TransparentなOutlineの描画に対応します
Transparentの場合でも、Skyboxの描画前にOutlineの描画が走ってしまう問題を修正
=> TransparentなOutlineの描画に対応する

Assets/VRMShaders/VRM10/MToon10/Resources/VRM10/vrmc_materials_mtoon_attribute.hlsl, Assets/VRMShaders/VRM10/MToon10/Resources/VRM10/vrmc_materials_mtoon_forward_fragment.hlsl, Assets/VRMShaders/VRM10/MToon10/Resources/VRM10/vrmc_materials_mtoon_forward_vertex.hlsl, Assets/VRMShaders/VRM10/MToon10/Resources/VRM10/vrmc_materials_mtoon_geometry_normal.hlsl, Assets/VRMShaders/VRM10/MToon10/Resources/VRM10/vrmc_materials_mtoon_geometry_uv.hlsl, Assets/VRMShaders/VRM10/MToon10/Resources/VRM10/vrmc_materials_mtoon_geometry_vertex.hlsl, Assets/VRMShaders/VRM10/MToon10/Resources/VRM10/vrmc_materials_mtoon_input.hlsl, Assets/VRMShaders/VRM10/MToon10/Resources/VRM10/vrmc_materials_mtoon_lighting_mtoon.hlsl, Assets/VRMShaders/VRM10/MToon10/Resources/VRM10/vrmc_materials_mtoon_lighting_unity.hlsl, Assets/VRMShaders/VRM10/MToon10/Resources/VRM10/vrmc_materials_mtoon_render_pipeline.hlsl, Assets/VRMShaders/VRM10/MToon10/Resources/VRM10/vrmc_materials_mtoon_render_pipeline.hlsl.meta, Assets/VRMShaders/VRM10/MToon10/Resources/VRM10/vrmc_materials_mtoon_shadowcaster_vertex.hlsl
[vrmc_materials_mtoon_render_pipeline.hlsl](https://github.com/vrm-c/UniVRM/pull/2062/files#diff-2579bae94c095767625f2ec972533b8b0f264d615c2693323f06e0f390b70753) を切り出し、そこ以外の各種ロジックからURPに関する知識を隔離しました。
このPRでやらないこと
- AdditionalLightingのロジックの修正
- これは対応コストの高さが予測されるため、後回しにする
=> vrmc_materials_mtoon_render_pipelineにURPに関する知識を隔離する

Assets/VRM/Runtime/IO/VRMExporter.cs
=> human bone の index が -1 になりうる？

Assets/UniGLTF/Runtime/UniGLTF/IO/ImporterContext.cs, Assets/VRM/Editor/SpringBone/VRMSpringBoneUtilityEditor.cs, Assets/VRM/Runtime/IO/VRMImporterContext.cs, Assets/VRM/Runtime/SpringBone/VRMSpringUtility.cs
fixed #2023
index の範囲違反を含む SpringBone を import したときに throw しない。
SpringBone の import は中途半端な状態になるが、VRM 全体としてはロードできるようになる。
export 時の index -1 チェックをひとつ追加。
=> springbone の import で throw しない

Assets/VRM10/Runtime/Components/VrmAnimationInstance.meta, Assets/VRM10/Runtime/Components/VrmAnimationInstance/VrmAnimationInstance.cs, Assets/VRM10/Runtime/Components/VrmAnimationInstance/VrmAnimationInstance.cs.meta, Assets/VRM10/Runtime/IO/VrmAnimationImporter.cs, Assets/VRM10/Runtime/IO/VrmAnimationImporter.cs.meta, Assets/VRM10_Samples/VRM10Viewer/Motions/BvhMotion.cs, Assets/VRM10_Samples/VRM10Viewer/Motions/BvhMotion.cs.meta, Assets/VRM10_Samples/VRM10Viewer/Motions/IMotion.cs, Assets/VRM10_Samples/VRM10Viewer/Motions/IMotion.cs.meta, Assets/VRM10_Samples/VRM10Viewer/Motions/VrmAnimation.cs, Assets/VRM10_Samples/VRM10Viewer/Motions/VrmAnimation.cs.meta
VrmAnimation を import するユーザーコードは以下のような感じなります
```cs
public static async Task<VrmAnimation> LoadVrmAnimationFromPathAsync(string path)
{
using GltfData data = new AutoGltfFileParser(path).Parse();
using var loader = new VrmAnimationImporter(data);
var instance = await loader.LoadAsync(new ImmediateCaller());
return new VrmAnimation(instance.GetComponent<VrmAnimationInstance>());
}
```
=> [VRM-animation] VrmAnimationImporter を実装

Assets/UniGLTF/Editor/UniGLTF/ScriptedImporter/RemapScriptedImporterEditorBase.cs
Unity 2022.2以降のバージョンでScriptedImporterEditor.ResetValues()がObsoleteになり、代わりにDiscardChanges()の利用が推奨されるようになりました。 UniGLTF.RemapScriptedImporterEditorBaseがResetValues()を利用しており、それにより、次のような警告を発生させていました。
```
Assets/UniGLTF/Editor/UniGLTF/ScriptedImporter/RemapScriptedImporterEditorBase.cs(50,33): warning CS0672: Member 'RemapScriptedImporterEditorBase.ResetValues()' overrides obsolete member 'AssetImporterEditor.ResetValues()'. Add the Obsolete attribute to 'RemapScriptedImporterEditorBase.ResetValues()'.
Assets/UniGLTF/Editor/UniGLTF/ScriptedImporter/RemapScriptedImporterEditorBase.cs(54,13): warning CS0618: 'AssetImporterEditor.ResetValues()' is obsolete: 'UnityUpgradeable () -> DiscardChanges'
```
オーバーライドされたResetValuesにもObsoleteを付与することで、警告が抑制されるようになりました。 …
=> Unity 2022.2以降のScriptedImporterEditor.ResetValues()のObsolete警告が出るのに対応

Assets/UniGLTF/Runtime/Extensions/glTFExtensions.cs, Assets/VRM10/Editor/Vrm10TopMenu.cs, Assets/VRM10/Editor/VrmAnimationMenu.cs, Assets/VRM10/Editor/VrmAnimationMenu.cs.meta, Assets/VRM10/Runtime/IO/VrmAnimationExporter.cs, Assets/VRM10/Runtime/IO/VrmAnimationExporter.cs.meta, Assets/VRM10/Runtime/IO/VrmAnimationUtil.cs, Assets/VRM10/Runtime/IO/VrmAnimationUtil.cs.meta
API としてはもうちょっと分かりやすいものにできそうだけど、とりあえず動くものを。
- 初期化(T-Pose)
- 各フレーム
- 書き出し
の３ステップに組み替えて Exporter を隠蔽した方が良いかもしれない。
=> [vrm-animation] VrmAnimationExporter の実装と bvh 変換の実験

Assets/VRMShaders/VRM10/MToon10/Resources/VRM10/vrmc_materials_mtoon_depthnormals_fragment.hlsl, Assets/VRMShaders/VRM10/MToon10/Resources/VRM10/vrmc_materials_mtoon_depthnormals_fragment.hlsl.meta, Assets/VRMShaders/VRM10/MToon10/Resources/VRM10/vrmc_materials_mtoon_depthnormals_vertex.hlsl, Assets/VRMShaders/VRM10/MToon10/Resources/VRM10/vrmc_materials_mtoon_depthnormals_vertex.hlsl.meta, Assets/VRMShaders/VRM10/MToon10/Resources/VRM10/vrmc_materials_mtoon_depthonly_fragment.hlsl, Assets/VRMShaders/VRM10/MToon10/Resources/VRM10/vrmc_materials_mtoon_depthonly_fragment.hlsl.meta, Assets/VRMShaders/VRM10/MToon10/Resources/VRM10/vrmc_materials_mtoon_depthonly_vertex.hlsl, Assets/VRMShaders/VRM10/MToon10/Resources/VRM10/vrmc_materials_mtoon_depthonly_vertex.hlsl.meta, Assets/VRMShaders/VRM10/MToon10/Resources/VRM10/vrmc_materials_mtoon_shadowcaster_vertex.hlsl, Assets/VRMShaders/VRM10/MToon10/Resources/VRM10/vrmc_materials_mtoon_urp.shader
MToon10のURP向けシェーダに不具合、Passの不備があったため以下の修正を行いました。
ご確認の程よろしくお願いいたします。
* ShadowCasterの不具合修正
Cutoutモデルのキャストシャドーが正常に行われていない不具合を修正しました。
これは、AlphaClipを行うべきUV座標が正しくFragmentシェーダに渡されていなかったため発生していました。
* 不要なBuilt-inキーワードの削除
URPシェーダにおいて必要のないBuilt-in専用のキーワード群を削除しました。
以下はBuilt-inシェーダ専用なので不要です。
`#pragma multi_compile_fwdbase nolightmap nodynlightmap nodirlightmap novertexlight`
* DepthOnlyPass、DepthNormalsPassの追加
DepthOnlyとDepthNormalsパスを追加しました。
_CameraDepthTextureや_CameraNormalsTextureを使うポストプロセスには上記のパスはほぼ必須であり、また、DepthPrepassが使われるプロジェクトはDepthOnlyもしくはDepthNormalsパスがPrepassとして使われるため、URPにおいてはこれらが存在しないと様々なポストプロセス表現や正常な深度テストが行えない場合があります。
=> MToon10のURP向けシェーダの不具合やパス不備の修正

Assets/VRM10/Runtime/Components/Expression/ExpressionMerger.cs, Assets/VRM10/Runtime/Components/VRM10Object/VRM10ObjectExpression.cs, Assets/VRM10/Runtime/Components/Vrm10Runtime/Vrm10RuntimeExpression.cs
UnityのアップデートによりDictionaryは自動的にタプルに分解されるようになったため、これらのスニペットが不要になりました
この際に発生していたGC Allocがなくなり、負荷が少し改善します
=> Remove linq snippets disused on unity update

Assets/VRM10/Runtime/Components/Vrm10Runtime/Vrm10RuntimeExpression.cs
Dictionaryを受け取るバージョンであるSetWeightsNonAllocを作りました
DictionaryをIEnumerableとして列挙する際にGC Allocが発生しますが、このAPIを使うことでそれを回避することが出来ます
=> Add Vrm10RuntimeExpression.SetWeightNonAlloc method

Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/RenderPipelineMaterialDescriptorUtility.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/RenderPipelineMaterialDescriptorUtility.cs.meta, Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/RenderPipelineTypes.cs, Assets/VRM/Runtime/IO/MaterialIO/VRMRenderPipelineMaterialDescriptorGeneratorUtility.cs, Assets/VRM/Runtime/IO/MaterialIO/VRMRenderPipelineMaterialDescriptorGeneratorUtility.cs.meta, Assets/VRM10/Runtime/IO/Material/URP/Import/VRM10RenderPipelineMaterialDescriptorGeneratorUtility.cs, Assets/VRM10/Runtime/IO/Material/URP/Import/VRM10RenderPipelineMaterialDescriptorGeneratorUtility.cs.meta, Assets/VRM10/Runtime/IO/Vrm10Importer.cs, Assets/VRM_Samples/SimpleViewer/ViewerUI.cs
This PR adds code to automatically detect the render pipeline and adds utility functions that returns the correct `IMaterialDescriptorGenerator` based on the current pipeline.
It also implements a use case in the  Vrm10Importer that means that in a URP project at runtime a VRM10 is loaded in using the correct materials.
=> Auto detect render pipelines

Assets/VRM10/Runtime/Components/Expression/ExpressionKey.cs, Assets/VRM10/Runtime/Components/Expression/ExpressionMerger.cs, Assets/VRM10/Runtime/Components/Vrm10Runtime/Vrm10RuntimeExpression.cs, Assets/VRM10/Tests/ExpressionKeyTests.cs, Assets/VRM10/Tests/ExpressionKeyTests.cs.meta
毎フレーム呼び出される `Vrm10RuntimeExpression` 中の処理で `ExpressionKey` の Dictionary Key としての比較処理がそこそこ負荷が高い。
これを public な挙動を変更せずに改善する。
13 % くらいは高速化した、かも。
=> Speed up ExpressionKey's comparison.

Assets/UniGLTF/Runtime/UniGLTF/IO/AnimationIO/AnimationImporterUtil.cs, Assets/VRM10/Runtime/Components/VrmAnimationInstance/VrmAnimationInstance.cs, Assets/VRM10/Runtime/IO/VrmAnimationImporter.cs, Assets/VRM10_Samples/VRM10Viewer/Motions/BvhMotion.cs, Assets/VRM10_Samples/VRM10Viewer/Motions/IMotion.cs, Assets/VRM10_Samples/VRM10Viewer/Motions/VrmAnimation.cs, Assets/VRM10_Samples/VRM10Viewer/VRM10ViewerUI.cs
AnimationClip に普通の float curve として格納する様に変更した。
VrmAnimationInstance の public field と連動する。
=> VrmAnimation の Expression は float field に変更

Assets/VRM10/Runtime/Components/Vrm10Runtime/Vrm10RuntimeExpression.cs
現在 `Vrm10RuntimeExpression` の `SetWeights()` `SetWeightsNonAlloc()` `SetWeight()` は呼び出すと即時、Expression の設定に従って `SkinnedMeshRenderer` の BlendShape 等が変化するように反映します。
この挙動は直感的に思えますが、実は他の Vrm10 要素と一貫性がなく、なによりパフォーマンスボトルネックになっています。
一貫性の無さとして `ControlRig` `Constraint` `LookAt` の他の Vrm10Runtime 要素は即時反映ではないことが挙げられます。
これらはデフォルトでは LateUpdate で呼び出される `Vrm10Runtime` の `Process()` において反映されます。
https://github.com/vrm-c/UniVRM/blob/4621d51001d16706a72d7eb574a80885b06cbf29/Assets/VRM10/Runtime/Components/Vrm10Runtime/Vrm10Runtime.cs#L187-L203
またパフォーマンスボトルネックとしては、１フレーム中において
- 「ユーザが `Vrm10RuntimeExpression.SetWeights()` を呼び出したとき」
- 「LateUpdate で `Vrm10Runtime.Process()` が呼び出されるとき」
の 2 回、反映処理が走ってしまうことがかなりネックになっています。
---
今回の挙動変更を行うことで、次のような変化が起きます。
- メリット Pros
- 多くのユーザアプリケーション実装において、特に挙動を変えずに Expression …
=> [API Behaviour Breaking Change] Don't change raw blendshapes immediately when calling `Vrm10RuntimeExpression.SetWeights()`

Assets/UniGLTF/Runtime/UniGLTF/RuntimeGltfInstance.cs
This PR introduces the `ReplaceResource` method to the `RuntimeGltfInstance` class. This enables resource replacement of Textures, Materials, AnimationClips, and Meshes. The old resource is destroyed after replacement.
In our project we integrated UniVRM for handling VRM imports. In a recent optimization effort we encountered the need to downscale the textures of imported VRMs during runtime. However we ran into issues regarding UniGLTF as the `RuntimeGltfInstance` class stores textures and other resources in a readonly list with no way to modify the contents from an external class. The `ReplaceResource` method is our solution to this limitation. By introducing this method, we can effectively modify and replace resources in the readonly list, ensuring efficient memory in our project.
=> Add `ReplaceResource` Method to `RuntimeGltfInstance`

Assets/VRM10/Runtime/Components/Vrm10Runtime/Vrm10Runtime.cs, Assets/VRM10/Runtime/Components/VrmAnimationInstance/Vrm10AnimationInstance.cs, Assets/VRM10/Runtime/Components/VrmAnimationInstance/Vrm10PoseLoader.cs, Assets/VRM10/Runtime/Components/VrmAnimationInstance/Vrm10PoseLoader.cs.meta, Assets/VRM10_Samples/VRM10Viewer/Motions/VrmAnimation.cs, Assets/VRM10_Samples/VRM10Viewer/VRM10ViewerUI.cs
- ポーズは UniVRMローカル用に名前変更
- ポーズをサンプルから API に移動。入れ物は Vrm10AnimationInstance を使うように変更
- Expression 周りの未実装を作業
- Custom 用の Setter/Getter を整備
LookAt は次で作業することにしてこの PR には含めないことにしました。
=> [VrmAnimation] Expression 周りの整理など

Assets/VRM10/Runtime/Components/LookAt/LookAtEyeDirection.cs, Assets/VRM10/Runtime/Components/LookAt/LookAtEyeDirectionApplicableToBone.cs, Assets/VRM10/Runtime/Components/LookAt/LookAtEyeDirectionApplicableToExpression.cs, Assets/VRM10/Runtime/Components/LookAt/LookAtInput.cs, Assets/VRM10/Runtime/Components/LookAt/LookAtInput.cs.meta, Assets/VRM10/Runtime/Components/Vrm10Runtime/Vrm10Runtime.cs, Assets/VRM10/Runtime/Components/Vrm10Runtime/Vrm10RuntimeLookAt.cs, Assets/VRM10/Runtime/Components/VrmAnimationInstance/IVrm10Animation.cs, Assets/VRM10/Runtime/Components/VrmAnimationInstance/Vrm10AnimationInstance.cs, Assets/VRM10_Samples/VRM10Viewer/Motions/BvhMotion.cs
=> LookAt の整理

Assets/VRMShaders/GLTF/IO/Runtime/Texture/Importer/DeserializingTextureInfo.cs, Assets/VRMShaders/GLTF/IO/Runtime/Texture/Importer/TextureFactory.cs
We implement image decoding in multi-thread, except "TextureImportTypes.StandardMap" mode for converting.
=> Transfer "TextureImportTypes" to ITextureDeserializer.LoadTextureAsync()

Assets/UniGLTF/Runtime/Extensions/StringExtensions.cs, Assets/VRM10/Runtime/StringExtensions.cs
https://misskey.niri.la/notes/9iqp7u6432
> AAOでmergeしたときにメッシュ名が空欄ににゃるからか、VRM出力の際にメッシュ名が ".baked"みたいににゃってしまって何かおかしくにゃってしまう…
のUniVRM側での対策です。AAOのメッシュ名が空で、その後変換時に`.baked`が追加された結果`.baked`という名称になり、これがアセットファイルの名前になるのが原因だと推測しました
=> メッシュ名が.から始まってたり空だとimport時に失敗する?

Assets/VRM10/Editor/Components/Expression/VRM10ExpressionEditor.cs
ExpressionのPreviewのPrefabを切り替えたときにパラメータが表示されなくなる問題を修正しました。
```
MissingReferenceException: The object of type 'SkinnedMeshRenderer' has been destroyed but you are still trying to access it.
Your script should either check if it is null or you should not destroy the object.
UniVRM10.SerializedExpressionEditor.MorphTargetBindsGUI () (at Assets/VRM10/Editor/Components/Expression/SerializedExpressionEditor.cs:179)
UniVRM10.SerializedExpressionEditor.Draw (UniVRM10.VRM10Expression& bakeValue) (at Assets/VRM10/Editor/Components/Expression/SerializedExpressionEditor.cs:96)
UniVRM10.ExpressionEditor.OnInspectorGUI () (at Assets/VRM10/Editor/Components/Expression/VRM10ExpressionEditor.cs:308)
UnityEditor.UIElements.InspectorElement+<>c__DisplayClass59_0.<CreateIMGUIInspectorFromEditor>b__0 () (at …
```
=> ExpressionのPreviewのPrefabを切り替えたときにパラメータが表示されなくなる問題を修正

Assets/VRM10/Runtime/Components/LookAt/LookAtEyeDirection.cs, Assets/VRM10/Runtime/Components/LookAt/LookAtEyeDirectionApplicableToBone.cs
Fix #2159 
次の問題を修正した
- VRM 1.0 の、ボーンを利用した目線制御において
- 実装が間違っており、ボーンの回転が identity でないときにおかしくなっていた
- 左目の Outer/Inner 制限角度が反転していた
=> Fix a incorrect eye direction control in VRM-1.0.

Assets/UniGLTF/Runtime/UniGLTF/IO/GltfExportSettings.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/MeshIO/MeshExporter_DividedVertexBuffer.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/MeshIO/MeshExporter_SharedVertexBuffer.cs, Assets/VRM/Editor/Format/VRMExportSettings.cs
fixed #2167
現状、Unity 上で２番目以降の UV を正しく反映する実装が無いのでエクスポートしない。
正しく反映 するには glTF と互換性のある shader にする必要があるのだが、
Unity の Standard と glTF の仕様が違うので対応予定無し。
- glTF は TextureInfo 毎に UV のチャンネルを指定することができる
https://github.com/KhronosGroup/glTF/blob/main/specification/2.0/schema/textureInfo.schema.json#L13
=> TEXCOORD_1 は export しない

Assets/UniGLTF/Runtime/MeshUtility/BlendShapeReport.cs, Assets/UniGLTF/Runtime/MeshUtility/BlendShapeReport.cs.meta, Assets/UniGLTF/Runtime/MeshUtility/BoneNormalizer.cs, Assets/UniGLTF/Runtime/MeshUtility/MeshFreezer.cs, Assets/UniGLTF/Runtime/MeshUtility/MeshFreezer.cs.meta, Assets/UniGLTF/Runtime/UniHumanoid/AvatarDescription.cs, Assets/VRM/Runtime/SkinnedMeshUtility/VRMBoneNormalizer.cs, Assets/VRM/Tests/NormalizeTests.cs, Assets/VRM10/Editor/MeshUtility/Vrm10MeshUtilityDialog.cs, Assets/VRM10/Runtime/MeshUtility/Vrm10MeshUtility.cs
#2169 の部品
vrm-0 の正規化ロジックを公開関数にしてオプションを整理。
ロジックの変更はまだしていない。
mesh bake までできるようになった。
=> [vrm1.0] impl refactor mesh bake

Assets/UniGLTF/Editor/MeshUtility/TabMeshIntegrator.cs, Assets/UniGLTF/Runtime/MeshUtility/BoneNormalizer.cs, Assets/UniGLTF/Runtime/MeshUtility/MeshIntegrationGroup.cs, Assets/UniGLTF/Runtime/MeshUtility/MeshIntegrationGroup.cs.meta, Assets/UniGLTF/Runtime/MeshUtility/MeshIntegrationResult.cs, Assets/UniGLTF/Runtime/MeshUtility/MeshIntegrator.cs, Assets/UniGLTF/Runtime/MeshUtility/MeshIntegratorUtility.cs, Assets/UniGLTF/Runtime/UniHumanoid/AvatarDescription.cs, Assets/VRM/Editor/SkinnedMeshUtility/VRMMeshIntegratorUtility.cs, Assets/VRM10/Editor/MeshUtility/MeshIntegrationTab.cs, Assets/VRM10/Runtime/MeshUtility/Vrm10MeshUtility.cs
#2169 の部品
List<Renderer> を統合するシンプルなインタフェースに改変。
exclude や統合対象を調整する責務は呼び出し側に移動した。
=> [vrm1.0] impl refactor mesh integration

Assets/UniGLTF/Editor/MeshUtility/TabMeshIntegrator.cs, Assets/UniGLTF/Runtime/MeshUtility/BoneMeshEraser.cs, Assets/UniGLTF/Runtime/MeshUtility/MeshFreezer.cs, Assets/UniGLTF/Runtime/MeshUtility/MeshIntegrationGroup.cs, Assets/UniGLTF/Runtime/MeshUtility/MeshIntegrationResult.cs, Assets/UniGLTF/Runtime/MeshUtility/MeshIntegrator.cs, Assets/UniGLTF/Runtime/MeshUtility/MeshIntegratorUtility.cs, Assets/UniGLTF/Runtime/MeshUtility/TriangleSeparator.cs, Assets/UniGLTF/Runtime/MeshUtility/TriangleSeparator.cs.meta, Assets/VRM/Editor/SkinnedMeshUtility/VRMMeshIntegratorUtility.cs, Assets/VRM/Editor/SkinnedMeshUtility/VrmMeshIntegratorWizard.cs, Assets/VRM10/Editor/MeshUtility/Vrm10MeshUtilityDialog.cs, Assets/VRM10/Runtime/Components/VRM10Object/VRM10ObjectFirstPerson.cs, Assets/VRM10/Runtime/MeshUtility/Vrm10MeshUtility.cs
#2169 の部品
`mesh bake` => `integrate > generate_firstperson_auto > split_by_blendshape`
という一連の処理です。
-  `generate_firstperson_auto` 整理
-  `split_by_blendshape` 追加
- undo の基本実装の追加
この次で Expression, SpringBone などへの影響を実装して完了予定です。
TODO: indexの調整だけで split を実装したので、未使用になった頂点を削除できる。
position, normal, uv, weight, joint, blendShape と indices への対応が必用。あとで。
=> [vrm1.0] impl mesh split by blendshape existence

Assets/UniGLTF/Editor/GltfImportMenu.cs, Assets/UniGLTF/Editor/GltfImportMenu.cs.meta, Assets/UniGLTF/Editor/MeshUtility/MeshUtilityDialog.cs, Assets/UniGLTF/Editor/TopMenu.cs, Assets/UniGLTF/Editor/TopMenuImplementation.cs.meta, Assets/UniGLTF/Editor/UniGLTF/ExportDialog/GltfExportWindow.cs, Assets/UniGLTF/Runtime/UniGLTF/PackageVersionPartial.cs, Assets/VRM/Editor/Format/VRMExporterWizard.cs, Assets/VRM/Editor/Format/VRMHumanoidNormalizerMenu.cs, Assets/VRM/Editor/Format/VRMImporterMenu.cs, Assets/VRM/Editor/SkinnedMeshUtility/VrmMeshIntegratorWizard.cs, Assets/VRM/Editor/SpringBone/VRMSpringBoneUtilityEditor.cs, Assets/VRM/Editor/VrmTopMenu.cs, Assets/VRM10/Editor/Components/VRM10Window.cs, Assets/VRM10/Editor/MeshUtility/MeshIntegrationTab.cs, Assets/VRM10/Editor/MeshUtility/Vrm10MeshUtilityDialog.cs, Assets/VRM10/Editor/Vrm10ExportDialog.cs, Assets/VRM10/Editor/Vrm10InstanceEditor.cs, Assets/VRM10/Editor/Vrm10TopMenu.cs, Assets/VRM10/Editor/VrmAnimationMenu.cs
- menu 名を関連クラスの `public const string MENU_NAME` にした(特に validate=true で２回同名で呼ぶところ)
- menu 表示名と dialog のタイトルを同じ文字列にした
=> menu 名と dialog 名を整理

Assets/UniGLTF/Editor/MeshUtility/MeshIntegrationTab.cs, Assets/UniGLTF/Runtime/MeshUtility/BoneNormalizer.cs, Assets/UniGLTF/Runtime/MeshUtility/GltfMeshUtility.cs, Assets/UniGLTF/Runtime/MeshUtility/MeshExtensions.cs, Assets/UniGLTF/Runtime/MeshUtility/MeshFreezer.cs, Assets/UniGLTF/Runtime/MeshUtility/MeshIntegrationGroup.cs, Assets/UniGLTF/Runtime/MeshUtility/MeshIntegrator.cs, Assets/VRM/Runtime/SkinnedMeshUtility/VrmMeshUtility.cs, Assets/VRM10/Runtime/MeshUtility/Vrm10MeshUtility.cs
#2119 (非原点 SkinnedMeshRenderer Weightあり・なし) の修正と、発見されたバグの修正
- FirstPerson 設定が無くても動くように renderer を収集
- freeze 後に avatar を作り直すと姿勢が崩れる問題の workaround
- integration の boneweight が無かった(typo)
=> [MeshUtility] 非原点 SkinnedMeshRenderer まわりの修正

Assets/VRM/Editor/VrmTopMenu.cs
閉じカッコに属性を付ける判定になりエラーになる。
エラーの有無とは別にメニューが無くなっている。
=> メニューの作業ミスを修正

Assets/VRM/Editor/Format/VRMEditorExporter.cs, Assets/VRM/Editor/Format/VRMHumanoidNormalizerMenu.cs, Assets/VRM/Runtime/SkinnedMeshUtility/VRMBoneNormalizer.cs, Assets/VRM_Samples/RuntimeExporterSample/VRMRuntimeExporter.cs
fixed #2201
```cs
animator.avatar = newAvatar
```
としたときに元の値を維持する？挙動があります。
そのため 旧avatar と newAvatar で元になる姿勢が異なる(例えば正規化)場合に姿勢が壊れます。
対策として、 Destory(Animator) して作り直します。
`v0.116` より前はヒエラルキーをコピーしていたため代入時の元の値を維持する挙動をたまたま回避できていたようです。
`v0.116` はコピーせずに同一のヒエラルキーで実行します。
=> avatar 代入時に姿勢が変わる対策

Assets/VRMShaders/GLTF/IO/Runtime/Texture/Importer/TextureFactory.cs
TextureFactoryにて所有権が譲渡されていないTextureが破棄されていないようなので、対策案を提出させていただきます。
例外発生などで`TransferOwnership` による所有権譲渡が実施されないまま、`ImporterContext.Dispose`が実施されるとTextureが破棄されないままになっていると思われます
=> TextureFactoryにて所有権が譲渡されていないTextureを破棄する

Assets/VRM10/Runtime/Migration/MeshUpdater.cs
nodeにmatrixを使用したVRM0.xのロードを実施すると "Exception: matrix with translation" が発生する問題がありましたため、対策案を提出させていただきます
- Migration後にnodeがmatrixとTRS両方保持することになって [こちら](https://github.com/vrm-c/UniVRM/blob/e3d4ea53e8002a60b8f13b607f21ba8359e61da2/Assets/VRM10/Runtime/IO/Vrm10ImportData.cs#L392) で `Exception: matrix with translation` が発生していました
- Migration時にTRS側が作成されているので、matrix側を除外するようにしています
- VRM10Viewerで [こちら](https://github.com/tsgcpp/UniVRM/blob/report_20240106/Tests/Models/vroid_a_0x_nodes_with_matrix/vroid_a_0x_nodes_with_matrix.vrm)のVRM0.x (nodeにmatrixを使用したVRM0.x) をロードすると再現します
=> nodeにmatrixを使用したVRM0.xのロードを実施すると "Exception: matrix with translation" が発生する問題を解消する

Assets/VRM10/Runtime/Components/Vrm10Instance/Vrm10Instance.cs
- Vrm10Instance生成後に非アクティブにしてそのままOnDestroy()が実施されるとエラーになるようなので、対策案を提出させていただきます
- 以下の流れでエラーになるようです
- `Vrm10Instance.OnDestory` がコールされた時点でGameObjectは破棄されている
- 非アクティブのままだと `m_runtime` が生成されておらず、その状態で`Vrm10Instance.OnDestory`が発生すると`Runtime`コールで `m_runtime` の生成が動いてしまう
- Vrm10Runtimeの生成はGameObjectや階層の編集が発生するため、`Cannot set the parent of the GameObject 'Runtime Control Rig' while its new parent 'VRM1' is being destroyed` のエラーが発生する
- https://github.com/tsgcpp/UniVRM/releases/tag/report_20240106 をcheckout
- `Assets/Report/Scenes/Report_ErrorWhenDestroyedWithoutEnabled_Vrm10Runtime.unity` を開いてPlayを実行
=> Vrm10Instance生成後に非アクティブにしてそのままOnDestroy()が実施された場合にエラーとなる問題の対策

Assets/VRM10/Runtime/Migration/MigrationVrmFirstPersonAndLookAt.cs
MeshAnnotationのmeshに-1が指定されているとNotImplementedExceptionが発生することを確認したため、その問題を回避案を提出させていただきます。
問題の流れは以下です。
- Migration時にmeshAnnotationsのmeshに-1が指定されているVRM0.xをロードする
- `glTFNode.node`の初期値 -1 と一致してしまいMeshがあるNodeとして扱われる
- Meshが存在しないNodeにMeshAnnotationsを設定しようとして [ここ](https://github.com/vrm-c/UniVRM/blob/e3d4ea53e8002a60b8f13b607f21ba8359e61da2/Assets/VRM10/Runtime/Components/VRM10Object/VRM10ObjectFirstPerson.cs#L125)に入り、`NotImplementedException` が発生する
```json
"meshAnnotations": [
{
"firstPersonFlag": "Auto",
"mesh": 0
},
{
"firstPersonFlag": "Auto",
"mesh": -1
},
{
"firstPersonFlag": "Auto",
"mesh": 2
}
]
```
UniVRM以外のツールでVRM0.xで上記のようなVRMが作られる場合が有るようでした。
- …
=> VRM0.xでMeshAnnotationsのmeshに-1が指定されていると一人称メッシュ作成時にNotImplementedExceptionが発生する問題を回避する

Assets/VRM10/Runtime/IO/Vrm10ImportData.cs
タイトルの通りのエラーを確認しましたため、対策案を提出させていただきます。
2つの事象があり若干関連がありましたため、まとめて提出させていただきます。
以下の条件が揃ったVRM0.xを読み込むとエラーになりました
- `meshes[x].primitives[x]`にてattributesのbufferViewは連続であるが、indicesのbufferViewがprimitivesの順番で連続ではない
- `accessors[x].byteOffset`が指定されていない
この場合、indicesのbufferViewをaccessor経由で読み込む際に、本来はInteger型ではない領域までInteger型として読み込んでしまい、`ArgumentException: Index buffer element #5088 (value 1090921693) is out of bounds; mesh only has 4083 vertices.`のようなエラーが発生していました
- glTFAccessor.byteOffsetは `int?` でOptional(Nullable)のため、`accessors[x].byteOffset`が指定されていない場合はnullとなる
- `int?` と `int` の演算は `int?`になる
- null + 1 = null となる (C#の仕様)
- null == null は true
- `var start = firstView.byteOffset + firstAccessor.byteOffset;` で …
=> attributesのbufferViewは連続であるが、indicesのbufferViewがprimitivesの順番で連続ではないVRM0.xをロードするとエラーになる問題の対策

Assets/VRM10/Runtime/IO/Vrm10Importer.cs
- UniVRM version: `v0.117.0`
ColliderGroupsはあるがColliderが全く存在しない場合にVRM0.xの読み込みで[こちらの行](https://github.com/vrm-c/UniVRM/blob/88f2c11d5cff8d3ebb2e25acf67521a9feb9be3d/Assets/VRM10/Runtime/IO/Vrm10Importer.cs#L590)にて`ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
` のエラーが発生するを確認しましたため、その対応案を提出します。
以下のように`VRMSpringBone`の`ColliderGroups`に`VRMSpringBoneColliderGroup`が指定されているが、その `Colliders`の要素数が0だった場合が該当します。
上記の条件に合致すると Vrm10Importer.csの518行目の `if (gltfVrmSpringBone.Colliders != null)` 内の処理が実施されず、結果的に `VRM10SpringBoneColliderGroup`の作成とそのプロパティ `Colliders` への登録が実施されないことで、後のSpringBoneの読み込みで `ArgumentOutOfRangeException` に繋がったようです。
対応としては、glTF内にColliderがなくてもColliderGroupがあれば …
=> ColliderGroupsはあるがColliderが全く存在しない場合にVRM0.xの読み込みで発生するエラーを解消する

Assets/VRM10/Runtime/IO/Vrm10Importer.cs
- UniVRM version: `v0.117.0`
非Skinned MeshかつMeshAnnotationが指定されていないメッシュがHead直下にある場合にLayerが設定されない現象を確認しましたため、その対応案を提出させていただきます。
`instance.Vrm.FirstPerson.SetupAsync` を実施した場合に、`SkinnedMeshRenderer`の場合はLayerが設定されますが、`MeshRenderer`の場合はLayerが適用されていませんでした。
MeshAnnotationを `auto` として適用する処理の対象コンポーネントが`SkinnedMeshRenderer`になっており、`MeshRenderer`が対象からはずれていることが原因と思われます。
- https://github.com/tsgcpp/UniVRM/releases/tag/report_20240106 をcheckout
- `Assets/Report/Scenes/Report_MeshAnnotationAutoToMeshUnderHead_Vrm10LoadWithFirstPerson.unity` を開いてPlayを実行
- VRMロード後に`instance.Vrm.FirstPerson.SetupAsync` を実施しています
Head直下のメッシュのGameObjectのLayerが以下のように`Default`のままになっていることが確認できます。GameViewにレンダリングするCameraのCullingMaskは `VRMThirdPersonOnly` のみを指定しています。
=> 非Skinned MeshかつMeshAnnotationが指定されていないメッシュがHead直下にある場合にLayerが設定されない現象を解消する

Assets/UniGLTF/Runtime/UniGLTF/RuntimeGltfInstance.cs
RuntimeGltfInstance.OnDestroy時のDebug.Logの削除を提案させていただきます。
ロードしたVRMのインスタンスが破棄されたときに発生するログのようですが、情報が `UnityResourceDestroyer.OnDestroy` の文字列とスタックトレースのみで用途があまりなさそうと思ったため、スタックトレース生成を含めたログ出力を回避するために削除を提案させていただきます。
=> [提案] RuntimeGltfInstance.OnDestroy時のDebug.Logを削除する

Assets/VRM/Runtime/FirstPerson/VRMFirstPerson.cs
fixed #2218
VRMFirstPerson の参照が無効な場合にスキップする。
=> VRMFirstPerson.CopyTo skip null

Assets/UniGLTF/Runtime/MeshUtility/MeshIntegrator.cs
fixed #2233
おそらく UniVRM 内で100以外の値を使うことは無い。
=> [MeshUtility] 統合時のblendshapeweight定数の修正

Assets/UniGLTF/Runtime/MeshUtility/MeshFreezer.cs
fixed #2236 
- 一般的な SkinningModel
- BoneWeight の無い BlendShape のみのモデル
で動作を確認しました。
`0.116` から発生している模様。
hierarchy の正規化が bake する前から後に移動？
=> hierarchy にスケーリングがある場合の blend shape の正規化修正

Assets/UniGLTF/Runtime/UniGLTF/RuntimeGltfInstance.cs, Assets/VRM10/Runtime/Components/VRM10Object/VRM10ObjectFirstPerson.cs, Assets/VRM10_Samples/VRM10FirstPersonSample/VRM10RuntimeLoader.cs
fixed #2209 
- headless モデルのリソース破棄
- auto で headless を作成する必要が無かった場合は both
- firstperson sample の ShowMesh の呼び方
#2209 の修正が主でしたが、関連して問題がある部分も修正しました。
=> [VRM10] FirstPerson の修正

Assets/VRM10/Runtime/Components/SpringBone/VRM10SpringBoneColliderGroupDrawer.cs, Assets/VRM10/Runtime/Components/SpringBone/VRM10SpringBoneColliderGroupDrawer.cs.meta, Assets/VRM10/Runtime/IO/Vrm10Importer.cs, Assets/VRM10/Runtime/Migration/MigrationVrmSpringBone.cs
=> [vrm10] SpringBone の inspector 修正など

Assets/VRM10/Editor/VRM10ExportSettings.cs, Assets/VRM10/Editor/Vrm10ExportDialog.cs
fixed #2119
memo  
> blendshape のみの bake をするには、
binding行列とtransformの状態が一致しているなど、
前提条件が要りそうなのだが
細かいことは抜きで簡単実装でよいかもしれない。
とりあえず vrm-0.x と同じ rotation & scale および blendShape をまとめて bake する機能を作った
=> [vrm-1.0] bake 機能を実装

.github/workflows/create-unitypackage.yml, Assets/UniGLTF/Editor/TestRunner.meta, Assets/UniGLTF/Editor/TestRunner/TestRunner.cs, Assets/UniGLTF/Editor/TestRunner/TestRunner.cs.meta, Assets/UniGLTF/Editor/TopMenu.cs
- `-runEditorTests` が廃止されているので自分でテストランナーを定義して `-executeMethod` する必要がある
- ただし自由度が上がったので、終了コードをどう返すかなどの設計がしやすくなった
- 今回は失敗したら終了コード `1` を返すようにした
コミットログが汚いのでこれは squash merge します
=> Create UnityPackage Action でとりあえず EditMode Tests まで走らせる

Assets/UniGLTF/Runtime/UniGLTF/IO/ExtensionSupportFlags.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/ExtensionSupportFlags.cs.meta, Assets/UniGLTF/Runtime/UniGLTF/IO/GltfData.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/ImporterContext.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/TextureIO/GltfTextureImporter.cs
Y 軸反転された basisu テクスチャを含む glTF/VRM/VRM10 ファイルを、Runtime でのみインポート可能にします。
| Supporting basisu texture  | Editor | Runtime |
|--|--|--|
| regular | - | - |
| Y-Flipped | - | ✅ |
```csharp
public class LoadYFlippedBasisuModel : MonoBehaviour
{
async void Start()
{
var path = @"C:\foo\bar\baz.gltf";
using var data = new AutoGltfFileParser(path).Parse();
data.ExtensionSupportFlags.ConsiderKhrTextureBasisu = true;
data.ExtensionSupportFlags.IsAllTexturesYFlipped = true;
using var loader = new ImporterContext(data, materialGenerator: RenderPipelineMaterialDescriptorGeneratorUtility.GetValidGLTFMaterialDescriptorGenerator());
var model = await loader.LoadAsync(new RuntimeOnlyAwaitCaller());
model.ShowMeshes();
}
}
```
=> Define ExtensionSupportFlags for limited supporting KHR_texture_basisu

Assets/UniGLTF/Editor/UniGLTF/UniGLTFPreference.cs
Unity 2023.1以降のバージョンでPlayerSettings.GetScriptingDefineSymbolsForGroup()系の関数がObsoleteになり、次の警告が発生していました。
```
Assets\UniGLTF\Editor\UniGLTF\UniGLTFPreference.cs(109,27): warning CS0618: 'PlayerSettings.GetScriptingDefineSymbolsForGroup(BuildTargetGroup)' is obsolete: 'Use GetScriptingDefineSymbols(NamedBuildTarget buildTarget) instead'
Assets\UniGLTF\Editor\UniGLTF\UniGLTFPreference.cs(116,27): warning CS0618: 'PlayerSettings.GetScriptingDefineSymbolsForGroup(BuildTargetGroup)' is obsolete: 'Use GetScriptingDefineSymbols(NamedBuildTarget buildTarget) instead'
Assets\UniGLTF\Editor\UniGLTF\UniGLTFPreference.cs(117,13): warning CS0618: 'PlayerSettings.SetScriptingDefineSymbolsForGroup(BuildTargetGroup, string)' is obsolete: 'Use SetScriptingDefineSymbols(NamedBuildTarget buildTarget, string …
```
=> Unity2023.1以降でGetScriptingDefineSymbolsForGroup系APIがObsolete警告を出すのに対応

Assets/VRM/Runtime/BlendShape/PreviewSceneManager.cs, Assets/VRM/Runtime/FirstPerson/VRMFirstPersonCameraManager.cs, Assets/VRM/Runtime/LookAt/LookAtTargetSwitcher.cs, Assets/VRM10/Runtime/Components/Expression/Preview/PreviewSceneManager.cs, Assets/VRM10/Runtime/FastSpringBone/System/FastSpringBoneService.cs, Assets/VRM10_Samples/VRM10FirstPersonSample/VRM10CanvasManager.cs, Assets/VRM10_Samples/VRM10Viewer/VRM10ViewerUI.cs, Assets/VRM_Samples/FirstPersonSample/CanvasManager.cs, Assets/VRM_Samples/SimpleViewer/ViewerUI.cs
Unity 2023.1以降のバージョンでUnityEngine.Object.FindObjectsOfType系APIがObsoleteになり、次の警告が発生していました。
```
Assets/VRM10_Samples/VRM10Viewer/VRM10ViewerUI.cs(250,24): warning CS0618: 'Object.FindObjectOfType<T>()' is obsolete: 'Object.FindObjectOfType has been deprecated. Use Object.FindFirstObjectByType instead or if finding any instance is acceptable the faster Object.FindAnyObjectByType'
Assets/VRM10_Samples/VRM10Viewer/VRM10ViewerUI.cs(208,31): warning CS0618: 'Object.FindObjectsOfType<T>()' is obsolete: 'Object.FindObjectsOfType has been deprecated. Use Object.FindObjectsByType instead which lets you decide whether you need the results sorted or not.  FindObjectsOfType sorts the results by InstanceID but if you do not need this using FindObjectSortMode.None is considerably faster.'
``` …
=> Unity2023.1以降でFindObjectsOfType系APIがObsolete警告を出すのに対応

Assets/VRMShaders/VRM10/MToon10/Runtime/MToonOutlineRenderPass.cs
代わりにCommandBuffer.DrawRendererList()を使うようにしました。
これに渡す引数を生成するScriptableRenderContext.CreateRendererList()メソッドには、2種類のオーバーロードが存在します。
1. ScriptableRenderContext.CreateRendererList(Rendering.RendererUtils.RendererListDesc desc);
2. ScriptableRenderContext.CreateRendererList(Rendering.RendererListParams param)
このPRでは `2` を選択しました。`1` はUnity 2021.3にも存在するという利点がありますが、 引数の組み立てが複雑だと感じたため避けました。
=> Unity2023.1以降でUnityScriptableRenderContext.DrawRenderers()がObsolete警告を出すのに対応

Assets/VRM/Runtime/BlendShape/PreviewSceneManager.cs, Assets/VRM/Runtime/FirstPerson/VRMFirstPersonCameraManager.cs, Assets/VRM/Runtime/LookAt/LookAtTargetSwitcher.cs, Assets/VRM10/Runtime/Components/Expression/Preview/PreviewSceneManager.cs, Assets/VRM10/Runtime/FastSpringBone/System/FastSpringBoneService.cs, Assets/VRM10_Samples/VRM10FirstPersonSample/VRM10CanvasManager.cs, Assets/VRM10_Samples/VRM10Viewer/VRM10ViewerUI.cs, Assets/VRM_Samples/FirstPersonSample/CanvasManager.cs, Assets/VRM_Samples/SimpleViewer/ViewerUI.cs
私が以前提出した PR https://github.com/vrm-c/UniVRM/pull/2285 で、コンパイルエラーのリグレッションを発生させてしまいました。そちらの修正です。お手数おかけしてしまい大変申し訳ありません。
FindObjectsBy系のAPIは、UniVRMがサポートしているUnityのうち、次の範囲のバージョンには存在していませんでした。
- 2021.3.0～2021.3.17
- 2022.1.0～2022.1.24
- 2022.2.0～2022.2.4
そのため、該当するバージョンのUnityではコンパイルエラーが発生していました。UNITY_2022_3_OR_NEWERで分岐することで、旧APIと新APIを安全に選択するようにしました。
厳密にはUNITY_2022_2_5_OR_NEWERを用いたいですが、そのようなシンボルは存在していませんでした。
以前の PR https://github.com/vrm-c/UniVRM/pull/2285 では、Unity 2021.3のドキュメントや2021.3.27f1でメソッドが存在したことで、2021.3以降のバージョンにはすべて存在していると勘違いしてしまっていました。
=> Unity2022.2.4以下と2021.3.17以下でFindObjectBy系APIが存在しないのに対応

Assets/VRM10/Runtime/FastSpringBone/System/UpdateFastSpringBoneJob.cs
https://github.com/vrm-c/UniVRM/issues/2291
について提案させていただきます。ご検討いただければと思います。
=> Capsuleの当たり判定を修正 #2291

Assets/VRM10/Runtime/IO/Vrm10.cs
応用的な Vrm10 ロードをする際には、Byte や Path からだけではないロードをしたい場合がある。
とはいえ Vrm10.* は Easy な API に徹したいので、むやみやたらに API を定義したいわけではない。
そこで `GltfData` を受け取る API を定義する。
=> Add Vrm10.LoadGltfDataAsync API for advanced usage.

Assets/VRM10/Runtime/IO/Vrm10.cs, Assets/VRM10/Tests/Vrm10ApiTests.cs, Assets/VRM10/Tests/Vrm10ApiTests.cs.meta
https://github.com/vrm-c/UniVRM/pull/2296 のマージ後に見てください。
- `Vrm10.LoadPathAsync`
- `Vrm10.LoadBytesAsync`
の使用時に、選択された `IAwaitCaller` によってはファイルパースの実行をメインスレッドではなくスレッドプール等で働くようにします。
=> Run parsing of vrm10 files on a thread pool.

Assets/VRM10/Runtime/Migration/Materials/MigrationMToonMaterial.cs, Assets/VRM10/Runtime/Migration/Materials/Vrm0XMToonValue.cs, Assets/VRM10/Runtime/VRM10.asmdef, Assets/VRMShaders/VRM10/MToon10/Editor/EditorMenu.cs, Assets/VRMShaders/VRM10/MToon10/Editor/EditorMenu.cs.meta, Assets/VRMShaders/VRM10/MToon10/Runtime/Extensions/MaterialExtensions.cs, Assets/VRMShaders/VRM10/MToon10/Runtime/MToon0X.meta, Assets/VRMShaders/VRM10/MToon10/Runtime/MToon0X/MToon0XDefinition.cs, Assets/VRMShaders/VRM10/MToon10/Runtime/MToon0X/MToon0XDefinition.cs.meta, Assets/VRMShaders/VRM10/MToon10/Runtime/MToon0X/MToon0XEnums.cs, Assets/VRMShaders/VRM10/MToon10/Runtime/MToon0X/MToon0XEnums.cs.meta, Assets/VRMShaders/VRM10/MToon10/Runtime/MToon0X/MToon0XUtils.cs, Assets/VRMShaders/VRM10/MToon10/Runtime/MToon0X/MToon0XUtils.cs.meta, Assets/VRMShaders/VRM10/MToon10/Runtime/MToon0X/MToon0XUtilsGetter.cs, Assets/VRMShaders/VRM10/MToon10/Runtime/MToon0X/MToon0XUtilsGetter.cs.meta, Assets/VRMShaders/VRM10/MToon10/Runtime/MToon0X/MToon0XUtilsVersion.cs, Assets/VRMShaders/VRM10/MToon10/Runtime/MToon0X/MToon0XUtilsVersion.cs.meta, Assets/VRMShaders/VRM10/MToon10/Runtime/MToon10Context.cs, Assets/VRMShaders/VRM10/MToon10/Runtime/MToonMaterialMigrator.cs, Assets/VRMShaders/VRM10/MToon10/Runtime/MToonMaterialMigrator.cs.meta
`VRM/MToon` シェーダの Material アセットを `VRM10/MToon10` シェーダにマイグレーションします。
これは Material アセットに完結した機能で、手動セットアップ時等に便利です。
ついでに
- VRM0X -> VRM10 のマイグレーションのバグを修正
- VRM10 -> MToon0X の asmdef 参照を削除
=> Add MToon0X -> MToon10 material migration command

Assets/UniGLTF/Runtime/UniGLTF/IO/MeshIO/BlendShapeExporter.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/MeshIO/MeshExporter_SharedVertexBuffer.cs
- Boundsの計算にAggregate()を使用している箇所を変更 (関連: #1505 )
- mesh.vertices, mesh.normalsへの不要なアクセスの削減
- mesh.GetBlendShapeFrameVertices()に渡す配列を使い回すようにする
=> Improve export of BlendShapes

Assets/VRMShaders/VRM10/MToon10/Runtime/MToonOutlineRenderPass.cs
Universal RPパッケージ 17以降でScriptableRenderPass.Execute()がObsoleteになりました。
https://github.com/Unity-Technologies/Graphics/blob/515c4d9a59b7a669bd7a0a33726d4e8ae8d0c59a/Packages/com.unity.render-pipelines.universal/Runtime/Passes/ScriptableRenderPass.cs#L660-L666
それが原因で、Execute()メソッドをオーバーライドをしている箇所がObsolete警告を出すようになりました。同様に[Obsolete]アトリビュートをつけることで警告を回避するようにしました。
本来なら「Universal RP 17以降が使われている場合[Obsolete]アトリビュートをつける」という方式で警告を回避したいですが、それは不可能なようでした。Universal RP 17はUnity 6000.0.0以降で有効なバージョンなため、代わりにUNITY_6000_0_OR_NEWERで判定するようにしました。
また、Obsoleteになってしまった部分の移行先であるRenderGraph版の実装追加も必要だとは思うのですが、このPull Requestではスコープ外とさせてください。
=> Universal RP 17以降でScriptableRenderPass.Execute()がObsolete警告を出すのに対応

Assets/VRM10/Runtime/IO/Vrm10Exporter.cs
VRM1.0のモデルエクスポート時に、ColliderGroupに入力したNameが引き継がれないので修正しています。
=> Fix collider group name export

Assets/UniGLTF/Runtime/UniGLTF/IO/ExtensionSupportFlags.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/ImporterContext.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/TextureIO/GltfTextureImporter.cs
glTF の定義に準じた `KHR_texture_basisu` を含むモデル通常の Runtime Load 関数でデフォルトでロードできるようにします。
ただし現状未実装なので例外が出ます。
Y 軸反転したものは、明示的にフラグを立てて `LoadGltfDataAsync` を用いてロードする必要があります。
=> load KHR_texture_basisu as default (but not implemented now)

Assets/VRMShaders/GLTF/IO/Runtime/Texture/Importer/KtxTextureDeserializer.cs
KtxTextureDeserializer .LoadTextureAsync()はcom.unity.cloud.ktxが存在していない場合にそのままnullを返す実装に切り替わりますが、そのままだとasyncメソッドで一度もawaitしていないので次のようなコンパイラの警告が出てしまっていました。
```
Assets/VRMShaders/GLTF/IO/Runtime/Texture/Importer/KtxTextureDeserializer.cs(14,38): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.
```
pragmaを用いて警告を抑制するようにしました。
=> com.unity.cloud.ktxが無い場合にasyncメソッドでawaitが無い警告が出るのを抑制

Assets/VRM10/Editor/Components/SpringBone/VRM10SpringBoneColliderDrawer.cs
**概要**
同じボーンに複数のVRM10SpringBoneColliderが存在する場合に、インスペクターから目的のVRM10SpringBoneColliderを探して選択し易くするボタンの追加です。
#2306 の機能強化になります。
**変更前**
Unity標準のオブジェクトピッカーでVRM10SpringBoneColliderを選択しようとした場合、表示されるのはボーンの中で一番上にアタッチされているVRM10SpringBoneColliderだけです。
下記の画像の例では、chestボーンに3つのコライダが存在しますが、オブジェクトピッカーにはchestが1つしか表示されません。このchestを選択した場合、chestボーンの中で一番上に存在するSphereが選択されます。Capsule1やCapsule2を選択するには、ボーンのインスペクタを開いてCapsule1やCapsule2のスクリプトを一番上に移動してから再度選択する必要があり、手間がかかります。
**変更後**
オブジェクトフィールドに表示されているボーンに複数のコライダが存在する場合、リセレクトボタンを表示します。
ボタンを押下すると下記のようなウィンドウが表示され、ボーンの中の任意のコライダが選択できます。
=> Improved selection of VRM10SpringBoneCollider on inspector

Assets/VRM10/Runtime/IO/Vrm10Exporter.cs
次の警告が発生していました。
```
UniVRM/Assets/VRM10/Runtime/IO/Vrm10Exporter.cs(384,21): warning CS0162: Unreachable code detected
```
冗長なbreakが存在していたため、削除しました。
=> コライダーエクスポート時の "Unreachable code detected" 警告に対応

Assets/UniGLTF/Runtime/MeshUtility/MeshExtensions.cs, Assets/UniGLTF/Runtime/MeshUtility/MeshFreezer.cs
fixed #2327
簡単になるように処理順をみなおし。
```cs
var mesh = src.sharedMesh.Copy(false, ".baked");
src.BakeMesh(mesh);
CopyBlendShapes(src, mesh); // matrix は適用しない
var m = Matrix4x4.TRS(Vector3.zero, src.transform.rotation, Vector3.one);
mesh.ApplyMatrixAlsoBlendShapes(m); // 最後の一回だけまとめて matrix を適用する
```
=> fix blendshape bake.

.github/ISSUE_TEMPLATE/------bug-report-ja--.md, .github/ISSUE_TEMPLATE/-----feature-request.md, .github/ISSUE_TEMPLATE/bug-report-------en--.md, .github/workflows/close-expired-issues.yml
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3
ついでに issue template も更新。
=> checkout@v3 をcheckout@master に変更など

.github/workflows/label_checker.yml
その PullRequest に Breaking Changes が含まれるかどうかのラベルの付与を促します。
`Breaking changes` か `Non breaking changes` のラベルが付与されているかどうかを見ます。
ここでいう `Breaking changes` とは、UniVRM を利用して Runtime Import を行っている Application 開発者にとっての Breaking changes かどうかをいまのところは指します。
=> Add PullRequest Label checker

Assets/UniGLTF/Runtime/MeshUtility/MeshAttachInfo.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/NodeImporter.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/gltfExporter.cs, Assets/VRM/Runtime/Extensions/VrmHumanoidExtensions.cs, Assets/VRM10/Runtime/IO/Model/ModelExporter.cs, Assets/VRM10/Runtime/IO/Vrm10Exporter.cs
=> [0.x][1.0] SkinnedMeshRenderer.bones に null が含まれていてもExportできる

Assets/VRMShaders/VRM10/MToon10/Resources/VRM10/vrmc_materials_mtoon_urp.shader
プロジェクトに URP が未導入の場合に MToon10 の URP 版シェーダがコンパイルエラーを Log に出力するのを抑制。
Unity 2021 からの機能を利用
https://docs.unity3d.com/2021.3/Documentation/Manual/SL-PackageRequirements.html
=> Suppress shader compile errors when URP is not imported.

Assets/UniGLTF/Runtime/UniGLTF/IO/ExtensionSupportFlags.cs, Assets/VRM10/Runtime/IO/Vrm10Data.cs
VRM 0.X モデルを VRM 1.0 モデルにマイグレーションするとき、もともとの `GltfData` に与えられていた `ExtensionSupportFlags` が初期値に戻ってしまう問題を解決します
=> Maintain extension support flags when migrating a vrm0.x model.

Assets/VRM10/Editor/Components/SpringBone/VRM10SpringBoneDrawer.cs, Assets/VRM10/Editor/Components/SpringBone/VRM10SpringBoneDrawer.cs.meta
fixed #2357 
対象は `class Vrm10InstanceSpringBone.Spring` です。
一般クラスなので CustomPropertyDrawer でエディタをカスタムし、ボタンを追加しました。
```cs
using static Vrm10InstanceSpringBone;
[CustomPropertyDrawer(typeof(Spring))]
```
=> root の子孫に再帰的に joint を設定するボタン

Assets/UniGLTF/Editor/UniGLTF/ScriptedImporter/TextureExtractor.cs
とりえあずエラー回避。
Alicia では以下のメッセージが出ます。
`Exception: UnityEngine.Texture:Sphere is not converted` 
Assets\VRM\Runtime\IO\MaterialIO\URP\Import\UrpVrmMaterialDescriptorGenerator.cs
> mtoon URP "MToon" shader is not ready. import fallback to unlit
=> URP プロジェクトで matcap を含むモデルを Editor import するとエラーになるのを回避(暫定)

Assets/Development.meta, Assets/Development/Editor.meta, Assets/Development/Editor/Development.Editor.asmdef, Assets/Development/Editor/Development.Editor.asmdef.meta, Assets/Development/Runtime.meta, Assets/Development/Runtime/Development.asmdef, Assets/Development/Runtime/Development.asmdef.meta, Assets/Development/Settings.meta, Assets/Development/Settings/URP.asset, Assets/Development/Settings/URP.asset.meta, Assets/Development/Settings/URP_Renderer.asset, Assets/Development/Settings/URP_Renderer.asset.meta, Assets/UniversalRenderPipelineGlobalSettings.asset, Assets/UniversalRenderPipelineGlobalSettings.asset.meta, ProjectSettings/GraphicsSettings.asset
開発プロジェクトのデフォルトを URP に変更します。
ただし現時点ではサンプルシーンなどに変更は入れていないため、URP では利用できず、Built-in 用のままです。
`Assets/Development` パッケージは公開用ではなく、UniVRM 開発プロジェクトの管理用に利用されることが期待されます。
たとえばバージョンインクリメントユーティリティはここにある方が望ましいと考えます。
=> Use URP as default in development project.

Assets/VRM10/Editor/Components/SpringBone/VRM10SpringBoneJointEditor.cs
https://vrm.dev/univrm1/vrm1_tutorial/springbone/#spring-%E3%81%AB-joint-%E3%82%92%E8%BF%BD%E5%8A%A0%E3%81%99%E3%82%8B
未登録の孤立Jointの警告。
バグで消えなくなっていた。
=> fix VRM10SpringBoneJointEditor

Assets/UniGLTF/Editor/UniGLTF/ScriptedImporter/GltfScriptedImporterBase.cs, Assets/UniGLTF/Editor/UniGLTF/ScriptedImporter/ImporterRenderPipelineTypes.cs, Assets/UniGLTF/Editor/UniGLTF/ScriptedImporter/ImporterRenderPipelineTypes.cs.meta, Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/Import/MaterialDescriptorGeneratorUtility.cs, Assets/VRM/Runtime/IO/MaterialIO/VrmMaterialDescriptorGeneratorUtility.cs, Assets/VRM10/Editor/ScriptedImporter/VrmScriptedImporter.cs, Assets/VRM10/Editor/ScriptedImporter/VrmScriptedImporterImpl.cs, Assets/VRM10/Runtime/IO/Material/Vrm10MaterialDescriptorGeneratorUtility.cs
ScriptedImporter に対応する glTF と VRM1.0 の Editor Asset において、RenderPipeline の自動選択を用意し、デフォルトの挙動としました。
VRM 0.X の Editor Asset は ScriptedImporter ではなく AssetPostprocessor であるため、従来挙動通り RenderPipeline は自動選択とします。
=> glTF/VRM1.0 ScriptedImporters can detect the project's RenderPipeline. or a user can select manually.

Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/BuiltInRP/Import/BuiltInGltfMaterialDescriptorGenerator.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/BuiltInRP/Import/Materials/BuiltInGltfDefaultMaterialImporter.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/Import/IMaterialDescriptorGenerator.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/URP/Import/Materials/UrpGltfDefaultMaterialImporter.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/URP/Import/Materials/UrpGltfPbrMaterialImporter.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/URP/Import/UrpGltfMaterialDescriptorGenerator.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/MaterialIO/URP/ShaderUtil/Lit/UrpLitContext.cs, Assets/VRM/Runtime/IO/MaterialIO/BuiltInRP/Import/BuiltInVrmMaterialDescriptorGenerator.cs, Assets/VRM/Runtime/IO/MaterialIO/URP/Import/UrpVrmMaterialDescriptorGenerator.cs, Assets/VRM10/Runtime/IO/Material/BuiltInRP/Import/BuiltInVrm10MaterialDescriptorGenerator.cs, Assets/VRM10/Runtime/IO/Material/URP/Import/UrpVrm10MaterialDescriptorGenerator.cs
`UrpGltfDefaultMaterialImporter` を glTF 仕様通りに実装します。
一点、破壊的変更として
`IMaterialDescriptorGenerator` の `GetGltfDefault` 関数に `string materialName = null` 引数を加えました。
カスタムしたシェーダをアプリケーションで使用したい用途を持つような、
`IMaterialDescriptorGeneartor` を独自に実装しているユーザに影響があります。
=> Implements glTF default material importer at URP

Assets/UniGLTF/Runtime/UniGLTF/IO/ExportingGltfData.cs
テクスチャが含まれていないVRMファイルを出力するとBufferのByteLengthの値が正しく出力されない問題を修正しました。
**Mesh**や**Texture**に関わるBufferを出力している`ExtendBufferAndGetView`についてはByteLengthに対して値を挿入し更新していますが、**Skin**に関わるBufferを出力している`AppendToBuffer`についてはBufferLengthの更新を行っていませんでした。
そのため、テクスチャデータの含まれないVRMファイルを出力するとmeshのBufferの長さのみがByteLengthに書き込まれます。
このとき出力されるデータはSkinに関するBufferViewのoffsetの値がBufferのByteLenghの値を超過するため、gltfとしてはInvaliedな状態になります。
この問題を解決するため、`AppendToBuffer`においてもByteLengthを更新する処理を追加しました。
https://github.com/vrm-c/UniVRM/blob/98934f6575249aa56eb0e96f7e015cb75c50d0f3/Assets/UniGLTF/Runtime/UniGLTF/IO/ExportingGltfData.cs#L35
=> テクスチャの含まれないVRMのExport時、Buffer ByteLentghが正しく出力されない問題を修正しました。

Assets/UniGLTF/Tests/UniGLTF/UniGLTFTests.cs, Assets/VRM10/Runtime/IO/Material/URP/Export.meta, Assets/VRM10/Runtime/IO/Material/URP/Export/UrpVrm10MaterialExporter.cs, Assets/VRM10/Runtime/IO/Material/URP/Export/UrpVrm10MaterialExporter.cs.meta, Assets/VRM10/Runtime/IO/Material/Vrm10MaterialExporterUtility.cs, Assets/VRM10/Tests/LoadTests.cs
vrm-1.0 の sparse と bindMatrix をバッファーに追加するときに通る関数で問題が起きていたぽい。
後続に image のバッファー追加があると上書きされて顕在化しない様子。
テストの都合で UrpVrm10MaterialExporter の placeholder だけ追加しました。
#2413 の有無によりテストの成否が変化することを確認できました。
exporter の buffer 周りのインタフェースがよろしくない(間違えやすい)ので、
リファクタリングしたいところ。
=> [vrm1] mesh export 時の byteLength 確認テストを追加

Assets/VRM/Runtime/IO/VRMExporter.cs, Assets/VRM/Runtime/IO/VRMImporterContext.cs, Assets/VRM10/Runtime/IO/ExpressionExtensions.cs, Assets/VRM10/Runtime/IO/Model/ModelExporter.cs, Assets/VRM10/Runtime/IO/Vrm10Exporter.cs, Assets/VRM10/Runtime/IO/Vrm10Importer.cs
fixed #2434
fixed #1980
export 時の renderer の export 基準を徹底した。
```cs
x.gameObject.activeInHierarchy && x.TryGetComponent<Renderer>(out var renderer) && renderer.enabled
```
関連して firstPerson.annotations と expression.binds の mesh/node が連動するのだけど、
残るバグがあった。
既存のモデルに firstPerson.annotations と expression.binds の無効な参照が残っている場合向けに
importer のチェックを追加した。
=> [exporter] renderer の export しない基準 GameObject.active / Renderer.enabled を修正

Assets/UniGLTF/Runtime/SpringBoneJobs/InputPorts/FastSpringBoneBuffer.cs
tail の初期位置が原点から始まって開始時にはねる。
tail の初期化経路が変わったからかもしれない。
#2440 `v0.126` は関係あるかもしれないが、別件かもしれない。
=> springbone 初期化の修正。

Assets/UniGLTF/Editor/UniGLTF.Editor.asmdef
Hi, I'm the maintainer of https://github.com/khronosgroup/unitygltf. We've got some reports of incompatibility when both UnityGLTF and UniGLTF are in the same project, leading to users believing that either project is broken while they're not.
This PR builds on
- https://github.com/vrm-c/UniVRM/issues/1576
and makes UniGLTF play nice with UnityGLTF and glTFast in the same project.
With this PR in place, all three can co-exist and will all be available as importer overrides.
Before this PR, users had to manually add `UNIGLTF_DISABLE_DEFAULT_GLB_IMPORTER` and `UNIGLTF_DISABLE_DEFAULT_GLTF_IMPORTER` to their scripting settings which was confusing – with this PR it's automatic. And if neither glTFast nor UnityGLTF are present, there is no change in behaviour either.
=> add version defines so that UniGLTF, UnityGLTF and glTFast can co-exist

Assets/UniGLTF/Editor/MeshUtility/MeshUtilityDialog.cs, Assets/UniGLTF/Runtime/MeshUtility/BoneNormalizer.cs, Assets/UniGLTF/Runtime/MeshUtility/GltfMeshUtility.cs, Assets/UniGLTF/Runtime/MeshUtility/MeshFreezer.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/GltfExportSettings.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/gltfExporter.cs, Assets/VRM/Editor/Format/VRMEditorExporter.cs, Assets/VRM/Editor/Format/VRMExportSettings.cs, Assets/VRM/Editor/Format/VRMHumanoidNormalizerMenu.cs, Assets/VRM/Editor/VrmTopMenu.cs, Assets/VRM/Runtime/SkinnedMeshUtility/VRMBoneNormalizer.cs, Assets/VRM/Runtime/SkinnedMeshUtility/VrmMeshUtility.cs, Assets/VRM10/Editor/VRM10ExportSettings.cs, Assets/VRM10/Editor/Vrm10ExportDialog.cs, Assets/VRM10/Runtime/MeshUtility/Vrm10MeshUtility.cs, Assets/VRM_Samples/RuntimeExporterSample/VRMRuntimeExporter.cs
fixed #2465
blendshapeを変化させた状態で bake したときに、
最初に 0 クリアすることで base mesh が意図したものではなく、
すべて 0 のもになる。
かつ、ループが進むごとに変化状態に復帰する bug。
- `0.x`, `1.0` 
- すべての blendshape が 0 じゃない
- export 時に pose_freeze オプション
で発動
=> [exporter][blendshape][bake] 基準メッシュバグ

Assets/VRM/Runtime/SpringBone/Jobs/Vrm0XFastSpringBoneRuntime.cs, Assets/VRM10/Runtime/Components/Vrm10Runtime/Vrm10FastSpringboneRuntime.cs, Assets/VRM10/Runtime/IO/Vrm10Importer.cs
多段に NullReferenceException の可能性があるのでちょっと整理する。
|runtime|service|combiner|combined|
|-|-|-|-|
|Vrm0XFastSpringboneRuntime|ok| OnEnable/OnDisable | ReconstructBuffers/Dispose
|Vrm10FastSpringboneRuntime|ok| OnEnable/OnDisable | ReconstructBuffers/Dispose
|Vrm10FastSpringboneRuntimeStandalone|--|new/Dispose| ReconstructBuffers/Dispose
- service と combiner は null でないことを期待してよい
- combined は null かもしれない(null check している)
という API でよさそう。
=> [springbone] SpringBone が無いモデルの NullReferenceException を修正

Assets/VRM/Editor/Format/VRMEditorExporter.cs, Assets/VRM/Runtime/IO/VrmGeometryBackup.cs, Assets/VRM/Runtime/IO/VrmGeometryBackup.cs.meta, Assets/VRM10/Editor/Vrm10ExportDialog.cs, Assets/VRM10/Runtime/IO/Vrm10GeometryBackup.cs, Assets/VRM10/Runtime/IO/Vrm10GeometryBackup.cs.meta
freeze_pose 時に SpringBone と LookAtOffset を反映する機能を実装しました。
fixed #2426
fixed #2277
fixed #2368
=> [export][springbone] bake 時に SpringBone と LookAt に反映する実装

Assets/VRM/Runtime/SpringBone/Logic/SpringBoneJointInit.cs, Assets/VRM/Runtime/SpringBone/Logic/SpringBoneSystem.cs
fixed #2440
2nd arg is wrong.
```cs
// currentTail が center 適用前
// nextTail が center 適用後で処理されるバグ
m_joints[i] = (transform, init, SpringBoneJointState.Make(scene.Center, currentTail: state.CurrentTail, nextTail: nextTail);           
```
=> [0.x][springbone][center] fix center coordinate conversion

Assets/UniGLTF/Runtime/UniGLTF/IO/ImporterContext.cs, Assets/VRM10/Editor/ScriptedImporter/VrmScriptedImporterImpl.cs, Assets/VRM10/Editor/Vrm10ExportDialog.cs, Assets/VRM10/Runtime/Components/Vrm10Runtime/Vrm10NopSpringboneRuntime.cs, Assets/VRM10/Runtime/Components/Vrm10Runtime/Vrm10NopSpringboneRuntime.cs.meta, Assets/VRM10/Runtime/IO/Vrm10Importer.cs, ProjectSettings/QualitySettings.asset
```
A Native Collection has not been disposed, resulting in a memory leak. Allocated from:
```
- export 用の copy されたヒエラルキーの springbone が活動してしまう
- play 時に asset import すると、意図しない springbone の初期化が動作してしまう
に対処しました、
主にSpringBone の初期化フェーズを importer 内に移動したことが、影響しています。
=> [vrm10][Importer引数] ScriptedImpoter からの Import で SpringBone の初期化を回避する

Assets/VRM10/Runtime/Components/SpringBone/VRM10SpringBoneCollider.cs, Assets/VRM10/Runtime/Components/SpringBone/VRM10SpringBoneColliderGroup.cs, Assets/VRM10/Runtime/Components/SpringBone/VRM10SpringBoneJoint.cs, Assets/VRM10/Runtime/Components/Vrm10Instance/Vrm10InstanceSpringBone.cs
`OnDrawGizmosSelected` で配下の collider を gizmo 描画する。
context menu で子オブジェクトを作って、そっちに移動する。
これは、ひとつの secondary に複数の VRM10SpringBoneColliderGroup がアタッチされていると作業しづらいことに対する対策です。よさそうであれば、後に import 時に secondry の子オブジェクトを自動で作ってもよいかもしれない。
=> VRM10SpringBoneColliderGroup 改善

Assets/UniGLTF/Runtime/UniGLTF/IO/MeshIO/MeshExportInfo.cs
fixed #2472
現状 triangles のみをサポートしています。
unity
```cs
public enum MeshTopology
{
//
// Summary:
//     Mesh is made from triangles.
Triangles = 0,
//
// Summary:
//     Mesh is made from quads.
Quads = 2,
//
// Summary:
//     Mesh is made from lines.
Lines = 3,
//
// Summary:
//     Mesh is a line strip.
LineStrip = 4,
//
// Summary:
//     Mesh is made from points.
Points = 5
}
```
glTF
```json
"mode": {
"description": "The topology type of primitives to render.",
"default": 4, // triangles
"anyOf": [
{
"const": 0,
"description": "POINTS",
"type": "integer"
},
{
"const": 1,
"description": "LINES",
"type": "integer"
},
{
"const": 2,
"description": "LINE_LOOP",
"type": "integer"
},
{
"const": 3,
"description": "LINE_STRIP",
"type": "integer"
},
{
"const": 4,
"description": "TRIANGLES", …
```
=> [export][mesh] 三角形メッシュじゃない場合にスキップする

Assets/UniGLTF/Runtime/SpringBoneJobs/FastSpringBoneBufferCombiner.cs, Assets/UniGLTF/Runtime/SpringBoneJobs/FastSpringBoneConbinedBuffer.cs, Assets/UniGLTF/Runtime/SpringBoneJobs/InputPorts/FastSpringBoneBuffer.cs, Assets/VRM10/Runtime/Components/Vrm10Runtime/FastSpringBoneBufferFactory.cs
Vrm10FastSpringboneRuntime かつモデルが複数ある時に ReconstructSpringBone すると問題が再現する。
FastSpringBoneBufferCombiner が理解しきれていなかった。
初期化時の index ずれを修正。
=> [fastspringbone] InitCurrentTailsJob use spring.transformIndexOffset

Assets/UniGLTF/Runtime/UniHumanoid/AnimationClipUtility.cs
Fix AnimationClipUtility to use empty string for curve path instead off null which gives an error.
fixes #2503
=> Fix AnimationClipUtility to use empty string

Assets/VRM10/Runtime/IO/Material/BuiltInRP/Import/Materials/BuiltInVrm10MToonMaterialImporter.cs
Loading a `.vrm` file gives an "invalid alphaMode" warning in case no `alphaMode` is set. According to the glTF specification, the `alphaMode` property is not required and the default value is `OPAQUE` ([material.schema.json#L45](https://github.com/KhronosGroup/glTF/blob/main/specification/2.0/schema/material.schema.json#L45)).
This PR adds a case that treats `null` as `OPAQUE` without logging the warning. In case an actual invalid value is set, the warning is still logged.
=> Don't log warning when `alphaMode` property is not set on glTFMaterial

Assets/VRM10/Editor/Components/SpringBone/VRM10SpringBoneColliderEditor.cs, Assets/VRM10/Editor/Components/SpringBone/VRM10SpringBoneColliderGroupEditor.cs, Assets/VRM10/Editor/Components/SpringBone/VRM10SpringBoneColliderGroupEditor.cs.meta
`Drag Handle` ボタンを押すと移動ハンドルが表示される。
常時表示しないのは VRM10springBoneCollider が複数アタッチできるためです。
=> [VRM-1.0][springbone][editor] Collider の offset ドラッグを追加

Assets/UniGLTF/Runtime/UniGLTF/IO/ArrayByteBuffer.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/NativeArrayManager.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/gltfExporter.cs
Improved exporting performance drastically by increasing allocated buffer more than needed to be able to skip extending chunk by chunk. 
No difference in export quality
=> Fixes #2521 - Improving runtime GLTF export performance

Assets/UniGLTF/Runtime/UniGLTF/IO/gltfExporter.cs
Actually using progress parameter in GLTF Export constructor.
This enables progress callback for exports
=> Fixed #2519 - progress being used when given

Assets/UniGLTF/Runtime/SpringBoneJobs/InputPorts/FastSpringBoneBuffer.cs, Assets/UniGLTF/Runtime/UniGLTF/Format/glTFMesh.cs, Assets/UniGLTF/Runtime/UniGLTF/IO/MeshIO/MeshExporter_SharedVertexBuffer.cs
Fixes:
* Exporting in general when quads being used in meshes
* Quads being processed and split into two triangles
Added an enum for clarification on gltfPrimitive modes. (optional)
=> Refs #2525 - Exporting meshes with quads

.github/workflows/create-unitypackage.yml
GitHub Actions workflow において、step 間で作業ディレクトリの状態を引き継ぎたいのであれば job を分けるべきではない。
Job を横断して作業ディレクトリの状態が引き継がれるのは、Runner マシンがたまたま同一であるというだけ。
=> [Actions] Use steps instead of jobs in create-unitypackage action.

Assets/VRM10/MToon10/Shaders/vrmc_materials_mtoon.shader, Assets/VRM10/MToon10/Shaders/vrmc_materials_mtoon_lighting_mtoon.hlsl, Assets/VRM10/MToon10/Shaders/vrmc_materials_mtoon_urp.shader
Fixed https://github.com/vrm-c/UniVRM/issues/2505
仕様によれば、`matcapTexture` が指定されていないとき `0.0` として評価されるべきです。
> When the texture is not defined, it must be sampled as having 0.0 in RGB components.
https://github.com/vrm-c/vrm-specification/tree/master/specification/VRMC_materials_mtoon-1.0#matcaptexture
つまり `matcapFactor` の値がなんであれ、`matcapTexture` が指定されていないときは MatCap 項自体が `0.0` となるべきだということです。
しかし現状は `matcapFactor` の値が評価されていました。
これを修正します。
またあわせて `matcapFactor` のデフォルト値も仕様に合わせて変更します。
Material 新規作成時のデフォルト値が変わりますが、新規モデル制作時の話であり、その場合も見た目の挙動は変わりません。
> default: [1, 1, 1]
https://github.com/vrm-c/vrm-specification/tree/master/specification/VRMC_materials_mtoon-1.0#matcapfactor
=> `matcapTexture` should be 0.0 when it doesn't exist.

Assets/VRM10/Runtime/IO/Material/URP/Import/Materials/UrpVrm10MToonMaterialImporter.cs
MToon10Meta.URPUnityShaderNameがObsoleteになり、次のような警告が出ていました。
```
Assets/VRM10/Runtime/IO/Material/URP/Import/Materials/UrpVrm10MToonMaterialImporter.cs(30,29): warning CS0618: 'MToon10Meta.URPUnityShaderName' is obsolete: 'Use UnityUrpShaderName instead'
```
Obsoleteになった際のコミットはこちらです: https://github.com/vrm-c/UniVRM/pull/2484/commits/cce076d324ca35d69cac2423a10e98843d9315dc
代わりに、同内容の推奨されている定数 MToon10Meta.UnityUrpShaderName を使うようにしました。
=> MToon10Meta.URPUnityShaderNameがObsolete警告を出すのに対応

Assets/VRM10/Editor/Components/SpringBone/VRM10SpringBoneColliderGroupEditor.cs, Assets/VRM10/Editor/Vrm10InstanceEditor.cs
from https://github.com/vrm-c/UniVRM/issues/2559
unity2021では古い定義を利用するようにしました。
（作業の過程でClothSampleが2021で未定義なものを参照していたのに気付きましたが、一旦本体のfixのみに絞っています）
=> fix compile error in unity 2021

Assets/VRM/Editor/BuildClass.cs
Unity6でGraphicsSettings.renderPipelineAssetがObsoleteになり、次のような警告が出ていました。
```
Assets/VRM/Editor/BuildClass.cs(31,13): warning CS0618: 'GraphicsSettings.renderPipelineAsset' is obsolete: 'renderPipelineAsset has been deprecated. Use defaultRenderPipeline instead (UnityUpgradable) -> defaultRenderPipeline'
```
Unity6以降では、代わりとして推奨されるフィールド `defaultRenderPipeline` を使うようにしました。
=> Unity6でGraphicsSettings.renderPipelineAssetがObsolete警告を出すのに対応

.github/workflows/build-webgl.yml
```
Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v3`. Learn more: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
```
=> [fix action dependency] update workflow 

Assets/VRM10/MToon10/Shaders/vrmc_materials_mtoon.shader, Assets/VRM10/MToon10/Shaders/vrmc_materials_mtoon_urp.shader
https://github.com/vrm-c/UniVRM/pull/2540 では VRM 1.0 の仕様に準じて変更を行った。
しかし一方で UniVRM v0.128.0 以下のバージョンを利用して VRM 1.0 モデルを扱ったアプリケーションでは
依然、仕様違反の挙動のままである。
したがって v0.128.1 以上のバージョンで仕様として正しい VRM 1.0 モデルを作成したとしても、
過去のバージョンではおかしな見た目（真っ白）のモデルとしてインポートされてしまう。
例 : https://github.com/vrm-c/UniVRM/issues/2592
したがって、仕様違反の UniVRM v0.128.0 以下の環境であっても期待される見た目になるようなデフォルト値を選択する。
=> Ensure `matcapFactor` Compatibility with VRM 1.0 Models in UniVRM v0.128.0 and Earlier

Assets/UniGLTF/Runtime/UniGLTF/IO/NativeArrayManager.cs
以下のスクリーンショットは、手元のアプリケーションプログラムを実行した際、
VRM ファイルをロードしたフレームでの Unity Profiler の様子です
ここで、 GC Alloc の量が目立つ場所の１つに `NativeArrayManager.CreateNativeArray<T>()` 下の ``ArraySegment`1.ToArray()`` があります。
UniVRM v0.128.3 の時点での、このコードの実体は以下のようなループコピーですが
https://github.com/vrm-c/UniVRM/blob/v0.128.3/Assets/UniGLTF/Runtime/UniGLTF/IO/NativeArrayManager.cs#L69-L75
```C#
public NativeArray<T> CreateNativeArray<T>(
ArraySegment<T> data
) where T : struct
{
var array = CreateNativeArray<T>(data.Count);
for (int i = 0; i < data.Count; i++)
array[i] = data.Array[data.Offset + i];
return array;
}
```
ループ内の `data.Array[]` によって `ArraySegment<>.ToArray()` が呼び出されているため、結果として大量の GC Alloc が発生する場合があります。
この PR では、 `ArraySegment.ToArray()` による GC Alloc を避けるために `Span` を使用しています。
Unity 2022 以降では、 `NativeArray`, `ArraySegment` …
=> SpanによるUniGLTF.NativeArrayManager.CreateNativeArray(ArraySegment)の改善

Assets/UniGLTF/Runtime/UniGLTF/IO/TextureIO/Import/UnitySupportedImageTypeDeserializer.cs
`UnitySupportedImageTypeDeserializer` に `MarkNonReadable` プロパティを追加します。
このプロパティは、`UnityEngine.ImageConvertesion.LoadImage()` の第二引数 `markNonReadable` として使用されます。
`true` を指定した場合、CPUからアクセス可能なメモリを持たなくなるため、テクスチャの書き換えができなくなりますが、代わりにアプリのメモリ使用量を削減できる場合があります。
フラグの詳細については `UnityEngine.Texture2D.Apply` の `makeNoLongerReadable` の説明を参照して下さい。
Close #2607 
```C#
public class MySample : MonoBehaviour {
[SerializeField] private string vrmPath = "MyAsset/MyModel.vrm";
private Vrm10Instance _vrm10Instance = null;
private void OnEnable() => Run();
private async Task Run() {
UnitySupportedImageTypeDeserializer textureDeserializer = new()
{
MarkNonReadable = true // MarkNonReadable を指定
};
_vrm10Instance = await Vrm10.LoadPathAsync(
vrmPath,
canLoadVrm0X: true,
controlRigGenerationOption: default,
showMeshes: …
```
=> Add: UnitySupportedImageTypeDeserializer に MarkNonReadable プロパティを追加

Assets/UniGLTF/Runtime/SpringBoneJobs/FastSpringBoneBufferCombiner.cs, Assets/UniGLTF/Runtime/SpringBoneJobs/FastSpringBoneConbinedBuffer.cs, Assets/VRM/Runtime/SpringBone/Jobs/Vrm0XFastSpringBoneRuntime.cs, Assets/VRM10/Runtime/Components/Vrm10Runtime/Vrm10FastSpringboneRuntime.cs, Assets/VRM10/Runtime/Components/Vrm10Runtime/Vrm10FastSpringboneRuntimeStandalone.cs
fixed #2611
#2609 のバグだった
ついでに unregister + register を一関数で一度にできるようにして、
あわせて順番が変わらないようにした。
=> [SpringBone] reconstruct 時の center の index の offset 足し忘れを修正

Assets/VRM10/MToon10/Shaders/vrmc_materials_mtoon_geometry_vertex.hlsl
MToon10シェーダーでは outlineWidthMultiplyTexture について R チャンネルを参照しておりますが、これはvrm-specificationと異なっております。
>### outlineWidthMultiplyTexture
>The texture to set multiplication factor of outline width. If it is not assigned, the value of outlineWidthFactor is used directly.
>The components of the texture are stored in linear colorspace. The G component of the texture is referred to.
https://github.com/vrm-c/vrm-specification/tree/master/specification/VRMC_materials_mtoon-1.0#outlinewidthmultiplytexture
仕様に合うようMToon10シェーダーを修正します。
=> Fix MToon10: Use G channel for outline width tex to match the specification

Assets/VRM/Editor/Format/VRMVersionMenu.cs, Assets/VRM10/package.json
fixed #2602
最近の新規 project の template だと最初から  Packages/manifest.json に com.unity.timeline が含まれているぽい。
含まれていない template を選択したり、過去のバージョンから引き継がれたプロジェクトでは無いかもしれない。
=> add dependency to com.unity.timeline

Assets/VRM10_Samples/MToon10Showcase/MToon10Showcase.unity, Assets/VRM10_Samples/MToon10Showcase/Runtime/MToon10ShowcaseEntryPoint.cs, Assets/VRM10_Samples/MToon10Showcase/Runtime/TopDownCapture.cs, Assets/VRM10_Samples/MToon10Showcase/Runtime/TopDownCapture.cs.meta, Assets/VRM10_Samples/MToon10Showcase/Runtime/VRM10.Samples.MToon10Showcase.asmdef
MToon10 Showcase シーンにマテリアル撮影機能を追加します。
この機能の目的は、異なるUniVRMバージョン間におけるMToon10のレンダリング結果の比較を容易にすることです。
シーンを開始すると、マテリアルの撮影が自動的に実行されます。
また、GameViewのボタンから撮影した画像の表示およびpngの保存ができます。
この機能の目的を達成するにあたり、ひとつ障害があります。それは、撮影結果の一部がGameViewのレンダリング結果と異なることです。
OutlineMode = ScreenのOutlineが設定されたマテリアルについて、撮影画像に映るアウトラインの形状が歪みます。これは、撮影に使用するカメラの変則的なアスペクト比に起因するものと思われます。
=> Add capture feature to MToon10 Showcase

Assets/VRM10_Samples/MToon10Showcase/Editor/CustomEditor/AlphaModeEntryDrawer.cs, Assets/VRM10_Samples/MToon10Showcase/Editor/CustomEditor/AlphaModeEntryDrawer.cs.meta, Assets/VRM10_Samples/MToon10Showcase/Editor/CustomEditor/EmissionEntryDrawer.cs, Assets/VRM10_Samples/MToon10Showcase/Editor/CustomEditor/EmissionEntryDrawer.cs.meta, Assets/VRM10_Samples/MToon10Showcase/Editor/CustomEditor/GIEqualizationEntryDrawer.cs, Assets/VRM10_Samples/MToon10Showcase/Editor/CustomEditor/GIEqualizationEntryDrawer.cs.meta, Assets/VRM10_Samples/MToon10Showcase/Editor/CustomEditor/MatcapEntryDrawer.cs, Assets/VRM10_Samples/MToon10Showcase/Editor/CustomEditor/MatcapEntryDrawer.cs.meta, Assets/VRM10_Samples/MToon10Showcase/Editor/CustomEditor/NormalMapEntryDrawer.cs, Assets/VRM10_Samples/MToon10Showcase/Editor/CustomEditor/NormalMapEntryDrawer.cs.meta, Assets/VRM10_Samples/MToon10Showcase/Editor/CustomEditor/OutlineEntryDrawer.cs, Assets/VRM10_Samples/MToon10Showcase/Editor/CustomEditor/OutlineEntryDrawer.cs.meta, Assets/VRM10_Samples/MToon10Showcase/Editor/CustomEditor/PrametricRimEntryDrawer.cs, Assets/VRM10_Samples/MToon10Showcase/Editor/CustomEditor/PrametricRimEntryDrawer.cs.meta, Assets/VRM10_Samples/MToon10Showcase/Editor/CustomEditor/RenderQueueOffsetEntryDrawer.cs, Assets/VRM10_Samples/MToon10Showcase/Editor/CustomEditor/RenderQueueOffsetEntryDrawer.cs.meta, Assets/VRM10_Samples/MToon10Showcase/Editor/CustomEditor/RimLightingEntryDrawer.cs, Assets/VRM10_Samples/MToon10Showcase/Editor/CustomEditor/RimLightingEntryDrawer.cs.meta, Assets/VRM10_Samples/MToon10Showcase/Editor/CustomEditor/ShadingShiftEntryDrawer.cs, Assets/VRM10_Samples/MToon10Showcase/Editor/CustomEditor/ShadingShiftEntryDrawer.cs.meta, Assets/VRM10_Samples/MToon10Showcase/Editor/CustomEditor/ShadingToonyEntryDrawer.cs, Assets/VRM10_Samples/MToon10Showcase/Editor/CustomEditor/ShadingToonyEntryDrawer.cs.meta, Assets/VRM10_Samples/MToon10Showcase/Editor/CustomEditor/UVAnimationEntryDrawer.cs, Assets/VRM10_Samples/MToon10Showcase/Editor/CustomEditor/UVAnimationEntryDrawer.cs.meta, Assets/VRM10_Samples/MToon10Showcase/Editor/VRM10.Samples.MToon10Showcase.Editor.asmdef, Assets/VRM10_Samples/MToon10Showcase/Runtime/ShowcaseTemplates/OutlineShowcase.cs
MToon10 Showcase に CustomPropertyDrawer を追加し、マテリアル設定値を保持する ScriptableObject の Inpector の視認性を改善します。
=> Add CustomPropertyDrawer to MToon10 Showcase

Assets/VRM10_Samples/VRM10Viewer/UIToolkit/VRM10MainView.cs, Assets/VRM10_Samples/VRM10Viewer/VRM10ViewerController.cs, Assets/VRM10_Samples/VRM10Viewer/uGui/VRM10ViewerUI.cs
- FileDialog が動かなくなっていたのを修正
- deprecated の WWWを UnityWebRequest に置き換え
=> [VRM10Viewer][WebGL] FileDialog復旧。WWW警告解決

Assets/VRM10/Samples~/VRM10Viewer/UIToolkit/MainView.asset, Assets/VRM10/Samples~/VRM10Viewer/UIToolkit/UnityDefaultRuntimeTheme.tss, Assets/VRM10/Samples~/VRM10Viewer/UIToolkit/UnityDefaultRuntimeTheme.tss.meta, Assets/VRM10_Samples/VRM10Viewer/UIToolkit/MainView.asset, Assets/VRM10_Samples/VRM10Viewer/UIToolkit/UnityDefaultRuntimeTheme.tss, Assets/VRM10_Samples/VRM10Viewer/UIToolkit/UnityDefaultRuntimeTheme.tss.meta
VRM10Viewer で unigypackage 経由の場合に UnityDefaultRuntimeTheme.tss への参照が外れてしまう。
VRM10Viewer フォルダに `Assets/UI Toolkit/UnityThemes/UnityDefaultRuntimeTheme.tss` をコピーして、それを参照することにしました。
=> [uitoolkit] missing UnityDefaultRuntimeTheme.tss

Assets/UniGLTF/Runtime/UniGLTF/IO/NativeArrayManager.cs
=> Fix NativeArrayManager compatibility with Unity 2022.1 and older versions

Assets/UniGLTF/Runtime/UniGLTF/IO/MeshIO/MeshUploader.cs
Since local variable `positions[]` always contains valid result of `blendShape.Positions.ToArray()`, we can reuse it to eliminate redundant `ToArray()` which also causes extra GC Alloc.
Memo: The other variable `normals[]` seems to be used as expected.
ローカル変数 `positions[]` は常に正しい `blendShape.Positions.ToArray()` の 結果を保持しているので、これを再利用することで余分な `ToArray()` および GC Alloc を抑制することができます。
メモ : もう一方の変数 `normals[]` は期待通りに使用されているように見えます。
=> chore: Reuse `positions` to eliminate redundant `ToArray()`

Assets/VRM10/MToon10/Shaders/vrmc_materials_mtoon_utility.hlsl
tangent Sign は本来、+1 か -1 の値が望まれる。そしてこれは通常、三角形内ですべておなじ値である。
しかし Unity 純正の `Mesh.RecalculateTangents()` を呼び出すと、頂点ごとに異なる tangent Sign を持つ三角形が生まれることがある。
その場合 interpolate されて 0 となり、ゼロ除算と NaN が発生し、Android 環境等 `half` 精度が採択された場合に、ビジュアルアーティファクトが顕著に出る場合がある。
そのためピクセルシェーダで tangent Sign を二値化する。
この処理は URP/Lit では行われていないが、URP/Lit では tangent を `float` とすることでたまたま回避できている。
ShaderGraph 製シェーダでは本 PullReq と同様の処理がなされているように読める。
UniVRM では UniGLTF の `ImporterContext` でのメッシュ生成時に `Mesh.RecalculateTangents()` を呼び出しているため、法線マップを利用するすべての glTF, VRM0.X, VRM1.0 に影響する。
https://github.com/vrm-c/UniVRM/blob/5885004730eb6843f61f6251f5fb4eb9d41adb70/Assets/UniGLTF/Runtime/UniGLTF/IO/MeshIO/MeshUploader.cs#L113
したがって根本的には、よりよい tangent 計算手法に置き換える必要があるが、本 PullReq では行わない。
図１：細かいが、黒線のアーティファクト。NaN のため、Bloom などをかけると非常に拡散する。 …
=> fix(tangent): binarize tangent.w to ±1 to prevent NaNs and artifacts

Assets/UniGLTF/Runtime/SpringBoneJobs/FastSpringBoneScheduler.cs, Assets/VRM10/Runtime/FastSpringBone/FastSpringBoneService.cs
HybridECS環境など、独自のJob管理を行いたい場合のオプションとして、FastSpringBone Job の JobHandle を受け取ることができる ManualUpdate のオーバーロードを追加しました
=> FastSpringBoneジョブのJobHandleをより柔軟に扱えるようにする変更

Assets/VRM10/Runtime/Components/Vrm10Runtime/Springbone/IVrm10SpringBoneRuntime.cs, Assets/VRM10/Runtime/Components/Vrm10Runtime/Springbone/Vrm10FastSpringboneRuntime.cs, Assets/VRM10/Runtime/Components/Vrm10Runtime/Springbone/Vrm10FastSpringboneRuntimeStandalone.cs, Assets/VRM10/Runtime/Components/Vrm10Runtime/Springbone/Vrm10NopSpringboneRuntime.cs, Assets/VRM10/Runtime/Components/Vrm10Runtime/Vrm10Runtime.cs, Assets/VRM10_Samples/ClothSample/ClothWarp/Runtime/ClothWarpRuntime.cs, Assets/VRM10_Samples/ClothSample/ClothWarp/Runtime/Jobs/ClothWarpJobRuntime.cs
SpringBoneの時間経過処理を任意の時間で評価できるように`IVrm10SpringBoneRuntime.Process()`関数に`deltaTime`引数を追加した。
=> IVrm10SpringBoneRuntimeのProcess関数にdeltaTime引数を追加

Assets/UniGLTF/Runtime/SpringBoneJobs/Anglelimit/Anglelimit.cs, Assets/UniGLTF/Runtime/SpringBoneJobs/Blittables/BlittableJointMutable.cs, Assets/VRM10/Editor/Components/SpringBone/VRM10SpringBoneJointEditor.cs, Assets/VRM10/Runtime/Components/SpringBone/VRM10SpringBoneJoint.cs, Assets/VRM10/Runtime/Components/Vrm10Runtime/Springbone/FastSpringBoneBufferFactory.cs
=> [SpringBoneLimit] 動くようにした

Assets/VRM10/Editor/Components/SpringBone/VRM10SpringBoneJointEditor.cs, Assets/VRM10/Runtime/Components/Vrm10Instance/Vrm10InstanceSpringBone.cs
SpringBoneLimit 拡張の続きです。
この PR では、関連するカスタムエディターを実装しました。
SpringBone のロジック間違い(角度制限の効き方が gizmo の見た目と一致していないような)などは後の PR で改めてやります。
gizmo と custom editor のみに注目。
=> [SpringBoneLimit] SpringBone LimitSpace gizmo

Assets/VRM10/Editor/Components/SpringBone/VRM10SpringBoneJointEditor.cs, Assets/VRM10/Runtime/Components/SpringBone/VRM10SpringBoneJoint.cs, Assets/VRM10/Runtime/Format/SpringBoneLimit/Deserializer.g.cs, Assets/VRM10/Runtime/Format/SpringBoneLimit/Format.g.cs, Assets/VRM10/Runtime/Format/SpringBoneLimit/Serializer.g.cs, Assets/VRM10/Runtime/IO/Vrm10Exporter.cs, Assets/VRM10/Runtime/IO/Vrm10Importer.cs
- gizmo と動作のずれを検証して、　~~ロジックを修正した。( 角度を 0.5 倍 )~~ => gizmo の方を修正
- 変数名、
- m_angleLimitRotation => m_limitSpaceOffset
- m_angleLimitAngle1 => m_phi => m_pitch
- m_angleLimitAngle2 => m_theta  => m_yaw
- ~~phi, theta~~ pitch, yaw(Sphericalの第２角度) が見た目に分かるように gizmo を増やした
- theta の値域 pi/2。初期値 0
=> [SpringboneLimit] gizmo 仕様合わせ
